import fs from 'fs';

const products = [];

// Helper to push product
function addProduct(p) {
  products.push(p);
}

// 1. SUITS (32 Products)
const suitDefs = [
  {
    name: 'N.K FABRICS Savile Row Chalk Stripe Three-Piece',
    price: 4400,
    tagline: 'English Worsted Navy Chalk Stripe with Sculpted High-V Waistcoat',
    description: 'The commanding boardroom authority. Crafted from heavyweight English chalk stripe flannel with roped structured shoulders, hand-sewn buttonholes, and a matching six-button waistcoat with watch chain pocket.',
    img1: 'CHALK_STRIPE', img2: 'NAVY_SUIT',
    colors: [{ name: 'Navy Chalk Stripe', hex: '#152238' }, { name: 'Charcoal Chalk Stripe', hex: '#2B2B2B' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'English Worsted Flannel with Natural Chalk Pinstripe (320g/m)',
    fabricOrigin: 'Fox Brothers & Co., Somerset, UK',
    fit: 'Classic Formal', occasion: 'Business & Boardroom', collection: 'Signature Collection',
    notes: ['Authentic Savile Row roped shoulder (con rollino)', 'High-V sculpted waistcoat with watch chain eyelet', 'Flat-front trousers with forward pleats and brass side adjusters'],
    newArrival: true, bestSeller: true,
  },
  {
    name: 'N.K FABRICS Black Signature Three-Piece Suit',
    price: 4200,
    tagline: 'Super 160s Virgin Wool with Silk Satin Details & Tailored Waistcoat',
    description: 'The definitive black-tie power suit. Hand-padded floating horsehair canvas ensures an immaculate roll across the chest, paired with a matching five-button tailored waistcoat and sharp pleated dress trousers.',
    img1: 'BLACK_SUIT', img2: 'FABRIC_DETAIL',
    colors: [{ name: 'Deep Black', hex: '#0C0C0C' }, { name: 'Midnight Charcoal', hex: '#1C1C1E' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Super 160s Virgin Wool & Cashmere (270g/m)',
    fabricOrigin: 'Loro Piana, Quarona, Italy',
    fit: 'Tailored Regular', occasion: 'Evening Black-Tie', collection: 'Signature Collection',
    notes: ['Full floating horsehair canvas construction', 'Hand-carved buffalo horn buttons with micro-engraved N.K FABRICS insignia', 'Pick-stitched lapels and interior cupro pocket linings'],
    bestSeller: true,
  },
  {
    name: 'N.K FABRICS Midnight Navy Peak-Lapel Three-Piece',
    price: 3850,
    tagline: 'Super 150s Tasmanian Merino Wool with Matching Double-Breasted Waistcoat',
    description: 'Sculpted in the quintessential Savile Row silhouette with roped shoulders, a broad 3.75-inch peak lapel, and a matching six-button double-breasted waistcoat that contours the torso effortlessly.',
    img1: 'NAVY_SUIT', img2: 'BACK_PROFILE',
    colors: [{ name: 'Midnight Navy', hex: '#121A2A' }, { name: 'Dark Navy', hex: '#0B1320' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Super 150s Tasmanian Merino Wool (250g/m)',
    fabricOrigin: 'Scabal, Huddersfield, England',
    fit: 'Tailored Regular', occasion: 'Business & Boardroom', collection: 'Formal Collection',
    notes: ['Milanese hand-sewn lapel buttonhole taking 45 minutes of artisan handwork', 'Double rear vents engineered to prevent bunching when seated', 'High-rise double forward-pleated trousers with 2-inch cuffs'],
    newArrival: true,
  },
  {
    name: 'N.K FABRICS Mayfair Charcoal Flannel Suit',
    price: 3600,
    tagline: 'English Worsted Flannel with 5-Button High-V Waistcoat',
    description: 'The quintessential British executive suit. Tailored from soft yet resilient worsted flannel, delivering exceptional drape, crease recovery, and understated gravitas.',
    img1: 'HERO_MODELS', img2: 'TROUSER_CHARCOAL',
    colors: [{ name: 'Charcoal', hex: '#242424' }, { name: 'Anthracite', hex: '#333333' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Worsted Wool Flannel (310g/m)',
    fabricOrigin: 'Huddersfield Fine Worsteds, Yorkshire, UK',
    fit: 'Classic Formal', occasion: 'Business & Boardroom', collection: 'Business Collection',
    notes: ['Gentle waist suppression with natural drape chest', 'Generous notch lapels with flower loop on under-collar', 'Suspender buttons installed inside trouser waistband'],
  },
  {
    name: 'N.K FABRICS Venetian Midnight Velvet Tuxedo',
    price: 4600,
    tagline: 'Silk-Cotton Italian Velvet with Corded Silk Shawl Collar',
    description: 'The pinnacle of black-tie opulence. Handcrafted from heavy Venetian cotton-silk velvet with an extraordinary nocturnal luster, finished with deep grosgrain shawl lapels.',
    img1: 'EVENING_SUIT', img2: 'BLACK_SUIT',
    colors: [{ name: 'Midnight Velvet Noir', hex: '#0A0A0A' }, { name: 'Royal Navy Velvet', hex: '#0B1526' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Italian Silk Velvet with Heavy Luster (360g/m)',
    fabricOrigin: 'Redaelli Velluti, Como, Italy',
    fit: 'Tailored Regular', occasion: 'Evening Black-Tie', collection: 'Evening Collection',
    notes: ['Continuous corded silk shawl lapel', 'Fabric-covered silk tuxedo buttons', 'Pure silk trouser side stripe braid'],
    newArrival: true,
  },
  {
    name: 'N.K FABRICS Royal Emerald Silk-Blend Evening Suit',
    price: 4350,
    tagline: 'Imperial Forest Emerald Wool-Silk with Black Satin Peak Lapels',
    description: 'A sovereign evening creation. Woven from a blend of ultra-fine wool and mulberry silk in an imperial forest emerald hue, framed by jet black silk satin peak lapels.',
    img1: 'EMERALD_SILK', img2: 'EVENING_SUIT',
    colors: [{ name: 'Forest Emerald', hex: '#0E281E' }, { name: 'Nocturne Green', hex: '#091A14' }],
    sizes: ['38R', '40R', '42R', '44R'],
    fabric: 'Super 150s Wool & Mulberry Silk (250g/m)',
    fabricOrigin: 'Dormeuil, France & UK',
    fit: 'Slim Fit', occasion: 'Wedding & Gala', collection: 'Wedding Collection',
    notes: ['Contrast midnight silk peak lapels', 'Matching emerald low-cut waistcoat', 'Jet black satin braided trousers'],
  },
  {
    name: 'N.K FABRICS Prince of Wales Glen Plaid Suit',
    price: 4150,
    tagline: 'Classic Glen Urquhart Plaid with Subtle Sky Blue Deco Overcheck',
    description: 'The timeless aristocrat pattern. Cut with soft Neapolitan shoulders and high gorge lapels, accented by a subtle sky blue overcheck woven from high-twist tropical wool.',
    img1: 'HERO_MODELS', img2: 'CHALK_STRIPE',
    colors: [{ name: 'Glen Plaid Grey', hex: '#4A4A4A' }, { name: 'Charcoal Deco', hex: '#2E2E2E' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Super 140s High-Twist Wool (260g/m)',
    fabricOrigin: 'Vitale Barberis Canonico, Biella, Italy',
    fit: 'Tailored Regular', occasion: 'Business & Boardroom', collection: 'Business Collection',
    notes: ['Spalla camicia shirt-sleeve shoulder for natural comfort', 'Barchetta curved breast pocket for silk flare', 'Matching double-breasted 6-button vest included'],
    bestSeller: true,
  },
  {
    name: 'N.K FABRICS Espresso Peak-Lapel Evening Suit',
    price: 4100,
    tagline: 'Deep Espresso Wool-Silk with Lustrous Silk Satin Lapels',
    description: 'An unconventional evening triumph. Replaces standard black tie with an opulent deep espresso brown that absorbs nocturnal ambient light with velvety warmth.',
    img1: 'EVENING_SUIT', img2: 'BLACK_SUIT',
    colors: [{ name: 'Deep Espresso', hex: '#251C17' }, { name: 'Dark Chocolate', hex: '#1C1512' }],
    sizes: ['38R', '40R', '42R', '44R'],
    fabric: '75% Fine Wool, 25% Mulberry Silk (240g/m)',
    fabricOrigin: 'Ermenegildo Zegna Lanificio, Trivero, Italy',
    fit: 'Tailored Regular', occasion: 'Evening Black-Tie', collection: 'Evening Collection',
    notes: ['Silk satin faced dramatic sweeping peak lapels', 'Low-scoop evening waistcoat with covered satin buttons', 'Silk satin braided trouser outseams'],
  },
  {
    name: 'N.K FABRICS Sovereign Camel Drape Suit',
    price: 4800,
    tagline: '100% Baby Camelhair & Cashmere with Natural Horn Buttons',
    description: 'An exceptional cold-weather monument. Woven from Mongolian baby camelhair and cashmere, creating an unparalleled golden luster, thermal insulation, and cloud-like handfeel.',
    img1: 'HERO_MODELS', img2: 'FABRIC_DETAIL',
    colors: [{ name: 'Golden Camel', hex: '#B88B4A' }, { name: 'Warm Taupe', hex: '#8B7355' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Baby Camelhair & Mongolian Cashmere (380g/m)',
    fabricOrigin: 'Piacenza 1733, Biella, Italy',
    fit: 'Classic Formal', occasion: 'Everyday Luxury', collection: 'Winter Collection',
    notes: ['Colossal notch lapels with Milanese buttonholes', 'Mottled honey horn buttons', 'Interior silk ticket pocket with custom monogram'],
    newArrival: true,
  },
  {
    name: 'N.K FABRICS Oxford Navy Birdseye Drape Suit',
    price: 3550,
    tagline: 'Micro-Textured Birdseye High-Twist Wool All-Season Suit',
    description: 'The sharpest everyday business suit. The micro-birdseye weave introduces visual depth while the high-twist yarns resist rumpling during long international flights.',
    img1: 'NAVY_SUIT', img2: 'CHALK_STRIPE',
    colors: [{ name: 'Oxford Navy', hex: '#162842' }, { name: 'Steel Blue', hex: '#263D5C' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Super 130s Pure Wool Birdseye (260g/m)',
    fabricOrigin: 'Vitale Barberis Canonico, Biella',
    fit: 'Tailored Regular', occasion: 'Business & Boardroom', collection: 'Business Collection',
    notes: ['Two-button front with 3.5-inch notch lapels', 'Lightly roped shoulder construction', 'Includes matching 5-button high-V waistcoat'],
  },
  {
    name: 'N.K FABRICS Westminster 6x2 Double-Breasted Suit',
    price: 3950,
    tagline: 'Heavyweight Worsted Twill with Sweeping 4-Inch Peak Lapels',
    description: 'The classic British power silhouette. Six-button double-breasted arrangement with deep waist suppression and high armholes, finished with hand-padded floating canvas.',
    img1: 'BLACK_SUIT', img2: 'TROUSER_CHARCOAL',
    colors: [{ name: 'Charcoal Grey', hex: '#222222' }, { name: 'Midnight Blue', hex: '#101726' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Heavy British Worsted Wool Twill (340g/m)',
    fabricOrigin: 'Huddersfield Fine Worsteds, UK',
    fit: 'Classic Formal', occasion: 'Formal Collection', collection: 'Formal Collection',
    notes: ['Traditional 6x2 button stance with 4-inch sweeping peak lapels', 'Reinforced Milanese lapel flower loop', 'Fishtail back trousers designed for button suspenders'],
  },
  {
    name: 'N.K FABRICS Riviera Taupe Silk-Linen Summer Suit',
    price: 3650,
    tagline: 'Unstructured Neapolitan Cut in Italian Silk-Linen Blend',
    description: 'Effortless Mediterranean sprezzatura. Unlined construction with open-weave Irish linen and mulberry silk that breathes in high summer while draping with architectural crispness.',
    img1: 'ESSENTIALS_POLO', img2: 'HERO_MODELS',
    colors: [{ name: 'Warm Taupe', hex: '#A89F91' }, { name: 'Sandstone', hex: '#C2B8A3' }],
    sizes: ['38R', '40R', '42R', '44R'],
    fabric: '55% Irish Linen, 45% Mulberry Silk (230g/m)',
    fabricOrigin: 'Baird McNutt, Northern Ireland',
    fit: 'Relaxed Drape', occasion: 'Resort & Casual', collection: 'Summer Collection',
    notes: ['Completely unlined quarter-back construction', 'Patch hip pockets with curved barchetta lines', 'Drawstring side-tab convertible trousers'],
  },
  {
    name: 'N.K FABRICS Ivory Tropical Formal Suit',
    price: 3950,
    tagline: 'Tropical High-Ventilation Worsted Wool with Pearlized Waistcoat',
    description: 'The pinnacle of warm-weather aristocracy. An airy open tropical weave creates unparalleled breathability, finished with carved mother-of-pearl buttons and Hollywood high-waist double-pleat trousers.',
    img1: 'ESSENTIALS_POLO', img2: 'TRAD_IVORY',
    colors: [{ name: 'Ivory', hex: '#FAF8F5' }, { name: 'Cream', hex: '#ECE7DD' }],
    sizes: ['40R', '42R', '44R'],
    fabric: 'Tropical High-Ventilation Worsted Wool (220g/m)',
    fabricOrigin: 'Holland & Sherry, Savile Row',
    fit: 'Classic Formal', occasion: 'Wedding & Gala', collection: 'Wedding Collection',
    notes: ['Quarter-lined cupro interior for maximum cooling ventilation', 'Double-breasted four-button jacket with peak lapels', 'Hollywood high-waist trousers with 2-inch turn-up cuffs'],
  },
  {
    name: 'N.K FABRICS Milanese Dark Grey Sartorial Two-Piece',
    price: 3450,
    tagline: 'Anthracite High-Twist Wool with Neapolitan Soft Shoulder',
    description: 'Engineered for seamless continental travel. Unstructured spalla camicia shirt-shoulder construction allows total freedom of motion while high-twist wool naturally sheds creases.',
    img1: 'NAVY_SUIT', img2: 'TROUSER_CHARCOAL',
    colors: [{ name: 'Dark Grey', hex: '#303030' }, { name: 'Charcoal', hex: '#1E1E1E' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Super 130s High-Twist All-Season Wool (250g/m)',
    fabricOrigin: 'Vitale Barberis Canonico, Biella',
    fit: 'Tailored Regular', occasion: 'Business & Boardroom', collection: 'Business Collection',
    notes: ['Barchetta curved chest pocket for handkerchief flare', 'Single-pleat tapered trousers with side tab adjusters', 'Bespoke floating canvas interlining'],
  },
  {
    name: 'N.K FABRICS Bordeaux Velvet Dinner Suit',
    price: 4500,
    tagline: 'Deep Wine Silk Velvet with Grosgrain Peak Lapels & Trousers',
    description: 'A theatrical triumph for galas and seasonal premieres. Deep bordeaux velvet cut in a single-button evening stance with satin-faced grosgrain peak lapels.',
    img1: 'EVENING_SUIT', img2: 'BLACK_SUIT',
    colors: [{ name: 'Deep Bordeaux', hex: '#4A0E17' }, { name: 'Midnight Wine', hex: '#33080F' }],
    sizes: ['38R', '40R', '42R', '44R'],
    fabric: 'Italian Cotton-Silk Velvet (350g/m)',
    fabricOrigin: 'Pontoglio 1883, Brescia, Italy',
    fit: 'Slim Fit', occasion: 'Evening Black-Tie', collection: 'Evening Collection',
    notes: ['Grosgrain faced peak lapels', 'Single-button evening stance with covered buttons', 'Midnight braided evening trousers'],
    newArrival: true,
  },
  {
    name: 'N.K FABRICS Light Grey Sharkskin Executive Two-Piece',
    price: 3500,
    tagline: 'Lustrous Super 150s Sharkskin Twill with Roped Shoulder',
    description: 'The sharp modern executive suit. The twill weave alternates light and dark threads for a silvery metallic depth that commands daytime conference presence.',
    img1: 'HERO_MODELS', img2: 'CHALK_STRIPE',
    colors: [{ name: 'Light Grey Sharkskin', hex: '#8C929D' }, { name: 'Silver Slate', hex: '#A2A8B3' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Super 150s Merino Wool Sharkskin (260g/m)',
    fabricOrigin: 'Loro Piana, Quarona, Italy',
    fit: 'Tailored Regular', occasion: 'Business & Boardroom', collection: 'Business Collection',
    notes: ['Roped shoulder head with hand-padded canvas', 'Slanted hacking hip pockets with ticket pocket', 'Side buckle tab forward pleated trousers'],
  },
  {
    name: 'N.K FABRICS Solaro Sunburst Herringbone Suit',
    price: 3900,
    tagline: 'Original British Solaro Fabric with Iridescent Copper-Green Luster',
    description: 'Legendary among bespoke connoisseurs. Woven with olive-green face yarns and crimson-brick reverse threads, creating an extraordinary two-tone sunburst reflection in daylight.',
    img1: 'ESSENTIALS_POLO', img2: 'HERO_MODELS',
    colors: [{ name: 'Solaro Olive-Copper', hex: '#635B48' }, { name: 'Bronze Sand', hex: '#7D7055' }],
    sizes: ['38R', '40R', '42R', '44R'],
    fabric: 'Original Wool Solaro Twill (290g/m)',
    fabricOrigin: 'Smith Woollens, Savile Row, London',
    fit: 'Tailored Regular', occasion: 'Premium Collection', collection: 'Premium Collection',
    notes: ['Classic 3-roll-2 button stance', 'Unlined body with bound silk seams', 'High-rise Hollywood waistband trousers'],
  },
  {
    name: 'N.K FABRICS Chocolate Brown Flannel Three-Piece',
    price: 3750,
    tagline: 'Rich Chocolate Wool Flannel with Double-Breasted Waistcoat',
    description: 'A sophisticated departure from navy and grey. Heavyweight wool flannel dyed in an appetizing bitter chocolate tone, paired with a sculpted 6-button vest.',
    img1: 'HERO_MODELS', img2: 'TROUSER_CHARCOAL',
    colors: [{ name: 'Bitter Chocolate', hex: '#2A1C16' }, { name: 'Roasted Espresso', hex: '#221611' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'English Worsted Flannel (320g/m)',
    fabricOrigin: 'Fox Brothers, Somerset, UK',
    fit: 'Classic Formal', occasion: 'Winter Collection', collection: 'Winter Collection',
    notes: ['Matching 6-button double-breasted vest with lapel', 'Real dark horn buttons with cross stitch', 'Turn-up 2-inch trouser cuffs'],
  },
  {
    name: 'N.K FABRICS Pearl Grey Wedding Ceremony Suit',
    price: 4300,
    tagline: 'Super 160s Pearl Grey Wool-Silk with Embroidered Silk Vest',
    description: 'Engineered for grand wedding occasions. A pale silvery pearl grey with exceptional light refraction, accompanied by an ivory and champagne damask waistcoat.',
    img1: 'TRAD_IVORY', img2: 'HERO_MODELS',
    colors: [{ name: 'Pearl Grey', hex: '#B8BCC4' }, { name: 'Platinum Silver', hex: '#D2D6DE' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Super 160s Wool & Mulberry Silk (250g/m)',
    fabricOrigin: 'Dormeuil, France & UK',
    fit: 'Tailored Regular', occasion: 'Wedding & Gala', collection: 'Wedding Collection',
    notes: ['Includes embroidered silk wedding waistcoat', 'Mother-of-pearl buttons with metal shank', 'Silk-lined pleated trousers'],
    newArrival: true,
  },
  {
    name: 'N.K FABRICS Glen Check Charcoal Three-Piece',
    price: 3850,
    tagline: 'Black & White Micro Glen Check with Tonal Charcoal Waistcoat',
    description: 'Subtle, distinguished, and timeless. The dense houndstooth and glen plaid arrangement gives immense depth while reading as sophisticated grey from a distance.',
    img1: 'CHALK_STRIPE', img2: 'BLACK_SUIT',
    colors: [{ name: 'Charcoal Glen Check', hex: '#353535' }, { name: 'Steel Check', hex: '#484848' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Super 140s Pure Wool (280g/m)',
    fabricOrigin: 'Huddersfield Fine Worsteds, UK',
    fit: 'Classic Formal', occasion: 'Business & Boardroom', collection: 'Signature Collection',
    notes: ['5-button high-V vest with jetted watch pocket', 'Pick stitched lapels', 'Extended waistband tab trousers'],
  },
  {
    name: 'N.K FABRICS Royal Navy Double-Breasted 4x2 Suit',
    price: 3700,
    tagline: 'Modern 4x2 Button Stance in High-Twist Travel Gabardine',
    description: 'A sleeker, lower button stance that elongates the neck and torso. The high-twist gabardine wool repels moisture and recovers completely from packing in luggage.',
    img1: 'NAVY_SUIT', img2: 'BACK_PROFILE',
    colors: [{ name: 'Royal Navy', hex: '#111D30' }, { name: 'Deep Indigo', hex: '#0B1422' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'High-Twist Pure Wool Gabardine (270g/m)',
    fabricOrigin: 'Vitale Barberis Canonico, Biella',
    fit: 'Tailored Regular', occasion: 'Business & Boardroom', collection: 'Business Collection',
    notes: ['Modern 4x2 double-breasted arrangement with sweeping peak lapels', 'Unfinished trouser cuffs for tailored break', 'Natural horn buttons'],
  },
  {
    name: 'N.K FABRICS Tobacco Linen Two-Piece Summer Suit',
    price: 3350,
    tagline: 'Pure Irish Linen in Rich Tobacco Khaki with Patch Pockets',
    description: 'The gentleman’s summer uniform. Heavy Irish linen that acquires noble character with each wear, featuring unlined spalla camicia construction and patch pockets.',
    img1: 'ESSENTIALS_POLO', img2: 'HERO_MODELS',
    colors: [{ name: 'Tobacco Khaki', hex: '#6E553B' }, { name: 'Golden Wheat', hex: '#876D4E' }],
    sizes: ['38R', '40R', '42R', '44R'],
    fabric: '100% Pure Irish Linen (280g/m)',
    fabricOrigin: 'Baird McNutt, Northern Ireland',
    fit: 'Relaxed Drape', occasion: 'Resort & Casual', collection: 'Summer Collection',
    notes: ['Quarter back lining for maximum ventilation', 'Dual patch hip pockets and barchetta breast pocket', 'Double pleat trousers with side adjusters'],
  },
  {
    name: 'N.K FABRICS Forest Green Flannel Three-Piece',
    price: 4100,
    tagline: 'Subtle Forest Green Wool Flannel with High-V Lapelled Waistcoat',
    description: 'A distinguished country-house formal suit. In low indoor light it registers as charcoal; in natural sunlight it reveals an enchanting deep botanical forest emerald hue.',
    img1: 'EMERALD_SILK', img2: 'HERO_MODELS',
    colors: [{ name: 'Deep Forest Green', hex: '#16281D' }, { name: 'Hunter Green', hex: '#0F1E15' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'English Wool Flannel (330g/m)',
    fabricOrigin: 'Fox Brothers, Somerset, UK',
    fit: 'Classic Formal', occasion: 'Winter Collection', collection: 'Winter Collection',
    notes: ['Includes lapelled 6-button waistcoat', 'Real horn buttons with cross stitch', 'Side tab buckle trousers'],
    newArrival: true,
  },
  {
    name: 'N.K FABRICS Sandstone Worsted Two-Piece Suit',
    price: 3450,
    tagline: 'Light Sandstone Merino Twill with Soft Structured Shoulders',
    description: 'Neutral, crisp, and aristocratic. Woven from high-twist merino wool in a warm sandstone tint, pairing effortlessly with crisp white or pale blue formal shirting.',
    img1: 'ESSENTIALS_POLO', img2: 'TRAD_IVORY',
    colors: [{ name: 'Sandstone Beige', hex: '#D2C3B0' }, { name: 'Oatmeal', hex: '#E0D4C3' }],
    sizes: ['38R', '40R', '42R', '44R'],
    fabric: 'Super 130s All-Season Merino Wool (250g/m)',
    fabricOrigin: 'Biella, Italy',
    fit: 'Tailored Regular', occasion: 'Everyday Luxury', collection: 'Essential Collection',
    notes: ['Soft shoulder padding with clean roll', 'Half-lined interior in cupro', 'Flat front tapered trousers'],
  },
  {
    name: 'N.K FABRICS Shadow Windowpane Charcoal Three-Piece',
    price: 3950,
    tagline: 'Charcoal Wool with Ghost Windowpane Grid & Horseshoe Waistcoat',
    description: 'Architectural minimalism. An almost imperceptible shadow grid adds vertical proportion to the gentleman’s stature, completed by a low-scoop horseshoe vest.',
    img1: 'CHALK_STRIPE', img2: 'TROUSER_CHARCOAL',
    colors: [{ name: 'Shadow Windowpane', hex: '#242426' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Super 150s Fine Worsted Wool (270g/m)',
    fabricOrigin: 'Scabal, Huddersfield, England',
    fit: 'Tailored Regular', occasion: 'Business & Boardroom', collection: 'Signature Collection',
    notes: ['Horseshoe 4-button vest', 'Slanted hacking pockets with ticket pocket', 'Side buckle forward pleat trousers'],
  },
  {
    name: 'N.K FABRICS Midnight Tuxedo with Grosgrain Shawl',
    price: 4400,
    tagline: 'Deep Midnight Blue Barathea Wool with Ribbed Grosgrain Lapels',
    description: 'The Savile Row alternative to satin. Ribbed silk grosgrain facing provides a tactile, matte texture that reflects photography flash evenly without shine.',
    img1: 'EVENING_SUIT', img2: 'BLACK_SUIT',
    colors: [{ name: 'Midnight Navy', hex: '#0B1220' }, { name: 'Deep Black', hex: '#090909' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Pure Wool Barathea (290g/m)',
    fabricOrigin: 'Holland & Sherry, Savile Row',
    fit: 'Tailored Regular', occasion: 'Evening Black-Tie', collection: 'Evening Collection',
    notes: ['Grosgrain faced continuous shawl collar', 'Jetted pockets with no flaps', 'Silk grosgrain braided trouser seams'],
    bestSeller: true,
  },
  {
    name: 'N.K FABRICS Cashmere Flannel Anthracite Suit',
    price: 4650,
    tagline: '85% Super 160s Wool, 15% Cashmere with High-V Waistcoat',
    description: 'The height of cold-weather luxury. An ultra-soft flannel weave enriched with Mongolian cashmere, providing sublime insulation and an unbroken fluid silhouette.',
    img1: 'HERO_MODELS', img2: 'FABRIC_DETAIL',
    colors: [{ name: 'Anthracite Flannel', hex: '#262626' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Wool-Cashmere Flannel (330g/m)',
    fabricOrigin: 'Piacenza 1733, Biella, Italy',
    fit: 'Classic Formal', occasion: 'Winter Collection', collection: 'Winter Collection',
    notes: ['Full floating canvas with natural horsehair chest piece', 'Pick-stitched wide peak lapels', 'Hollywood high-rise trousers'],
  },
  {
    name: 'N.K FABRICS Cream Silk-Linen Wedding Three-Piece',
    price: 4500,
    tagline: 'Mulberry Silk, Linen & Wool with Floral Damask Silk Waistcoat',
    description: 'Designed for summer garden weddings and luxury destination ceremonies. An opulent ivory cream weave paired with a custom floral damask silk vest.',
    img1: 'TRAD_IVORY', img2: 'ESSENTIALS_POLO',
    colors: [{ name: 'Ivory Cream', hex: '#FAF5EC' }],
    sizes: ['38R', '40R', '42R', '44R'],
    fabric: '40% Silk, 35% Linen, 25% Wool (240g/m)',
    fabricOrigin: 'Loro Piana, Quarona, Italy',
    fit: 'Tailored Regular', occasion: 'Wedding & Gala', collection: 'Wedding Collection',
    notes: ['Includes matching floral damask silk vest', 'Carved mother-of-pearl buttons with gold shank', 'Double forward pleat trousers'],
    newArrival: true,
  },
  {
    name: 'N.K FABRICS English Herringbone Charcoal Two-Piece',
    price: 3600,
    tagline: 'Textured Fine Herringbone Weave in Super 140s British Wool',
    description: 'Classic British texture with modern lightweight wearability. The fine chevron weave reflects light symmetrically across the chest.',
    img1: 'TROUSER_CHARCOAL', img2: 'HERO_MODELS',
    colors: [{ name: 'Charcoal Herringbone', hex: '#2D2D2D' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Super 140s British Worsted Wool (280g/m)',
    fabricOrigin: 'Huddersfield Fine Worsteds, UK',
    fit: 'Tailored Regular', occasion: 'Business & Boardroom', collection: 'Business Collection',
    notes: ['Milanese lapel buttonhole', 'Two-button single-breasted stance with curved barchetta chest pocket', 'Side buckle tab trousers'],
  },
  {
    name: 'N.K FABRICS Imperial Burgundy Three-Piece Suit',
    price: 4250,
    tagline: 'Deep Wine Super 150s Merino Wool with Tonal Waistcoat',
    description: 'A regal evening and reception ensemble. Deep wine burgundy wool crafted with an immaculate canvas roll, paired with a matching five-button tailored vest.',
    img1: 'EVENING_SUIT', img2: 'HERO_MODELS',
    colors: [{ name: 'Imperial Burgundy', hex: '#3F121C' }, { name: 'Deep Claret', hex: '#2F0B13' }],
    sizes: ['38R', '40R', '42R', '44R'],
    fabric: 'Super 150s Tasmanian Merino Wool (260g/m)',
    fabricOrigin: 'Scabal, England',
    fit: 'Slim Fit', occasion: 'Wedding & Gala', collection: 'Wedding Collection',
    notes: ['Broad 3.75-inch peak lapels', 'Matching 5-button tailored vest', 'Flat front dress trousers with side adjusters'],
    newArrival: true,
  },
  {
    name: 'N.K FABRICS Steel Blue Micro-Check Two-Piece',
    price: 3500,
    tagline: 'Modern Steel Blue Wool with Micro Houndstooth Check',
    description: 'Subtle color dimension for contemporary formal environments. High-twist wool prevents creases while the subtle steel blue hue sets the wearer apart.',
    img1: 'NAVY_SUIT', img2: 'HERO_MODELS',
    colors: [{ name: 'Steel Blue', hex: '#2F4056' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Super 130s High-Twist Wool (250g/m)',
    fabricOrigin: 'Vitale Barberis Canonico, Italy',
    fit: 'Tailored Regular', occasion: 'Business & Boardroom', collection: 'Business Collection',
    notes: ['Neapolitan soft shoulder', 'Flap hip pockets with ticket pocket', 'Single-pleat trousers'],
  },
  {
    name: 'N.K FABRICS Midnight Velvet 3-Piece Black Tie Suit',
    price: 4900,
    tagline: 'Venetian Black Velvet with Double-Breasted Silk Waistcoat',
    description: 'The supreme formal ceremony monument. Heavy Italian velvet with an incomparable luster, complete with a six-button pure silk satin vest and braided trousers.',
    img1: 'BLACK_SUIT', img2: 'EVENING_SUIT',
    colors: [{ name: 'Venetian Black', hex: '#070707' }],
    sizes: ['38R', '40R', '42R', '44R', '46L'],
    fabric: 'Silk-Cotton Velvet & Pure Como Silk (380g/m)',
    fabricOrigin: 'Como & Milan, Italy',
    fit: 'Tailored Regular', occasion: 'Evening Black-Tie', collection: 'Limited Edition',
    notes: ['Includes 6-button silk satin waistcoat', 'Silk grosgrain peak lapels', 'Side braided black-tie trousers'],
    bestSeller: true,
  },
];

console.log(`Generated ${suitDefs.length} suit definitions.`);
