# 22 Unique Kurtas for N.K FABRICS

kurtas = [
    ('kt-sandstone-slub-silk', 'Sandstone Slub Silk Traditional Kurta', 1250,
     'Textured Slub Raw Silk with Single-Needle Pick Stitch',
     'An essential for sophisticated gatherings. Hand-loomed raw silk with natural slub variations gives an unmistakable tactile presence, paired with a mandarin band collar and mother-of-pearl buttons.',
     'HERO_MODELS', 'TRAD_IVORY',
     [{'name': 'Sandstone', 'hex': '#D4C4B0'}, {'name': 'Oatmeal', 'hex': '#E2D8C9'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '100% Pure Raw Mulberry Silk (240g/m)', 'Heritage Mills, Lahore',
     'Tailored Regular', 'Ceremony & Eid', 'Traditional Collection',
     ['Concealed placket with carved mother-of-pearl buttons', 'High side slits with reinforced hand-sewn bar tacks', 'Can be paired with matching trousers or off-white shalwar'],
     False, True),

    ('kt-shadow-black-chikankari', 'Shadow Black Hand-Embroidered Chikankari Kurta', 1450,
     'Tonal Black-on-Black Hand-Embroidered Chikankari on Fine Georgette Cotton',
     'A masterpiece of subtle artisan dexterity. Delicate floral and geometric shadow embroidery hand-stitched by generational artisans onto high-twist black cotton voile.',
     'TRAD_BLACK', 'EVENING_SUIT',
     [{'name': 'Shadow Black', 'hex': '#0A0A0A'}, {'name': 'Charcoal Noir', 'hex': '#1A1A1A'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], 'High-Twist Fine Cotton Voile with Silk Threadwork', 'Heritage Embroidery Guild, Lahore',
     'Classic Formal', 'Wedding & Gala', 'Signature Collection',
     ['Over 80 hours of hand-embroidery per garment', 'Silk satin piping on band collar', 'Concealed snap placket with mother-of-pearl face buttons'],
     True, True),

    ('kt-minimalist-noir-cotton', 'Minimalist Noir Egyptian Poplin Kurta', 950,
     '140s Compact Cotton Poplin with Hidden Placket',
     'Clean, sculptural, and unembellished. A masterclass in minimalist design focusing on sharp shoulder lines, a firm mandarin collar, and a modern straight hem with side vents.',
     'TRAD_BLACK', 'SHIRT_WHITE',
     [{'name': 'Deep Black', 'hex': '#0C0C0C'}, {'name': 'Charcoal', 'hex': '#222222'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], 'Super 140s Compact Egyptian Cotton (160g/m)', 'Thomas Mason, Italy',
     'Slim Fit', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Concealed placket with horn buttons', 'Straight cut modern silhouette with tailored chest taper', 'Side in-seam pockets'],
     False, False),

    ('kt-royal-ivory-giza-pique', 'Royal Ivory Giza Piqué Kurta', 1150,
     'Fine Marcella Waffle Texture with Clean Stand Collar',
     'Borrowing the texture of formal white-tie evening shirts. Crisp Egyptian Marcella piqué waffle fabric delivers a sculptured collar and three-dimensional visual texture.',
     'TRAD_IVORY', 'SHIRT_WHITE',
     [{'name': 'Ivory Piqué', 'hex': '#FDFBF7'}, {'name': 'Alabaster', 'hex': '#F2ECE1'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], 'Giza 45 Egyptian Cotton Marcella Piqué', 'Albini Group, Bergamo, Italy',
     'Tailored Regular', 'Ceremony & Eid', 'Eid Collection',
     ['Stiffened stand collar with double horsehair interlining', 'Genuine Australian mother-of-pearl buttons', 'French cuff slits'],
     True, False),

    ('kt-saffron-silk-ceremonial', 'Imperial Saffron Silk Festival Kurta', 1380,
     'Warm Saffron Raw Silk with Champagne Gold Zari Border',
     'Radiant and sovereign. Spun from warm golden saffron mulberry raw silk, detailed with microscopic gold bullion zari threads woven into the cuffs and neckline.',
     'HERO_MODELS', 'TAG_TEXTURE',
     [{'name': 'Imperial Saffron', 'hex': '#D99B26'}, {'name': 'Deep Ochre', 'hex': '#B87A18'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], 'Hand-Loomed Raw Silk with Zari Metallic Accent (250g/m)', 'Heritage Weavers, Lahore',
     'Classic Formal', 'Ceremony & Eid', 'Traditional Collection',
     ['Micro metallic zari bullion borders on collar and cuffs', 'Pairs elegantly with cream or black trousers', 'Handmade fabric loop buttons'],
     False, False),

    ('kt-slate-blue-bandhgala', 'Slate Blue Bandhgala Short Kurta', 1280,
     'Modern Mid-Thigh Length in High-Twist Wool-Silk Blend',
     'Designed for the modern gentleman who wears traditional tailoring with tailored wool trousers. Features a high structured bandhgala collar with horn buttons.',
     'NAVY_SUIT', 'HERO_MODELS',
     [{'name': 'Slate Blue', 'hex': '#2C3E55'}, {'name': 'Dusty Indigo', 'hex': '#1E2B3C'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '70% Wool, 30% Mulberry Silk (210g/m)', 'Biella & Lahore Artisans',
     'Slim Fit', 'Everyday Luxury', 'Signature Collection',
     ['Mid-thigh length cut specifically for wearing over tailored trousers', 'Dual side tab waist suppression adjusters', 'Chest pocket with silk piping'],
     False, False),

    ('kt-emerald-needlepoint-silk', 'Emerald Green Needlepoint Silk Kurta', 1350,
     'Pure Raw Silk with Intricate Single-Needle Leaf Embroidery',
     'Refined royal greenery. The deep emerald green cloth is accented with delicate tone-on-tone leaf needlepoint along the placket, embodying understated nobility.',
     'EMERALD_SILK', 'TRAD_GREEN',
     [{'name': 'Emerald Green', 'hex': '#0B291E'}, {'name': 'Bottle Green', 'hex': '#071C14'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], 'Dense Raw Silk with Natural Slubs (260g/m)', 'Heritage Silk Guild, Lahore',
     'Classic Formal', 'Ceremony & Eid', 'Wedding Collection',
     ['Tone-on-tone single needle embroidery along chest line', 'Concealed smartphone pocket inside right side seam', 'Horn button closures'],
     True, False),

    ('kt-raw-oatmeal-handloom', 'Raw Oatmeal Handloom Textured Kurta', 1050,
     'Unbleached Organic Cotton-Silk with Natural Texture',
     'Purity of noble raw textiles. Unbleached organic cotton spun together with wild tussar silk for an earthy, textured hand that breathes effortlessly.',
     'ESSENTIALS_POLO', 'TRAD_IVORY',
     [{'name': 'Raw Oatmeal', 'hex': '#D8CEBE'}, {'name': 'Bone Ivory', 'hex': '#EBE5D8'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '70% Hand-Spun Organic Cotton, 30% Wild Tussar Silk', 'Punjab Traditional Looms',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Hand-stitched bone buttons', 'Soft unpadded band collar for maximum ease', 'French seams throughout'],
     False, False),

    ('kt-pearl-white-eid-embroidered', 'Sovereign Pearl White Embroidered Eid Kurta', 1390,
     'Swiss Voile Cotton with Delicate Resham Thread Floral Work',
     'Created for sacred Eid morning prayers and celebratory family banquets. Crisp Swiss voile adorned with subtle ivory resham thread embroidery.',
     'TRAD_IVORY', 'SHIRT_WHITE',
     [{'name': 'Pearl White', 'hex': '#FFFFFF'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '100% Ultra-Fine Swiss Cotton Voile (140g/m)', 'Appenzell, Switzerland & Lahore',
     'Tailored Regular', 'Ceremony & Eid', 'Eid Collection',
     ['Tone-on-tone fine resham thread embroidery on collar and cuffs', 'Australian mother-of-pearl buttons', 'Lightweight and semi-translucent structure'],
     True, True),

    ('kt-midnight-indigo-kashmiri', 'Midnight Indigo Kashmiri Ari-Work Kurta', 1550,
     'Pure Raw Silk with Traditional Kashmiri Needlework on Placket',
     'Regal North-Indian and Kashmiri artistry. Intricate swirling flora hand-stitched with fine silk needles along the neckline and cuffs.',
     'NAVY_SUIT', 'TRAD_BLACK',
     [{'name': 'Midnight Indigo', 'hex': '#121F38'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '100% Hand-Spun Raw Mulberry Silk', 'Srinagar & Lahore Artisans',
     'Classic Formal', 'Wedding & Gala', 'Traditional Collection',
     ['Over 65 hours of ari-needle hand embroidery', 'Mother-of-pearl buttons with hand-twisted silk eyelets'],
     False, False),

    ('kt-sandstone-linen-band-collar', 'Multan Sandstone Pure Linen Short Kurta', 980,
     'Northern Irish Linen Tailored in Contemporary Short Silhouette',
     'Designed for modern daytime gatherings. Heavy pure linen that stays crisp under heat, cut to a modern mid-thigh hemline with deep side pockets.',
     'CASUAL_SHIRT', 'HERO_MODELS',
     [{'name': 'Sandstone Linen', 'hex': '#C8BBA5'}, {'name': 'Natural Beige', 'hex': '#DDD2BD'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '100% Pure Irish Linen (250g/m)', 'Baird McNutt, Ireland',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Mandarin band collar with 1-button neck clasp', 'Dual side pockets with reinforced corners', 'Short tailored length'],
     False, False),

    ('kt-deep-plum-silk-brocade', 'Imperial Plum Silk Brocade Wedding Kurta', 1480,
     'Rich Jewel-Toned Plum Raw Silk with Subtle Paisley Micro-Brocade',
     'An aristocratic evening wedding statement. The deep violet plum shade reflects warmth under chandeliers, framed by gold metallic piped edges.',
     'EVENING_SUIT', 'HERO_MODELS',
     [{'name': 'Imperial Plum', 'hex': '#3A142D'}, {'name': 'Royal Violet', 'hex': '#280D1F'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '100% Pure Mulberry Silk Brocade (260g/m)', 'Heritage Weavers, Lahore',
     'Slim Fit', 'Wedding & Gala', 'Wedding Collection',
     ['Gold bullion metallic edge piping on collar', 'Carved horn buttons with gold loop fasteners'],
     True, False),

    ('kt-ivory-matka-gold-button', 'Sovereign Ivory Matka Silk Kurta', 1290,
     'Heavy Matka Silk with 18K Gold PVD Gilded Monogram Buttons',
     'Substantial, statuesque raw silk that holds an immaculate vertical column drape. Accented with solid brass buttons gilded in 18K champagne gold.',
     'TRAD_IVORY', 'TAG_TEXTURE',
     [{'name': 'Ivory Matka', 'hex': '#FBF7ED'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], 'Heavyweight Matka Raw Silk (290g/m)', 'Lahore Master Looms',
     'Classic Formal', 'Ceremony & Eid', 'Signature Collection',
     ['Custom 18K gold-plated N.K monogram crest buttons', 'Structured collar with double horsehair interlining', 'Tailored French cuffs'],
     False, True),

    ('kt-charcoal-geometric-jacquard', 'Charcoal Geometric Silk-Cotton Kurta', 1190,
     'Tone-on-Tone Jacquard Diamond Weave with Structured Collar',
     'Modern dark sophistication. Woven on precision jacquard looms to create a subtle geometric diamond relief in deep charcoal grey.',
     'TRAD_BLACK', 'TROUSER_CHARCOAL',
     [{'name': 'Charcoal Jacquard', 'hex': '#262628'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '60% Mulberry Silk, 40% Egyptian Cotton (220g/m)', 'Como & Lahore',
     'Tailored Regular', 'Formal Collection', 'Formal Collection',
     ['Concealed snap placket with mother-of-pearl face buttons', 'Structured band collar'],
     False, False),

    ('kt-sky-blue-egyptian-cotton', 'Sky Blue Giza 87 Egyptian Cotton Kurta', 920,
     'Silky-Smooth 200/2 Egyptian Cotton with Single-Needle Seams',
     'Unmatched daytime comfort. Egyptian cotton that glides coolly against the skin, finished with an elegant straight hem and French cuff slits.',
     'SHIRT_WHITE', 'HERO_MODELS',
     [{'name': 'Sky Blue', 'hex': '#D4E4F2'}, {'name': 'Glacier Blue', 'hex': '#E5EFF7'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '100% Giza 87 Egyptian Cotton (Silk Finish)', 'Thomas Mason, Italy',
     'Tailored Regular', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Mandarin collar with 1mm edge stitching', 'Mother-of-pearl buttons', 'Deep in-seam pockets'],
     False, False),

    ('kt-olive-raw-silk-festive', 'Forest Olive Raw Silk Festive Kurta', 1320,
     'Heavy Slub Raw Mulberry Silk in Deep Forest Olive',
     'Earthy South Asian grandeur. The natural slub variations of hand-spun raw silk are highlighted by subtle tonal needlepoint on the placket.',
     'EMERALD_SILK', 'HERO_MODELS',
     [{'name': 'Forest Olive', 'hex': '#233826'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '100% Raw Mulberry Silk (Heavy Drape)', 'Lahore Silk Guild',
     'Classic Formal', 'Ceremony & Eid', 'Traditional Collection',
     ['Tonal needlepoint detailing on neckline', 'Carved dark buffalo horn buttons'],
     False, False),

    ('kt-gold-tissue-silk-wedding', 'Champagne Gold Tissue Silk Wedding Kurta', 1590,
     'Lustrous Metallic Tissue Silk with Zari Bullion Neckline',
     'Designed specifically for wedding banquets and groomsmen ceremonies. An opulent champagne gold sheen that glimmers radiantly.',
     'TRAD_IVORY', 'PRINCE_COAT',
     [{'name': 'Champagne Gold', 'hex': '#E2D1AB'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], 'Silk & Lurex Tissue Weave (230g/m)', 'Varanasi Master Looms',
     'Classic Formal', 'Wedding & Gala', 'Wedding Collection',
     ['Zari bullion hand-embroidery on mandarin collar', 'Concealed magnetic placket with crystal buttons'],
     True, False),

    ('kt-steel-grey-compact-twill', 'Steel Grey Compact Twill Formal Kurta', 960,
     'Wrinkle-Resistant Fine Diagonal Cotton Twill',
     'Business and daytime formal readiness. Diagonal twill that resists creases throughout long banquets, paired with a firm stand collar.',
     'HERO_MODELS', 'TROUSER_CHARCOAL',
     [{'name': 'Steel Grey', 'hex': '#3C4048'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '100% Long-Staple Egyptian Cotton Twill', 'Albini Group, Italy',
     'Tailored Regular', 'Formal Collection', 'Formal Collection',
     ['Firm stand collar with double interlining', 'Hidden placket with real horn buttons'],
     False, False),

    ('kt-terracotta-raw-silk', 'Terracotta Raw Silk Ceremonial Kurta', 1340,
     'Warm Terracotta Rust Raw Silk with Gold Piping Accents',
     'A vibrant autumnal festive creation. Hand-spun raw silk in rich terracotta rust, accented with subtle gold thread piping along the placket.',
     'HERO_MODELS', 'TAG_TEXTURE',
     [{'name': 'Terracotta Rust', 'hex': '#9E4733'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '100% Pure Raw Mulberry Silk (260g/m)', 'Heritage Mills, Lahore',
     'Tailored Regular', 'Ceremony & Eid', 'Traditional Collection',
     ['Gold thread piping along collar and cuffs', 'Handmade horn button fasteners'],
     False, False),

    ('kt-black-velvet-collar-kurta', 'Imperial Noir Kurta with Silk-Velvet Collar', 1280,
     'Super 140s Cotton Poplin with Venetian Velvet Stand Collar',
     'Subtle contrast of textures. Crisp, high-count black cotton poplin adorned with an opulent Italian silk-cotton velvet mandarin stand collar.',
     'TRAD_BLACK', 'EVENING_SUIT',
     [{'name': 'Black on Black Velvet', 'hex': '#080808'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '140s Egyptian Cotton with Italian Silk Velvet Collar', 'Albini & Pontoglio, Italy',
     'Slim Fit', 'Evening Black-Tie', 'Signature Collection',
     ['Venetian black velvet mandarin stand collar', 'Dark smoked mother-of-pearl buttons', 'French cuff slits'],
     True, False),

    ('kt-powder-pink-chanderi-silk', 'Powder Pink Chanderi Silk Festive Kurta', 1420,
     'Lightweight Chanderi Silk with Sheer Luster & Zari Booti',
     'Ethereal springtime celebratory elegance. Pure Chanderi silk with miniature gold zari booti motifs woven into the ground.',
     'TRAD_IVORY', 'HERO_MODELS',
     [{'name': 'Powder Pink', 'hex': '#EAD4D8'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], 'Pure Chanderi Silk with Fine Zari Motif (180g/m)', 'Heritage Guild, Lahore',
     'Tailored Regular', 'Wedding & Gala', 'Wedding Collection',
     ['Hand-loomed gold zari booti motifs throughout', 'Mother-of-pearl buttons with pink thread loops'],
     False, False),

    ('kt-navy-raw-silk-formal', 'Midnight Navy Raw Mulberry Silk Kurta', 1290,
     'Dense Hand-Loomed Navy Raw Silk with Mother-of-Pearl Buttons',
     'Classic South Asian evening nobility. Rich midnight navy raw silk that drapes cleanly, paired with a firm collar and side seam pockets.',
     'NAVY_SUIT', 'TRAD_BLACK',
     [{'name': 'Midnight Navy', 'hex': '#101A2C'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '100% Hand-Spun Raw Mulberry Silk (260g/m)', 'Heritage Weavers, Lahore',
     'Tailored Regular', 'Ceremony & Eid', 'Traditional Collection',
     ['Genuine Australian mother-of-pearl buttons', 'Mandarin stand collar with pick stitching', 'French seams throughout'],
     False, True),
]

print(f"Kurtas configured: {len(kurtas)}")
