# 26 Unique Trousers & Pants for N.K FABRICS

trousers = [
    ('tr-english-flannel-charcoal', 'English Flannel Pleated Dress Trousers', 780,
     'High-Rise Double Forward Pleats with Brass Side Tab Buckles',
     'Crafted without belt loops for a clean unbroken line. Dual brass side-adjuster buckles allow micro-fit refinement while forward pleats ensure absolute ease when seated.',
     'TROUSER_CHARCOAL', 'HERO_MODELS',
     [{'name': 'Charcoal', 'hex': '#2B2B2B'}, {'name': 'Deep Black', 'hex': '#0C0C0C'}],
     ['30', '32', '34', '36', '38', '40'], '100% English Worsted Wool Flannel (310g/m)', 'Fox Brothers & Co., Somerset, UK',
     'Classic Formal', 'Business & Boardroom', 'Signature Collection',
     ['High-rise waistline sitting naturally at the naval', 'Interior waistband curtain with rubberized shirt gripper tape', '2-inch turn-up cuffs with hand-blindstitched hems'],
     False, True),

    ('tr-gurkha-buckle-olive', 'Savile Row Gurkha Trousers (Olive)', 850,
     'Cross-Over Cinch Belted Waistband in High-Twist Wool Gabardine',
     'The definitive Gurkha silhouette. Features the iconic overlapping self-belt with dual brass buckles, forward deep pleats, and a relaxed taper down to a clean cuff.',
     'TROUSER_CHARCOAL', 'ESSENTIALS_POLO',
     [{'name': 'Military Olive', 'hex': '#3B4234'}, {'name': 'Tobacco Khaki', 'hex': '#7A6245'}],
     ['30', '32', '34', '36', '38'], 'High-Twist Wool Gabardine (280g/m)', 'Vitale Barberis Canonico, Biella',
     'Tailored Regular', 'Everyday Luxury', 'Signature Collection',
     ['Iconic Gurkha overlapping waist cinch with solid brass buckles', 'Dual forward pleats with high rise', 'Fishtail rear waist notch'],
     True, False),

    ('tr-black-tuxedo-silk-braid', 'Silk-Satin Braided Tuxedo Trousers', 920,
     'Midnight Black Barathea Wool with 20mm Silk Satin Side Braid',
     'Strict black-tie formal trousers. Cut with no belt loops and flat front, featuring a 20mm Como silk satin stripe down each outseam and hidden side tab buckles.',
     'BLACK_SUIT', 'TROUSER_CHARCOAL',
     [{'name': 'Midnight Black', 'hex': '#0B0B0B'}],
     ['30', '32', '34', '36', '38', '40'], 'Pure Wool Barathea with Silk Satin Trim (290g/m)', 'Dormeuil, UK & France',
     'Classic Formal', 'Evening Black-Tie', 'Evening Collection',
     ['Continuous 20mm silk satin side braid along both legs', 'Suspender buttons installed inside the curtain waistband', 'Unfinished bottoms for custom tailoring'],
     False, True),

    ('tr-cream-tropical-worsted', 'Cream Tropical Worsted High-Waist Trousers', 820,
     'High-Ventilation Open Weave with Hollywood High-Waistband',
     'Warm-weather perfection. Woven with high-twist yarns that encourage airflow while sustaining a crisp center crease from morning to evening.',
     'ESSENTIALS_POLO', 'TRAD_IVORY',
     [{'name': 'Cream', 'hex': '#ECE7DD'}, {'name': 'Sand Beige', 'hex': '#DED7C8'}],
     ['30', '32', '34', '36', '38'], 'Tropical Worsted Wool (220g/m)', 'Holland & Sherry, Savile Row',
     'Classic Formal', 'Wedding & Gala', 'Wedding Collection',
     ['Double forward pleats with generous leg drape', 'Lined to the knee in pure breathable cupro', '2-inch turn-up cuffs'],
     False, False),

    ('tr-navy-travel-gabardine', 'Midnight Navy High-Twist Gabardine Trousers', 750,
     'Water-Repellent Merino Gabardine with Single Pleat',
     'The workhorse of the traveling gentleman. Densely woven wool gabardine that naturally sheds moisture and wrinkles, tailored with side tab adjusters.',
     'NAVY_SUIT', 'TROUSER_CHARCOAL',
     [{'name': 'Midnight Navy', 'hex': '#121A2A'}, {'name': 'Ink Blue', 'hex': '#0E1724'}],
     ['30', '32', '34', '36', '38', '40'], 'Super 130s Wool Gabardine (270g/m)', 'Vitale Barberis Canonico, Biella',
     'Tailored Regular', 'Business & Boardroom', 'Business Collection',
     ['Single forward pleat with gentle taper to hem', 'Slanted front coin pocket', 'Horn button closures'],
     False, False),

    ('tr-sand-irish-linen-pleat', 'Mediterranean Sand Irish Linen Trousers', 740,
     'Pure Irish Linen with Dual Forward Pleats & Side Buckles',
     'The ultimate holiday trouser. Heavyweight Irish linen that drapes fluidly without becoming flimsy, finished with a 2-inch cuff that anchors the hem.',
     'ESSENTIALS_POLO', 'HERO_MODELS',
     [{'name': 'Sand Beige', 'hex': '#D6CBB8'}, {'name': 'Off-White', 'hex': '#F0ECE1'}],
     ['30', '32', '34', '36', '38'], '100% Pure Irish Linen (260g/m)', 'Baird McNutt, Northern Ireland',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Side tab brass adjusters replacing belt loops', '2-inch turn-up cuffs with hand-blindstitching', 'Half-lined in soft cotton'],
     True, False),

    ('tr-houndstooth-dress-trouser', 'English Houndstooth Dress Trousers', 790,
     'Micro Black & White Houndstooth Wool with High Rise',
     'A sartorial staple that pairs with jackets, black suits, or cashmere knitwear. Woven in a micro puppytooth scale that reads as textured grey from afar.',
     'TROUSER_CHARCOAL', 'HERO_MODELS',
     [{'name': 'Black & White Houndstooth', 'hex': '#3E3E3E'}],
     ['30', '32', '34', '36', '38'], 'Super 140s Pure Wool (280g/m)', 'Fox Brothers & Co., UK',
     'Classic Formal', 'Business & Boardroom', 'Signature Collection',
     ['High rise with extended waistband tab and corozo button', 'Double forward pleats', 'Side buckle tab adjusters'],
     False, False),

    ('tr-tobacco-cotton-twill-chino', 'Sartorial Officer Cotton Chino (Tobacco)', 580,
     'Heavy 10oz Italian Cotton Twill with Extended Waist Tab',
     'An elevated casual essential. Military-grade heavy cotton twill tailored with sartorial discipline, featuring side adjusters, coin pocket, and clean flat front.',
     'TROUSER_CHARCOAL', 'ESSENTIALS_POLO',
     [{'name': 'Tobacco Khaki', 'hex': '#735B42'}, {'name': 'Stone Beige', 'hex': '#C2B6A3'}],
     ['30', '32', '34', '36', '38', '40'], '100% Heavy Italian Cotton Twill (10oz)', 'Albiate 1830, Italy',
     'Tailored Regular', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Extended waistband tab with hidden button', 'Pick stitching along side seams', 'Clean straight leg taper'],
     False, True),

    ('tr-dark-navy-flat-front-suit', 'Mayfair Flat-Front Navy Dress Trousers', 720,
     'Super 150s Worsted Wool with Belt Loops & Slanted Pockets',
     'Clean, modern, and uncluttered. Tailored flat-front silhouette designed for gentlemen who prefer wearing leather dress belts with business attire.',
     'NAVY_SUIT', 'TROUSER_CHARCOAL',
     [{'name': 'Dark Navy', 'hex': '#101B2E'}],
     ['30', '32', '34', '36', '38', '40'], 'Super 150s Pure Merino Wool (250g/m)', 'Loro Piana, Italy',
     'Slim Fit', 'Business & Boardroom', 'Business Collection',
     ['Belt loops engineered for 30mm dress belts', 'Slanted side pockets with bartack reinforcement', 'Clean plain bottom hem'],
     False, False),

    ('tr-chocolate-brown-wool-trouser', 'Chocolate Brown High-Twist Wool Trousers', 760,
     'Deep Bitter Chocolate 4-Ply Wool with Single Reverse Pleat',
     'A rich, warm tone for boardroom elegance. Heavy 4-ply high-twist wool resists wrinkles and hangs like an iron column.',
     'TROUSER_CHARCOAL', 'HERO_MODELS',
     [{'name': 'Bitter Chocolate', 'hex': '#2D1F18'}, {'name': 'Espresso', 'hex': '#21150F'}],
     ['30', '32', '34', '36', '38'], '4-Ply High-Twist Wool Fresco (340g/m)', 'Smith Woollens, London',
     'Classic Formal', 'Winter Collection', 'Winter Collection',
     ['Single reverse pleat', 'Fishtail back notch for button suspenders', '2-inch turn-up cuffs'],
     False, False),

    ('tr-white-denim-sartorial', 'Selvedge White Denim Sartorial Trousers', 620,
     '12oz Japanese White Selvedge Denim Tailored with Slanted Pockets',
     'Where luxury tailoring meets raw denim. Cut with trousers-style slanted pockets and a high rise rather than traditional 5-pocket jean styling.',
     'CASUAL_SHIRT', 'ESSENTIALS_POLO',
     [{'name': 'Chalk White', 'hex': '#FAF8F5'}],
     ['30', '32', '34', '36', '38'], '100% Japanese Selvedge Cotton Denim (12oz)', 'Kojima, Japan',
     'Tailored Regular', 'Resort & Casual', 'Summer Collection',
     ['Slanted dress trousers pockets', 'Internal selvedge outseam visible when cuffed', 'Corozo nut buttons'],
     True, False),

    ('tr-chalk-stripe-pleated-navy', 'Savile Row Chalk Stripe Flannel Trousers', 840,
     'Heavy English Worsted Navy Flannel with Natural Chalk Pinstripe',
     'Matching the iconic three-piece suit or worn as a standalone statement with knitwear. Double forward pleats and brass side adjusters.',
     'CHALK_STRIPE', 'NAVY_SUIT',
     [{'name': 'Navy Chalk Stripe', 'hex': '#152238'}],
     ['30', '32', '34', '36', '38', '40'], 'English Worsted Flannel (320g/m)', 'Fox Brothers, Somerset, UK',
     'Classic Formal', 'Business & Boardroom', 'Signature Collection',
     ['Side tab brass buckles', 'Fishtail rear back waistband with suspender buttons', '2-inch turn-up cuffs'],
     False, False),

    ('tr-light-grey-sharkskin-trouser', 'Light Grey Sharkskin Executive Trousers', 740,
     'Super 150s Sharkskin Wool with Silvery Metallic Luster',
     'The ultimate formal coordinate. Crisp center creases remain sharp throughout international travel thanks to the resilient two-tone twill weave.',
     'HERO_MODELS', 'TROUSER_CHARCOAL',
     [{'name': 'Light Grey Sharkskin', 'hex': '#9AA0AC'}],
     ['30', '32', '34', '36', '38', '40'], 'Super 150s Merino Wool Sharkskin', 'Loro Piana, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Business Collection',
     ['Extended waistband tab with hidden horn button', 'Single pleat front with tapered leg'],
     False, False),

    ('tr-bordeaux-wool-silk-gala', 'Bordeaux Wool-Silk Evening Dress Trousers', 890,
     'Deep Wine Wool-Silk with 10mm Satin Waistband & Side Trim',
     'Rich and nocturnal. Tailored with a silk satin waistband and outseam trim, designed to anchor velvet dinner jackets and silk evening shirts.',
     'EVENING_SUIT', 'BLACK_SUIT',
     [{'name': 'Bordeaux Wine', 'hex': '#44101A'}],
     ['30', '32', '34', '36', '38'], '75% Wool, 25% Silk (260g/m)', 'Dormeuil, France & UK',
     'Slim Fit', 'Evening Black-Tie', 'Evening Collection',
     ['Satin-faced waistband', '10mm satin outseam piping', 'Jetted rear pockets without buttons'],
     True, False),

    ('tr-olive-wool-flannel-trouser', 'Forest Olive Heavy Flannel Trousers', 790,
     'English Wool Flannel with Forward Pleats & Cinch Buckles',
     'A sophisticated country-house trouser. Deep moss olive green that pairs naturally with camel coats, navy knitwear, and brown leather shoes.',
     'EMERALD_SILK', 'TROUSER_CHARCOAL',
     [{'name': 'Forest Olive', 'hex': '#2E3D2A'}],
     ['30', '32', '34', '36', '38'], 'Pure Wool Flannel (330g/m)', 'Fox Brothers, UK',
     'Classic Formal', 'Winter Collection', 'Winter Collection',
     ['Double forward pleats', 'Side brass adjusters', '2-inch cuffs'],
     False, False),

    ('tr-drawstring-linen-resort', 'Riviera Silk-Linen Drawstring Trousers', 690,
     'Elasticated Back with Flat Front & Internal Drawstring',
     'Pure holiday sprezzatura. The comfort of an elasticated waistband concealed behind a tailored flat front with an interior silk drawstring.',
     'CASUAL_SHIRT', 'ESSENTIALS_POLO',
     [{'name': 'Natural Sandstone', 'hex': '#C7B9A3'}, {'name': 'Midnight Navy', 'hex': '#141E30'}],
     ['S (30-31)', 'M (32-33)', 'L (34-35)', 'XL (36-38)'], '55% Irish Linen, 45% Silk (220g/m)', 'Baird McNutt, Ireland',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Concealed internal braided drawstring', 'Quarter-top side pockets', 'Relaxed leg with gentle taper'],
     False, True),

    ('tr-anthracite-cashmere-flannel', 'Anthracite Cashmere-Wool Dress Trousers', 950,
     '85% Super 160s Wool, 15% Mongolian Cashmere Flannel',
     'Peak cold-weather luxury. Unimaginable handfeel and insulation, cut with a high rise and forward pleats for effortless drape.',
     'HERO_MODELS', 'FABRIC_DETAIL',
     [{'name': 'Anthracite Grey', 'hex': '#252525'}],
     ['30', '32', '34', '36', '38', '40'], 'Wool-Cashmere Flannel (320g/m)', 'Piacenza 1733, Italy',
     'Classic Formal', 'Winter Collection', 'Winter Collection',
     ['Hollywood high-rise waistband', 'Lined with pure cupro to the knee', 'Fishtail back with suspender buttons'],
     False, False),

    ('tr-black-poplin-summer-trouser', 'Black Tropical High-Twist Wool Trousers', 710,
     'Open-Weave High-Twist Tropical Wool in Solid Pitch Black',
     'A black formal trouser engineered for sweltering heat. The high-twist porous weave permits breeze while remaining pitch black under bright sun.',
     'BLACK_SUIT', 'TROUSER_CHARCOAL',
     [{'name': 'Pitch Black', 'hex': '#0A0A0A'}],
     ['30', '32', '34', '36', '38'], 'Tropical High-Twist Wool (210g/m)', 'Vitale Barberis Canonico, Italy',
     'Slim Fit', 'Everyday Luxury', 'Summer Collection',
     ['Flat front with clean lines', 'Side tab buckles', 'Plain bottom hem'],
     False, False),

    ('tr-sandstone-linen-suit-trouser', 'Sandstone Irish Linen Suit Trousers', 730,
     'Pure Heavy Linen with 2-Inch Turn-Up Cuffs & High Rise',
     'Tailored to match N.K FABRICS summer jackets or worn alone with dress shirts. Features an extended waist tab with hidden hook closure.',
     'ESSENTIALS_POLO', 'TRAD_IVORY',
     [{'name': 'Sandstone Taupe', 'hex': '#D1C4B0'}],
     ['30', '32', '34', '36', '38'], '100% Pure Irish Linen (270g/m)', 'Baird McNutt, Ireland',
     'Tailored Regular', 'Wedding & Gala', 'Summer Collection',
     ['Extended waistband tab with hidden slide hook', '2-inch turn-up cuffs', 'Pick-stitched fly seam'],
     False, False),

    ('tr-charcoal-puppytooth-wool', 'Charcoal Puppytooth High-Rise Trousers', 780,
     'Micro Checkered Wool Twill with Double Forward Pleats',
     'The quintessential Savile Row pattern. Reads as a textured solid grey, offering visual richness under navy, black, and camel jackets.',
     'TROUSER_CHARCOAL', 'HERO_MODELS',
     [{'name': 'Charcoal Puppytooth', 'hex': '#363636'}],
     ['30', '32', '34', '36', '38'], 'Super 140s Pure Wool (290g/m)', 'Huddersfield Fine Worsteds, UK',
     'Classic Formal', 'Business & Boardroom', 'Signature Collection',
     ['Deep forward pleats that open gently when seated', 'Side tab brass adjusters', '2-inch cuffs'],
     False, False),

    ('tr-ivory-wool-silk-ceremony', 'Ivory Wool-Silk Ceremony Dress Trousers', 880,
     'Lustrous Wool & Mulberry Silk Barathea in Pure Ivory',
     'Created for grand daytime receptions and milestone wedding banquets. Impossibly clean drape with zero translucency.',
     'TRAD_IVORY', 'ESSENTIALS_POLO',
     [{'name': 'Pure Ivory', 'hex': '#FDFBF5'}],
     ['30', '32', '34', '36', '38'], 'Super 150s Wool & Silk Barathea (260g/m)', 'Holland & Sherry, Savile Row',
     'Tailored Regular', 'Wedding & Gala', 'Wedding Collection',
     ['Full cupro lining preventing transparency', 'Double pleats with side tab adjusters', 'Turn-up cuffs'],
     True, False),

    ('tr-navy-cotton-garment-dyed', 'Navy Garment-Dyed Cotton Chino Pants', 560,
     'Italian Stretch Cotton Twill Garment-Dyed for Soft Lived-In Color',
     'The ultimate smart casual trouser. 98% cotton with 2% elastane for unrestricted mobility during weekend travel, tailored with trousers-grade finish.',
     'NAVY_SUIT', 'TROUSER_CHARCOAL',
     [{'name': 'Washed Navy', 'hex': '#1B2A3E'}, {'name': 'Dark Ink', 'hex': '#121D2C'}],
     ['30', '32', '34', '36', '38', '40'], '98% Cotton, 2% Elastane Twill (290g/m)', 'Albiate, Italy',
     'Slim Fit', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Garment-dyed in Milan for subtle seam fading', 'Split back waistband for tailor alteration', 'Horn buttons'],
     False, False),

    ('tr-khaki-gurkha-linen', 'Mediterranean Khaki Gurkha Linen Trousers', 780,
     'Heavy Irish Linen with Iconic Cross-Over Gurkha Buckles',
     'Military history meets summer aristocracy. The overlapping self-belt creates an eye-catching waistline when worn with tucked linen shirts or polos.',
     'CASUAL_SHIRT', 'HERO_MODELS',
     [{'name': 'Khaki Tan', 'hex': '#8C775E'}],
     ['30', '32', '34', '36', '38'], '100% Pure Irish Linen (280g/m)', 'Baird McNutt, Ireland',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Cross-over Gurkha waistband with double brass buckles', 'Forward pleats', '2-inch cuffs'],
     True, False),

    ('tr-grey-hopsack-travel-trouser', 'Anthracite Wool Hopsack Travel Trousers', 720,
     'High-Ventilation Open Hopsack Weave with Natural Stretch',
     'The most resilient travel trouser in existence. Wrinkles disappear within 15 minutes of hanging, making it indispensable for global itineraries.',
     'TROUSER_CHARCOAL', 'NAVY_SUIT',
     [{'name': 'Anthracite Hopsack', 'hex': '#333333'}],
     ['30', '32', '34', '36', '38', '40'], 'High-Twist Wool Hopsack (280g/m)', 'Vitale Barberis Canonico, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Business Collection',
     ['Single pleat front with belt loops', 'Internal curtain waistband with shirt grip'],
     False, False),

    ('tr-shadow-check-black-dress', 'Midnight Shadow Check Formal Trousers', 810,
     'Super 150s Black Wool with Tone-on-Tone Windowpane Relief',
     'An architectural dark trouser with three-dimensional depth. Subtle tonally woven grid that catches light during movement.',
     'BLACK_SUIT', 'TROUSER_CHARCOAL',
     [{'name': 'Midnight Shadow Check', 'hex': '#141416'}],
     ['30', '32', '34', '36', '38'], 'Super 150s Worsted Wool (260g/m)', 'Scabal, Huddersfield, England',
     'Slim Fit', 'Formal Collection', 'Formal Collection',
     ['Side tab adjusters without belt loops', 'Flat front with sharp crease', 'Hand-stitched hems'],
     False, False),

    ('tr-raw-denim-sartorial-trouser', '13oz Japanese Selvedge Denim Dress Trousers', 650,
     'Raw Indigo Selvedge Denim Cut in High-Rise Double-Pleat Tailoring',
     'Denim elevated to haute couture. Hand-tailored like a bespoke wool trouser with forward pleats, side brass adjusters, and turn-up cuffs showing the red selvedge ID line.',
     'NAVY_SUIT', 'CASUAL_SHIRT',
     [{'name': 'Raw Deep Indigo', 'hex': '#101C30'}],
     ['30', '32', '34', '36', '38'], '100% Japanese Selvedge Cotton Denim (13oz)', 'Kurabo Mills, Okayama, Japan',
     'Tailored Regular', 'Everyday Luxury', 'Signature Collection',
     ['Double forward pleats', 'Red selvedge ticker visible on 2-inch turn-up cuffs', 'Brass side adjusters'],
     True, True),
]

print(f"Trousers configured: {len(trousers)}")
