# 22 Unique Luxury Accessories for N.K FABRICS

accessories = [
    ('acc-champagne-gold-cufflinks', '18K Champagne Gold Atelier Cufflinks', 520,
     'Solid Brass with 18K Champagne Gold PVD Satin Coating',
     'Micro-engraved with the sovereign N.K monogram and atelier seal. Features a smooth whale-tail toggle mechanism engineered for French cuff shirts.',
     'TAG_TEXTURE', 'PACKAGING',
     [{'name': 'Champagne Gold', 'hex': '#C8A97E'}, {'name': 'Sterling Silver', 'hex': '#E2E2E2'}],
     ['One Size (16mm diameter)'], 'Jewelry Grade Brass with 18K PVD Satin Gilding', 'Arezzo Gold Atelier, Italy',
     'Classic Formal', 'Business & Boardroom', 'Signature Collection',
     ['Engraved with N.K FABRICS atelier circular seal', 'Packaged in bespoke velvet presentation box', 'Whale-tail toggle mechanism'],
     False, True),

    ('acc-silk-tie-midnight-navy', '7-Fold Mulberry Silk Tie (Midnight Navy)', 360,
     'Untipped Hand-Rolled 7-Fold Pure Silk Twill',
     'The zenith of haberdashery neckwear. Made from a single generous square of heavyweight Como silk, folded onto itself seven times without synthetic interlining.',
     'BLACK_SUIT', 'NAVY_SUIT',
     [{'name': 'Midnight Navy', 'hex': '#121A2A'}, {'name': 'Deep Black', 'hex': '#0C0C0C'}],
     ['8.5cm Width × 150cm Length'], '100% Heavyweight Como Silk Twill (36oz)', 'Como, Italy',
     'Classic Formal', 'Business & Boardroom', 'Signature Collection',
     ['Pure 7-fold construction without synthetic canvas', 'Hand-rolled edges with self-fabric keeper loop', 'Pure Como silk'],
     False, True),

    ('acc-french-boxcalf-belt', 'Full-Grain French Calfskin Dress Belt (Black)', 450,
     '30mm Feathered Edge French Boxcalf with Solid Brass Buckle',
     'Hand-burnished feathered edge belt cut from French boxcalf leather, lined with soft nubuck and secured by a solid brass buckle plated in satin champagne palladium.',
     'TAG_TEXTURE', 'BLACK_SUIT',
     [{'name': 'Nero Black', 'hex': '#0C0C0C'}, {'name': 'Espresso Brown', 'hex': '#2A1C16'}],
     ['32', '34', '36', '38', '40'], 'Full-Grain French Boxcalf Leather', 'Tanneries d’Annonay, France',
     'Classic Formal', 'Business & Boardroom', 'Signature Collection',
     ['Solid brass buckle with satin palladium finish', 'Five teardrop adjustment holes with beveled edges', 'Nubuck leather interior lining'],
     False, True),

    ('acc-pocket-square-trio', 'Silk Pocket Square Trio (Hand-Rolled)', 340,
     'Set of Three Hand-Rolled Mulberry Silk Pocket Squares',
     'Includes Champagne Gold Monogram, Sovereign White Hand-Piped, and Midnight Paisley squares. Each hem is rolled by hand with 4 stitches per centimeter.',
     'FABRIC_DETAIL', 'PACKAGING',
     [{'name': 'Gold / White / Midnight', 'hex': '#C8A97E'}],
     ['42cm × 42cm (Classic Large Flare)'], '100% Como Silk Twill (14 Momme)', 'Como, Italy',
     'Classic Formal', 'Wedding & Gala', 'Signature Collection',
     ['Hand-rolled contrasting edges that flare with sculptural volume', 'Presented in rigid embossed gold presentation box'],
     True, False),

    ('acc-reversible-cashmere-scarf', 'Reversible Double-Face Cashmere Scarf', 680,
     'Two-Tone Charcoal & Camel Pure Mongolian Cashmere with Fringed Hem',
     'Finished with a natural teasel ripple water-finish that gives an iridescent wave across the surface. Reversible two-tone charcoal and camel weave.',
     'HERO_MODELS', 'PACKAGING',
     [{'name': 'Charcoal & Camel', 'hex': '#3A3A3A'}, {'name': 'Navy & Grey', 'hex': '#162238'}],
     ['45cm × 190cm'], '100% Pure Mongolian Cashmere with Teasel Finish', 'Johnstons of Elgin, Scotland',
     'Tailored Regular', 'Winter Collection', 'Winter Collection',
     ['Natural dried teasel thistle brushed ripple finish', 'Hand-twisted fringe ends', 'Reversible double-face design'],
     False, True),

    ('acc-solid-brass-collar-stays', 'Engraved Solid Brass Collar Stays (Trio Set)', 180,
     'Solid Heavyweight Brass with Laser-Etched N.K Monogram',
     'Set of three pairs (2.25", 2.5", and 2.75") of substantial solid brass stays that give dress shirt collars an unyielding, crisp roll under jacket lapels.',
     'TAG_TEXTURE', 'SHIRT_WHITE',
     [{'name': 'Champagne Brass', 'hex': '#C8A97E'}],
     ['Three Pairs: 2.25", 2.5", 2.75"'], 'Heavyweight Solid Brass (3mm Thickness)', 'Birmingham Jewellery Quarter, UK',
     'Classic Formal', 'Business & Boardroom', 'Signature Collection',
     ['Includes saddle leather protective travel sheath', 'Laser-etched with N.K FABRICS Savile Row crest'],
     False, False),

    ('acc-grenadine-tie-burgundy', 'Grenadine Grossa Silk Tie (Burgundy)', 380,
     'Hand-Woven Italian Silk Grenadine on Historical Wooden Looms',
     'The ultimate textured neckwear favored by bespoke gentlemen. The porous honeycomb grenadine grossa weave anchors collar points with tactile gravitas.',
     'EVENING_SUIT', 'NAVY_SUIT',
     [{'name': 'Bordeaux Burgundy', 'hex': '#4A111E'}, {'name': 'Forest Green', 'hex': '#142E1F'}],
     ['8.5cm Width × 150cm Length'], '100% Pure Italian Grenadine Grossa Silk', 'Fermo Fossati, Como, Italy',
     'Classic Formal', 'Business & Boardroom', 'Signature Collection',
     ['Woven on 19th-century wooden shuttle looms in Como', 'Untipped hand-rolled edges with wool interlining'],
     False, False),

    ('acc-black-onyx-formal-studs', 'Black Onyx & 18K Gold Tuxedo Stud Set', 480,
     'Natural Black Onyx Gemstones in 18K Gold-Plated Mountings',
     'Strict black-tie evening essentials. Includes four shirt front studs and matching swivel cufflinks with natural cabochon black onyx stone faces.',
     'BLACK_SUIT', 'TAG_TEXTURE',
     [{'name': 'Gold & Black Onyx', 'hex': '#0A0A0A'}],
     ['Four Studs & Two Cufflinks Set'], 'Natural Black Onyx with 18K Gold Plated Brass', 'Arezzo, Italy',
     'Classic Formal', 'Evening Black-Tie', 'Evening Collection',
     ['Spring-loaded stud back mechanism for easy insertion', 'Delivered in leather jewelry travel case'],
     True, False),

    ('acc-french-leather-bifold-wallet', 'Full-Grain Boxcalf Bifold Wallet (Nero)', 420,
     'French Boxcalf Leather with Eight Card Slots & Cash Divider',
     'Ultra-slim formal wallet engineered to sit flush inside suit jacket interior breast pockets without creating awkward exterior bulges.',
     'TAG_TEXTURE', 'PACKAGING',
     [{'name': 'Nero Black', 'hex': '#0C0C0C'}, {'name': 'Cognac Brown', 'hex': '#583D2A'}],
     ['11cm × 9.5cm (Ultra-Slim 7mm Profile)'], 'Full-Grain French Boxcalf Leather & Moire Silk Lining', 'France & Florence, Italy',
     'Classic Formal', 'Everyday Luxury', 'Signature Collection',
     ['Ultra-slim 7mm profile for suit jacket pocket fit', 'Hand-painted and burnished edges', 'Gold foil embossed N.K FABRICS seal'],
     False, True),

    ('acc-silk-evening-bow-tie', 'Self-Tie Mulberry Silk Satin Bow Tie (Black)', 240,
     'Pure Silk Duchess Satin with Adjustable Collar Slider',
     'Authentic self-tie bow tie with generous butterfly proportion (2.75 inches). Finished with adjustable brass hook slider for neck sizes 14.5 to 18.5.',
     'BLACK_SUIT', 'EVENING_SUIT',
     [{'name': 'Duchess Satin Black', 'hex': '#080808'}],
     ['Adjustable 14.5" - 18.5" Neck'], '100% Pure Como Silk Duchess Satin', 'Como, Italy',
     'Classic Formal', 'Evening Black-Tie', 'Evening Collection',
     ['Authentic self-tie butterfly shape', 'Calibrated satin luster designed to match tuxedo lapels'],
     False, False),

    ('acc-irish-linen-pocket-square', 'Hand-Rolled Irish Linen Pocket Square (White)', 160,
     'Pure Northern Irish Linen with Hand-Rolled Contrast Navy Edge',
     'The cornerstone of sartorial pocket wear. Crisp, absorbent Irish linen that folds into sharp TV folds or casual puff folds without slipping.',
     'SHIRT_WHITE', 'PACKAGING',
     [{'name': 'White with Navy Edge', 'hex': '#FFFFFF'}, {'name': 'White with White Edge', 'hex': '#FAFAFA'}],
     ['40cm × 40cm'], '100% Pure Irish Linen', 'Baird McNutt, Ireland',
     'Classic Formal', 'Business & Boardroom', 'N.K FABRICS Essentials',
     ['100% hand-rolled edges taking 30 minutes of needlework', 'Holds geometric architectural folds with crisp stance'],
     False, False),

    ('acc-suede-dress-belt-espresso', 'Italian Calf Suede Dress Belt (Espresso)', 420,
     '32mm Feathered Suede with Brushed Satin Palladium Buckle',
     'Rich, matte, and tactile. Lined with vegetable-tanned French vachetta leather, designed to pair with suede shoes and flannel tailoring.',
     'SUEDE_JACKET', 'TAG_TEXTURE',
     [{'name': 'Espresso Brown', 'hex': '#2B1D16'}, {'name': 'Snuff Suede', 'hex': '#634E3C'}],
     ['32', '34', '36', '38', '40'], '100% Italian Calf Suede & Vachetta Lining', 'Florence, Italy',
     'Tailored Regular', 'Everyday Luxury', 'Signature Collection',
     ['Feathered edge with tone-on-tone perimeter stitching', 'Brushed palladium buckle'],
     False, False),

    ('acc-silk-evening-dress-scarf', 'Silk Evening Tubular Dress Scarf (Black & Ivory)', 580,
     'Double-Sided Jacquard Silk Tubular Scarf with Hand-Knotted Fringe',
     'The pinnacle of black-tie winter elegance. Tubular double-faced Como silk draped casually over dinner suits, finished with 10cm hand-knotted macramé fringe.',
     'EVENING_SUIT', 'HERO_MODELS',
     [{'name': 'Black & Ivory Jacquard', 'hex': '#0A0A0A'}],
     ['35cm × 180cm + 10cm Fringe'], '100% Heavy Mulberry Silk Jacquard', 'Como, Italy',
     'Classic Formal', 'Evening Black-Tie', 'Evening Collection',
     ['Hand-knotted macramé silk fringe', 'Tubular double-layer construction for plush drape'],
     True, False),

    ('acc-sterling-silver-cufflinks', 'Sterling Silver 925 Monogram Cufflinks', 540,
     'Solid 925 Sterling Silver with Hand-Engraved Guilloché Sunburst',
     'Master jeweler craftsmanship. Solid hallmarked sterling silver featuring engine-turned guilloché ray engraving and an oval monogram center.',
     'TAG_TEXTURE', 'SHIRT_WHITE',
     [{'name': 'Polished Sterling Silver', 'hex': '#E8E8E8'}],
     ['One Size (18mm × 13mm Oval)'], 'Solid 925 Hallmarked Sterling Silver (18.5g)', 'Birmingham Jewellery Quarter, UK',
     'Classic Formal', 'Business & Boardroom', 'Signature Collection',
     ['Engine-turned guilloché pattern', 'Hallmarked with British Assay Office silver stamps', 'Swivel torpedo back'],
     False, False),

    ('acc-egyptian-cotton-dress-socks', 'Mercerized Egyptian Cotton Dress Socks (Trio Pack)', 190,
     'Set of Three Over-the-Calf Socks in Navy, Charcoal, and Black',
     'Engineered never to fall down. Knitted in Italy on 240-needle machines using Fil d’Écosse mercerized Egyptian cotton with hand-linked seamless toes.',
     'PACKAGING', 'TAG_TEXTURE',
     [{'name': 'Navy / Charcoal / Black', 'hex': '#161E2E'}],
     ['Medium (UK 7-9 / US 8-10)', 'Large (UK 10-12 / US 11-13)'], '100% Fil d’Écosse Double-Mercerized Egyptian Cotton', 'Brescia, Italy',
     'Classic Formal', 'Business & Boardroom', 'N.K FABRICS Essentials',
     ['Over-the-calf height staying up throughout 16-hour days', 'Hand-linked seamless toe eliminating rubbing friction', 'Reinforced heel and toe cups'],
     False, True),

    ('acc-cashmere-winter-socks', 'Grade-A Pure Cashmere Winter Socks (Charcoal)', 220,
     '85% Mongolian Cashmere, 15% Stretch Nylon for Shape Memory',
     'The ultimate winter indulgence for gentlemen. Ultra-soft Mongolian cashmere keeping feet blissfully warm inside bespoke dress shoes.',
     'TROUSER_CHARCOAL', 'PACKAGING',
     [{'name': 'Charcoal Cashmere', 'hex': '#2F2F32'}],
     ['Medium (US 8-10)', 'Large (US 11-13)'], '85% Grade-A Mongolian Cashmere, 15% Nylon', 'Biella, Italy',
     'Tailored Regular', 'Winter Collection', 'Winter Collection',
     ['Hand-linked toe seam', 'Ribbed leg providing gentle stay-up hold'],
     False, False),

    ('acc-silk-knit-tie-black', 'Italian Silk Knit Square-End Tie (Black)', 320,
     'Knitted Cri de la Soie Silk on Vintage Tubular Knitting Machines',
     'Crunchy, tactile silk knit that bridges formal and casual wear. The characteristic crunchy handfeel (cri de la soie) pairs impeccably with flannel suits.',
     'BLACK_SUIT', 'NAVY_SUIT',
     [{'name': 'Pitch Black', 'hex': '#0A0A0A'}, {'name': 'Midnight Navy', 'hex': '#101B2E'}],
     ['6.5cm Width × 148cm Length'], '100% Pure Italian Knitted Silk', 'Como, Italy',
     'Tailored Regular', 'Everyday Luxury', 'Signature Collection',
     ['Authentic square bottom hem', 'Unlined tubular knit with grosgrain neckband for collar comfort'],
     False, False),

    ('acc-cashmere-flannel-tie-grey', 'English Cashmere Flannel Tie (Mid-Grey)', 340,
     '90% Wool, 10% Cashmere Flannel Untipped Necktie',
     'Matte cold-weather sophistication. Brushed wool-cashmere flannel with soft hand-rolled edges, offering substantial texture under chalk stripe suiting.',
     'HERO_MODELS', 'CHALK_STRIPE',
     [{'name': 'Mid-Grey Flannel', 'hex': '#666668'}],
     ['8.5cm Width × 150cm Length'], '90% English Wool, 10% Cashmere Flannel', 'Somerset, UK & Como, Italy',
     'Classic Formal', 'Winter Collection', 'Winter Collection',
     ['Untipped hand-rolled edges', 'Self-fabric keeper loop and hand-basted bar tacks'],
     False, False),

    ('acc-champagne-lapel-pin', 'Champagne Gold Rose Flower Lapel Pin', 260,
     'Hand-Cast Solid Brass Gilded in 18K Champagne Gold with Boutonnière Stem',
     'The subtle mark of distinction. A sculptured miniature rose bud cast in solid brass with an extended needle pin designed to slide into bespoke lapel flower loops.',
     'TAG_TEXTURE', 'BLACK_SUIT',
     [{'name': 'Champagne Gold', 'hex': '#C8A97E'}],
     ['12mm Flower Head × 65mm Pin Stem'], 'Solid Brass with 18K PVD Champagne Gold Gilding', 'Arezzo, Italy',
     'Classic Formal', 'Wedding & Gala', 'Signature Collection',
     ['Designed specifically to slide through Milanese lapel buttonholes', 'Protective safety end cap included'],
     True, False),

    ('acc-french-calfskin-cardholder', 'Slim Boxcalf Cardholder with Monogram (Black)', 280,
     'Four Card Slots with Central Cash Pocket in French Boxcalf',
     'Ultra-compact cardholder measuring just 4mm thickness. Hand-painted edges with gold hot-stamped N.K FABRICS atelier emblem.',
     'TAG_TEXTURE', 'PACKAGING',
     [{'name': 'Nero Black', 'hex': '#0A0A0A'}],
     ['10cm × 7cm (4mm Ultra-Slim)'], '100% Full-Grain French Boxcalf Leather', 'France',
     'Classic Formal', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Four card slots with central lined banknote sleeve', 'Hand-burnished edges'],
     False, True),

    ('acc-long-coat-breast-wallet', 'Executive Long Coat Breast Pocket Wallet', 520,
     'Twelve Card Slots, Dual Banknote Sleeves in Full-Grain Boxcalf',
     'The gentleman’s traditional coat wallet. Sits completely flat inside suit jacket breast pockets, holding unfolded international currency and cards.',
     'BLACK_SUIT', 'TAG_TEXTURE',
     [{'name': 'Nero Black', 'hex': '#080808'}, {'name': 'Espresso Brown', 'hex': '#251710'}],
     ['18.5cm × 9.5cm (Flat Profile)'], 'Full-Grain French Calfskin with Silk Lining', 'Florence, Italy',
     'Classic Formal', 'Business & Boardroom', 'Signature Collection',
     ['Twelve credit card slots and two full-length currency sleeves', 'Designed to fit suit interior breast pockets without bulging'],
     False, False),

    ('acc-braided-leather-belt-brown', 'Hand-Braided Vegetable Tanned Leather Belt', 390,
     '35mm Hand-Woven Italian Saddle Leather with Solid Brass Buckle',
     'Artisanal flexibility. Platted by hand from supple vegetable-tanned bridle leather, allowing the buckle prong to pass through any point for customized fit.',
     'CASUAL_SHIRT', 'TAG_TEXTURE',
     [{'name': 'Chestnut Brown', 'hex': '#543621'}, {'name': 'Black Leather', 'hex': '#0C0C0C'}],
     ['32', '34', '36', '38', '40'], '100% Vegetable-Tanned Italian Bridle Leather', 'Tuscany, Italy',
     'Tailored Regular', 'Resort & Casual', 'Summer Collection',
     ['Solid brass buckle with satin antique brass finish', 'Micro-adjustable braided weave without pre-punched holes'],
     False, False),
]

print(f"Accessories configured: {len(accessories)}")
