# 22 Unique Casual Shirts for N.K FABRICS

casual_shirts = [
    ('cs-sandstone-linen-overshirt', 'Sandstone Pure Irish Linen Overshirt', 580,
     'Heavyweight Irish Linen with Dual Chest Patch Pockets',
     'The cornerstone of relaxed sartorial dressing. Open-collar construction in breathable Irish linen, tailored with horn buttons and straight hem with side vents for wearing untucked.',
     'CASUAL_SHIRT', 'ESSENTIALS_POLO',
     [{'name': 'Sandstone Taupe', 'hex': '#C2B199'}, {'name': 'Oatmeal', 'hex': '#D8CEBF'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Heavyweight Irish Linen (260g/m)', 'Baird McNutt, Northern Ireland',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Dual chest flap patch pockets with horn button closures', 'Straight hem with side vents for untucked wear', 'Soft unlined spread collar'],
     True, True),

    ('cs-classic-white-oxford-bd', 'Signature Heavyweight Oxford Button-Down', 460,
     'American Long-Staple Supima Cotton in Classic 3-Inch Collar Roll',
     'The definitive Ivy-style classic. Heavyweight Oxford cloth with an authentic soft collar roll, mother-of-pearl buttons, and back box pleat with locker loop.',
     'CASUAL_SHIRT', 'SHIRT_WHITE',
     [{'name': 'Oxford White', 'hex': '#FFFFFF'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Long-Staple Supima Cotton Oxford', 'Albini Group, Italy',
     'Tailored Regular', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Unlined button-down collar with natural 3-inch roll', 'Center back box pleat and locker loop', 'Generous curved hem'],
     False, True),

    ('cs-sky-blue-oxford-bd', 'Sky Blue Heavyweight Oxford Button-Down', 460,
     'Classic Melange Oxford Weave in Heritage Sky Blue',
     'The timeless weekend staple. Dense basketweave cotton that softens and acquires personal character with every wash, finished with mother-of-pearl buttons.',
     'CASUAL_SHIRT', 'NAVY_SUIT',
     [{'name': 'Sky Blue', 'hex': '#8BB1D4'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Long-Staple Supima Cotton Oxford', 'Albini Group, Italy',
     'Tailored Regular', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Chalk white genuine mother-of-pearl buttons', 'Single rounded chest pocket', 'Unlined cuffs for easy rolling'],
     False, False),

    ('cs-navy-indigo-linen-shirt', 'Indigo-Dyed Pure Linen Casual Shirt', 520,
     'Deep Indigo Raw Linen with Natural Texture & Camp Collar',
     'Rich, saturated indigo hue that breathes effortlessly in Mediterranean heat. Styled with a retro camp collar and mother-of-pearl buttons.',
     'CASUAL_SHIRT', 'NAVY_SUIT',
     [{'name': 'Deep Indigo', 'hex': '#1C2B42'}, {'name': 'Washed Navy', 'hex': '#283C5A'}],
     ['S', 'M', 'L', 'XL'], '100% Pure Normandy Linen', 'Normandy, France',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Convertible camp open collar', 'Straight hem with side vents', 'Natural mother-of-pearl buttons'],
     True, False),

    ('cs-olive-safari-overshirt', 'Tuscan Olive Cotton-Linen Safari Overshirt', 620,
     'Military-Inspired Four-Pocket Field Shirt in Cotton-Linen Twill',
     'Rugged elegance. Four button-through bellows pockets on the front provide ample storage while the breathable cotton-linen twill holds a crisp, structured drape.',
     'CASUAL_SHIRT', 'SUEDE_JACKET',
     [{'name': 'Tuscan Olive', 'hex': '#3D4435'}, {'name': 'Khaki Tan', 'hex': '#7A6B53'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '60% Linen, 40% Egyptian Cotton (280g/m)', 'Tuscany, Italy',
     'Relaxed Drape', 'Everyday Luxury', 'Essential Collection',
     ['Four front bellows pockets with buttoned flaps', 'Internal waist drawstring for adjustable suppression', 'Dark horn buttons'],
     False, False),

    ('cs-madras-check-linen', 'Heritage Multicolored Madras Linen Shirt', 480,
     'Authentic Hand-Woven Madras Plaid with Relaxed Spread Collar',
     'Vibrant summer elegance. Traditional Madras plaid interweaving navy, burgundy, and ecru yarns, washed for a super-soft lived-in handfeel.',
     'CASUAL_SHIRT', 'HERO_MODELS',
     [{'name': 'Heritage Madras Plaid', 'hex': '#5A333A'}],
     ['S', 'M', 'L', 'XL'], '100% Pure Indian Handloom Linen', 'Chennai Artisans & N.K FABRICS',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Soft unlined button-down collar', 'Single chest patch pocket with pen slot'],
     False, False),

    ('cs-espresso-corduroy-overshirt', 'Fine-Wale Espresso Cotton Corduroy Overshirt', 540,
     'Baby Corduroy 18-Wale in Rich Roasted Espresso Brown',
     'Warm, tactile layering for autumn. Velvety 18-wale micro-corduroy woven from Italian cotton, finished with dark horn buttons and twin flap pockets.',
     'CASUAL_SHIRT', 'TROUSER_CHARCOAL',
     [{'name': 'Espresso Brown', 'hex': '#2D1F18'}, {'name': 'Cognac Tan', 'hex': '#5E3E2B'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Fine-Wale Italian Cotton Corduroy', 'Brescia, Italy',
     'Tailored Regular', 'Winter Collection', 'Winter Collection',
     ['Dual chest pockets with buttoned flaps', 'Hand-stitched horn buttons', 'Satin-lined collar band for neck comfort'],
     False, False),

    ('cs-resort-camp-collar-ivory', 'Riviera Camp-Collar Silk-Linen Resort Shirt', 590,
     'Unstructured Open-Collar Shirt in 55% Silk, 45% Linen',
     'The definitive seaside luxury shirt. Fluid silk drape combined with the cooling properties of open-weave linen, finished with a retro one-piece holiday collar.',
     'CASUAL_SHIRT', 'TRAD_IVORY',
     [{'name': 'Ivory Silk-Linen', 'hex': '#F7F3E9'}, {'name': 'Oatmeal', 'hex': '#E2DACB'}],
     ['S', 'M', 'L', 'XL'], '55% Mulberry Silk, 45% Linen (190g/m)', 'Como & Ireland',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Continuous camp collar with no neckband', 'Straight hem designed strictly for untucked wear', 'Carved Australian mother-of-pearl buttons'],
     True, False),

    ('cs-chambray-selvedge-workshirt', 'Japanese Selvedge Chambray Casual Shirt', 490,
     'Authentic 5oz Shuttle-Loomed Selvedge Chambray with Triple Stitching',
     'Artisanal workwear elevated to luxury. Shuttle-loomed on vintage Toyoda looms with white selvedge ID line along the side gussets and triple-needle chainstitching.',
     'CASUAL_SHIRT', 'NAVY_SUIT',
     [{'name': 'Washed Chambray Blue', 'hex': '#5B7A9C'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Japanese Selvedge Cotton Chambray (5oz)', 'Kojima, Okayama, Japan',
     'Tailored Regular', 'Everyday Luxury', 'Essential Collection',
     ['Triple-needle chainstitched seams with run-off thread detail', 'Selvedge side seam gussets', 'Catseye urea buttons'],
     False, False),

    ('cs-black-washed-linen-casual', 'Nocturne Washed Linen Button-Down', 510,
     'Pre-Washed Black Irish Linen with Relaxed Texture',
     'Sleek, dark, and summery. Enzyme-washed to achieve a velvety soft matte surface that drapes effortlessly over tailored shorts or linen trousers.',
     'CASUAL_SHIRT', 'BLACK_SUIT',
     [{'name': 'Pitch Black', 'hex': '#0A0A0A'}],
     ['S', 'M', 'L', 'XL'], '100% Irish Linen Enzyme Washed', 'Baird McNutt, Ireland',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Hidden button-down collar points', 'Smoked dark mother-of-pearl buttons'],
     False, False),

    ('cs-flannel-buffalo-check-navy', 'Navy & Charcoal Brushed Flannel Casual Shirt', 480,
     'Double-Brushed Heavyweight Cotton Flannel for Winter Warmth',
     'Supreme cold-weather comfort. Fluffy double-brushed cotton flannel in a muted navy and charcoal buffalo check that feels like cashmere against the skin.',
     'CASUAL_SHIRT', 'HERO_MODELS',
     [{'name': 'Navy & Charcoal Check', 'hex': '#232C3A'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Double-Brushed Cotton Flannel (240g/m)', 'Portugal',
     'Tailored Regular', 'Winter Collection', 'Winter Collection',
     ['Twin chest buttoned flap pockets', 'Reinforced elbow patches in self fabric', 'Matte horn buttons'],
     False, False),

    ('cs-terry-cloth-resort-shirt', 'French Terry Resort Button-Up Shirt', 470,
     'Pure Cotton Knit Terry Cloth with Camp Collar',
     'Designed for yacht decks and poolside terraces. Ultra-absorbent looped cotton terry cloth that replaces standard shirting with casual, tactile luxury.',
     'CASUAL_SHIRT', 'ESSENTIALS_POLO',
     [{'name': 'Off-White Terry', 'hex': '#F4EFE6'}, {'name': 'Navy Blue', 'hex': '#141E30'}],
     ['S', 'M', 'L', 'XL'], '100% Cotton Knitted Loop Terry (220g/m)', 'Portugal',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Camp collar with loop closure', 'Breathable looped pile texture', 'Natural mother-of-pearl buttons'],
     True, False),

    ('cs-striped-poplin-relaxed', 'Green & White Awning Stripe Relaxed Shirt', 450,
     'Bold 8mm Awning Stripe in Crisp Egyptian Cotton Poplin',
     'Mediterranean holiday flair. Broad green and white deckchair stripes cut in an oversized relaxed silhouette with dropped shoulders and a curved hem.',
     'CASUAL_SHIRT', 'HERO_MODELS',
     [{'name': 'Forest Green Stripe', 'hex': '#2B4A34'}],
     ['S', 'M', 'L', 'XL'], '100% Egyptian Cotton Poplin (120/2)', 'Thomas Mason, Italy',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Wide spread collar with soft unlined construction', 'Dropped shoulder seam for easy drape'],
     False, False),

    ('cs-wool-overshirt-charcoal', 'Melton Wool CPO Overshirt (Charcoal)', 690,
     'Heavy 16oz British Melton Wool with Satin Sleeve Lining',
     'A hybrid between jacket and shirt. Heavyweight Melton wool that repels wind and light rain, designed to layer over t-shirts and knitwear.',
     'CASUAL_SHIRT', 'TROUSER_CHARCOAL',
     [{'name': 'Charcoal Melton', 'hex': '#262626'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% British Pure Wool Melton (16oz)', 'Abraham Moon, Yorkshire, UK',
     'Relaxed Drape', 'Winter Collection', 'Winter Collection',
     ['Twin anchor-engraved horn buttons on chest pockets', 'Satin-lined sleeves for smooth layering', 'Straight hem'],
     True, False),

    ('cs-botanical-print-silk-shirt', 'Botanical Nocturne Printed Silk Resort Shirt', 680,
     'Monochrome Hand-Printed Mulberry Silk Crepe de Chine',
     'Evening resort elegance. Fluid black silk crepe with subtle cream botanical leaf motifs, cut with an open camp collar and French seams.',
     'CASUAL_SHIRT', 'BLACK_SUIT',
     [{'name': 'Nocturne Botanical', 'hex': '#111111'}],
     ['S', 'M', 'L', 'XL'], '100% Pure Mulberry Silk Crepe (18 Momme)', 'Como, Italy',
     'Relaxed Drape', 'Evening Black-Tie', 'Limited Edition',
     ['Hand-screen printed in Como', 'Genuine mother-of-pearl buttons', 'Straight split hem'],
     False, False),

    ('cs-denim-western-shirt-raw', 'Selvedge Raw Denim Western Casual Shirt', 530,
     '8oz Japanese Deep Indigo Raw Denim with Mother-of-Pearl Snaps',
     'Elevated Western tailoring. Slanted sawtooth chest pockets, shaped Western shoulder yokes, and genuine iridescent mother-of-pearl snap fasteners.',
     'CASUAL_SHIRT', 'NAVY_SUIT',
     [{'name': 'Raw Indigo', 'hex': '#162238'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Japanese Selvedge Denim (8oz)', 'Kojima, Japan',
     'Tailored Regular', 'Everyday Luxury', 'Signature Collection',
     ['Mother-of-pearl snap buttons throughout', 'Sawtooth double flap pockets', 'Shaped front and back Western yokes'],
     False, False),

    ('cs-linen-band-collar-white', 'Mandarin Band-Collar Pure Linen Shirt', 490,
     'Pure French Linen with Clean Stand Collar & Popover Placket',
     'Minimalist warm-weather tailoring. Three-button popover placket and a crisp mandarin band collar that channels quiet luxury.',
     'CASUAL_SHIRT', 'TRAD_IVORY',
     [{'name': 'Pure White', 'hex': '#FFFFFF'}, {'name': 'Natural Ecru', 'hex': '#E8E1D2'}],
     ['S', 'M', 'L', 'XL'], '100% French Normandy Linen', 'France',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Three-button popover half-placket', 'Unstructured mandarin stand collar', 'Single chest pocket'],
     False, False),

    ('cs-micro-gingham-navy-white', 'Executive Navy Gingham Poplin Shirt', 460,
     'Micro 2mm Navy Gingham Check with Button-Down Collar',
     'Smart-casual perfection. Worn under sweaters or with chinos for effortless Friday elegance without losing sartorial sharpness.',
     'CASUAL_SHIRT', 'HERO_MODELS',
     [{'name': 'Navy Gingham', 'hex': '#1B2E4B'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Long-Staple Egyptian Cotton (120/2)', 'Albini Group, Italy',
     'Tailored Regular', 'Business & Boardroom', 'N.K FABRICS Essentials',
     ['Button-down collar with 3-inch roll', 'Genuine mother-of-pearl buttons'],
     False, False),

    ('cs-cashmere-cotton-flannel', 'Cashmere-Enriched Cotton Flannel Shirt', 640,
     '85% Cotton, 15% Cashmere in Warm Camel Heather',
     'Unsurpassed softness. A blend of brushed cotton and Grade-A cashmere that delivers cozy thermal performance with zero bulk.',
     'CASUAL_SHIRT', 'ESSENTIALS_POLO',
     [{'name': 'Camel Heather', 'hex': '#A88D6A'}],
     ['S', 'M', 'L', 'XL'], '85% Cotton, 15% Cashmere (Albiate)', 'Albini Group, Italy',
     'Tailored Regular', 'Winter Collection', 'Winter Collection',
     ['Soft spread collar with removable stays', 'Mother-of-pearl smoked buttons'],
     False, False),

    ('cs-khaki-poplin-military-shirt', 'Field Khaki High-Density Poplin Shirt', 480,
     'Structured 140s Cotton Poplin with Shoulder Epaulettes',
     'Sharp utilitarian styling. Finished with military shoulder epaulettes, dual pleated chest pockets, and a buttoned storm placket.',
     'CASUAL_SHIRT', 'HERO_MODELS',
     [{'name': 'Field Khaki', 'hex': '#736852'}],
     ['S', 'M', 'L', 'XL', 'XXL'], 'Super 140s Compact Cotton Poplin', 'Thomas Mason, Italy',
     'Tailored Regular', 'Everyday Luxury', 'Essential Collection',
     ['Shoulder epaulettes with horn buttons', 'Dual pleated bellows chest pockets'],
     False, False),

    ('cs-linen-guayabera-ivory', 'Four-Pocket Linen Guayabera Shirt', 570,
     'Pure Linen with Vertical Alforzas Pleats & Split Hem',
     'The aristocratic tropical dress shirt. Four patch pockets and precision vertical micro-pleating (alforzas) down front and back.',
     'CASUAL_SHIRT', 'TRAD_IVORY',
     [{'name': 'Ivory Linen', 'hex': '#F9F5EC'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Pure Irish Linen (230g/m)', 'Baird McNutt, Ireland',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Four front patch pockets with decorative buttons', 'Vertical alforzas tuck pleating', 'Side buttoned vents'],
     True, False),

    ('cs-navy-silk-bowling-shirt', 'Retro Silk Bowling Camp Shirt (Navy)', 620,
     'Heavy 22-Momme Silk Twill with Contrast Cream Piping',
     'Vintage elegance modernized. Dense silk twill in deep midnight navy with ivory piping along the camp collar and chest pocket.',
     'CASUAL_SHIRT', 'NAVY_SUIT',
     [{'name': 'Midnight Navy', 'hex': '#0D172B'}],
     ['S', 'M', 'L', 'XL'], '100% Pure Mulberry Silk Twill (22 Momme)', 'Como, Italy',
     'Relaxed Drape', 'Evening Black-Tie', 'Limited Edition',
     ['Contrast cream silk piping along collar and pocket', 'Straight boxy hem with side vents'],
     False, True),
]

print(f"Casual shirts configured: {len(casual_shirts)}")
