# 16 Polo Shirts and 16 T-Shirts for N.K FABRICS

polos = [
    ('po-silk-cotton-cream', '18-Gauge Silk-Cotton Knitted Polo (Cream)', 520,
     '18-Gauge Silk & Sea Island Cotton Knitted Open Collar Polo',
     'The essence of quiet luxury. Hand-linked on 18-gauge machines from mulberry silk and long-staple cotton, finished with a seamless placket and ribbed cuffs.',
     'ESSENTIALS_POLO', 'TRAD_IVORY',
     [{'name': 'Warm Cream', 'hex': '#EDE8DF'}, {'name': 'Midnight Navy', 'hex': '#141E2E'}],
     ['S', 'M', 'L', 'XL'], '55% Mulberry Silk, 45% Long-Staple Cotton (18-Gauge Knit)', 'Biella, Italy',
     'Tailored Regular', 'Resort & Casual', 'Quiet Luxury',
     ['Fully fashioned seamless collar and placket', 'Ribbed cuffs and waistband that hug gently without pinching'],
     False, True),

    ('po-noir-merino-wool', 'Noir Extra-Fine Worsted Merino Polo', 560,
     'Super 160s Worsted Merino Wool with Genuine Mother-of-Pearl Buttons',
     'Worn comfortably beneath sport coats or as a standalone statement. Temperature-regulating merino wool with natural elasticity and an ultra-fine hand.',
     'ESSENTIALS_POLO', 'BLACK_SUIT',
     [{'name': 'Deep Black', 'hex': '#0C0C0C'}, {'name': 'Charcoal', 'hex': '#222222'}],
     ['S', 'M', 'L', 'XL'], '100% Super 160s Worsted Merino Wool (190g/m)', 'Zegna Baruffa, Biella, Italy',
     'Slim Fit', 'Business & Boardroom', 'Signature Collection',
     ['Three-button placket with real smoked mother-of-pearl buttons', 'Natural wrinkle recovery and odor resistance'],
     False, False),

    ('po-longsleeve-resort-cashmere', 'Long-Sleeve Cashmere-Silk Resort Polo', 680,
     'Long-Sleeve Ribbed Polo in Mongolian Cashmere & Mulberry Silk',
     'A luxurious transition piece. Combines the softness of Grade-A cashmere with the gentle drape of mulberry silk, finished with tailored shirt-style cuffs.',
     'ESSENTIALS_POLO', 'HERO_MODELS',
     [{'name': 'Sandstone', 'hex': '#D8CEBE'}, {'name': 'Midnight Navy', 'hex': '#111A29'}],
     ['S', 'M', 'L', 'XL'], '70% Silk, 30% Mongolian Cashmere', 'Biella, Italy',
     'Tailored Regular', 'Everyday Luxury', 'Signature Collection',
     ['Mitered shirt-style cuffs with mother-of-pearl buttons', 'Camp-style open collar with zero buttons'],
     True, False),

    ('po-emerald-silk-knit', 'Imperial Emerald Knitted Silk Polo', 540,
     '18-Gauge Pure Silk Knit with Contrast Champagne Collar Edge',
     'Distinctive jewel-tone nobility. Emerald green pure silk knit detailed with a delicate champagne gold micro-stripe along the knitted collar.',
     'EMERALD_SILK', 'ESSENTIALS_POLO',
     [{'name': 'Emerald', 'hex': '#0F2B20'}, {'name': 'Nocturne Green', 'hex': '#071A12'}],
     ['S', 'M', 'L', 'XL'], '100% Pure Mulberry Silk Knit', 'Como, Italy',
     'Slim Fit', 'Ceremony & Eid', 'Wedding Collection',
     ['Contrast champagne gold tipping on collar edge', 'Three-button hand-finished placket'],
     False, False),

    ('po-johnny-collar-navy-pique', 'Johnny Collar Sea Island Cotton Piqué Polo', 480,
     'Buttonless Johnny Collar in Heavyweight Egyptian Piqué Knit',
     'The clean, contemporary polo. Buttonless V-neckline that rolls naturally without button clutter, crafted from breathable honeycomb cotton piqué.',
     'NAVY_SUIT', 'ESSENTIALS_POLO',
     [{'name': 'Midnight Navy', 'hex': '#101C30'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Sea Island Long-Staple Cotton Piqué (220g/m)', 'Thomas Mason, Italy',
     'Tailored Regular', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Clean buttonless Johnny open collar', 'Ribbed collar and sleeve bands that retain structure'],
     True, True),

    ('po-waffle-knit-longsleeve-grey', 'Charcoal Waffle-Knit Long-Sleeve Polo', 590,
     'Superfine Merino Wool Honeycomb Knit with Horn Buttons',
     'Textured thermal luxury. Three-dimensional honeycomb knit that breathes naturally while trapping warm air close to the torso.',
     'TROUSER_CHARCOAL', 'HERO_MODELS',
     [{'name': 'Charcoal Melange', 'hex': '#323236'}],
     ['S', 'M', 'L', 'XL'], '100% Super 140s Merino Wool (Honeycomb Weave)', 'Biella, Italy',
     'Tailored Regular', 'Winter Collection', 'Winter Collection',
     ['Three-button placket with dark buffalo horn buttons', 'Ribbed cuffs that push up securely on the forearm'],
     False, False),

    ('po-retro-striped-resort-polo', 'Riviera Deco-Stripe Silk-Cotton Polo', 560,
     'Vertical Knit Retro Stripe in Ivory and Tobacco Brown',
     'Vintage Mediterranean leisure. Knitted vertical block stripes inspired by 1960s Portofino, finished with a spread open collar.',
     'CASUAL_SHIRT', 'ESSENTIALS_POLO',
     [{'name': 'Ivory & Tobacco', 'hex': '#EADEC9'}],
     ['S', 'M', 'L', 'XL'], '60% Silk, 40% Egyptian Cotton', 'Como, Italy',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Knitted vertical block stripes with zero printing', 'Open spread collar with relaxed fit'],
     True, False),

    ('po-zip-neck-merino-black', 'Nocturne Quarter-Zip Merino Wool Polo', 580,
     'Super 150s Merino Wool with Solid Champagne Gold Zipper',
     'Modern athletic tailoring. Minimalist metal zipper replaces buttons, delivering a sleek, unbroken collar line that looks sharp under jackets.',
     'BLACK_SUIT', 'ESSENTIALS_POLO',
     [{'name': 'Pitch Black', 'hex': '#0A0A0A'}],
     ['S', 'M', 'L', 'XL'], 'Super 150s Worsted Merino Wool (190g/m)', 'Biella, Italy',
     'Slim Fit', 'Evening Black-Tie', 'Signature Collection',
     ['Concealed gold Lampo zipper mechanism', 'Fine rib collar with shape retention'],
     False, False),

    ('po-sandstone-linen-knit', 'Sandstone Pure Knitted Linen Polo', 490,
     'Airy Linen Slub Knit with Mother-of-Pearl Three-Button Placket',
     'The ultimate high-summer polo. Knitted from delicate linen yarns with natural slub textures, offering cooling ventilation in tropical heat.',
     'CASUAL_SHIRT', 'TRAD_IVORY',
     [{'name': 'Sandstone Taupe', 'hex': '#CDBFA8'}, {'name': 'Natural Ecru', 'hex': '#E0D6C3'}],
     ['S', 'M', 'L', 'XL'], '100% Pure Knitted French Linen (170g/m)', 'Normandy, France',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Lightweight knitted linen with natural cooling drape', 'Australian mother-of-pearl buttons'],
     False, False),

    ('po-french-blue-mercerized-pique', 'French Blue Double-Mercerized Piqué Polo', 460,
     'Ultra-Smooth Double-Mercerized Egyptian Cotton with Silk Luster',
     'Radiant color depth and silky handfeel. The double-mercerization process locks in the French blue dye, preventing fading after repeated wear.',
     'SHIRT_WHITE', 'NAVY_SUIT',
     [{'name': 'French Blue', 'hex': '#365D88'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Giza 87 Double-Mercerized Cotton', 'Albini Group, Italy',
     'Tailored Regular', 'Business & Boardroom', 'N.K FABRICS Essentials',
     ['Double-mercerized silky sheen', 'Interlined woven shirt collar that never curls'],
     False, False),

    ('po-olive-cashmere-knit', 'Tuscan Olive Cashmere Short-Sleeve Polo', 690,
     'Featherweight 1-Ply Mongolian Cashmere in Deep Olive Green',
     'Decadently soft luxury. Spun from ultra-fine 1-ply worsted cashmere for warm weather, offering a cloud-like touch against bare skin.',
     'EMERALD_SILK', 'ESSENTIALS_POLO',
     [{'name': 'Tuscan Olive', 'hex': '#3B4834'}],
     ['S', 'M', 'L', 'XL'], '100% 1-Ply Featherweight Mongolian Cashmere', 'Cariaggi, Italy',
     'Tailored Regular', 'Everyday Luxury', 'Signature Collection',
     ['Seamless fully fashioned knit', 'Three horn buttons with cross stitch'],
     True, False),

    ('po-burgundy-silk-pique', 'Imperial Burgundy Silk-Cotton Piqué Polo', 530,
     'Textured Honeycomb Piqué in Rich Imperial Wine',
     'Sophisticated weekend depth. Woven from a rich blend of silk and cotton in a micro-honeycomb piqué that pairs with grey or cream trousers.',
     'EVENING_SUIT', 'HERO_MODELS',
     [{'name': 'Imperial Burgundy', 'hex': '#481320'}],
     ['S', 'M', 'L', 'XL'], '50% Mulberry Silk, 50% Giza Cotton', 'Como, Italy',
     'Slim Fit', 'Wedding & Gala', 'Evening Collection',
     ['Mother-of-pearl buttons with burgundy thread', 'Ribbed cuffs with contrast tipping'],
     False, False),

    ('po-terry-cloth-resort-navy', 'Navy Terry Toweling Open-Collar Polo', 450,
     'Pure Cotton Terry Toweling Knit for Beachside Relaxation',
     'Inspired by vintage 1970s Saint-Tropez. Plush looped cotton terry cloth that absorbs ocean spray while delivering effortless sartorial style.',
     'NAVY_SUIT', 'CASUAL_SHIRT',
     [{'name': 'Riviera Navy', 'hex': '#142036'}],
     ['S', 'M', 'L', 'XL'], '100% Cotton Knitted Loop Terry (230g/m)', 'Portugal',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Camp open neckline without buttons', 'Breathable looped pile fabric'],
     False, False),

    ('po-chocolate-fine-merino', 'Espresso Chocolate Extra-Fine Merino Polo', 550,
     'Deep Roasted Chocolate Brown in Super 160s Merino Knit',
     'A luxurious neutral staple. Deep espresso brown that adds rich warmth beneath camel coats, suede jackets, and charcoal tailoring.',
     'TROUSER_CHARCOAL', 'HERO_MODELS',
     [{'name': 'Espresso Brown', 'hex': '#281912'}],
     ['S', 'M', 'L', 'XL'], 'Super 160s Extra-Fine Merino Wool', 'Zegna Baruffa, Italy',
     'Tailored Regular', 'Winter Collection', 'Winter Collection',
     ['Natural horn buttons with laser engraving', 'Seamless rib cuffs and hem'],
     False, False),

    ('po-white-knit-dress-collar', 'White Knitted Polo with Woven Shirt Collar', 490,
     'Knitted Mercerized Cotton Body with Crisp Woven Poplin Collar',
     'The ultimate hybrid polo. Combines the comfort of a knitted tee body with the crisp, firm collar of a bespoke dress shirt.',
     'SHIRT_WHITE', 'ESSENTIALS_POLO',
     [{'name': 'Optical White', 'hex': '#FFFFFF'}],
     ['S', 'M', 'L', 'XL', 'XXL'], 'Body: 100% Mercerized Cotton Knit / Collar: 100% Giza Poplin', 'Albini Group, Italy',
     'Slim Fit', 'Business & Boardroom', 'Signature Collection',
     ['Firm woven shirt collar that stays upright under suit jackets', 'Removable brass stays inside collar points'],
     True, False),

    ('po-powder-blue-cashmere-silk', 'Powder Blue Cashmere-Silk Knitted Polo', 690,
     'Featherweight Cashmere and Mulberry Silk in Pale Azure',
     'An ethereal springtime luxury. The pale azure hue complements grey flannel and tan trousers with aristocratic distinction.',
     'SHIRT_WHITE', 'ESSENTIALS_POLO',
     [{'name': 'Powder Blue', 'hex': '#A8C2DC'}],
     ['S', 'M', 'L', 'XL'], '70% Silk, 30% Mongolian Cashmere', 'Biella, Italy',
     'Tailored Regular', 'Resort & Casual', 'Summer Collection',
     ['Mother-of-pearl buttons with silk loop fasteners', 'Hand-linked shoulders'],
     False, True),
]

# =========================================================================
# 9. T-SHIRTS (16 Products)
# =========================================================================
tshirts = [
    ('ts-giza87-mercerized-black', 'Giza 87 Mercerized T-Shirt (Black)', 320,
     'Double-Mercerized Giza 87 Cotton with Silk Luster & Bound Neck',
     'The definitive luxury tee. Spun from rare Giza 87 Egyptian cotton and double-mercerized for an intense, silky luster and immaculate shape retention over hundreds of wears.',
     'ESSENTIALS_POLO', 'BLACK_SUIT',
     [{'name': 'Pitch Black', 'hex': '#0C0C0C'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Giza 87 Egyptian Cotton (180g/m)', 'Albini Group, Italy',
     'Tailored Regular', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Double-needle hem and sleeve finish with blind stitch', 'Bound neckline that never stretches or wrinkles'],
     False, True),

    ('ts-giza87-mercerized-white', 'Giza 87 Mercerized T-Shirt (White)', 320,
     'Double-Mercerized Ultra-White Long-Staple Cotton',
     'Crisp, radiant, and heavy enough to prevent translucency. Designed to layer beneath bespoke jackets or stand alone with pleated trousers.',
     'SHIRT_WHITE', 'ESSENTIALS_POLO',
     [{'name': 'Optical White', 'hex': '#FFFFFF'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Giza 87 Double-Mercerized Egyptian Cotton', 'Albini Group, Italy',
     'Tailored Regular', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Zero side seams for seamless cylindrical silhouette', 'Embroidered tonal micro-monogram on left rib'],
     False, True),

    ('ts-giza87-mercerized-charcoal', 'Giza 87 Mercerized T-Shirt (Charcoal)', 320,
     'Deep Charcoal Grey Mercerized Cotton with Micro-Neckband',
     'An executive casual essential. The deep anthracite charcoal shade absorbs lighting with rich depth, pairing flawlessly with grey and black tailoring.',
     'TROUSER_CHARCOAL', 'ESSENTIALS_POLO',
     [{'name': 'Anthracite Charcoal', 'hex': '#262626'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Giza 87 Double-Mercerized Cotton', 'Albini Group, Italy',
     'Tailored Regular', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Tailored sleeve angle designed to flatter bicep silhouette', 'Blind-stitched hems'],
     False, False),

    ('ts-heavyweight-280gsm-navy', 'Heavyweight 280gsm Relaxed Cotton Tee (Navy)', 340,
     'Substantial 280g/m Combed Cotton with Dropped Shoulder Fit',
     'Thick, architectural drape. Heavyweight single jersey that never clings, maintaining a clean boxy silhouette over tailored trousers and chinos.',
     'NAVY_SUIT', 'ESSENTIALS_POLO',
     [{'name': 'Deep Navy', 'hex': '#101B2E'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Long-Staple Combed Cotton (280g/m Heavyweight)', 'Portugal',
     'Relaxed Drape', 'Everyday Luxury', 'Signature Collection',
     ['Dropped shoulder seam with boxy modern chest cut', 'Heavy 2.5cm ribbed collar with elastane reinforcement'],
     True, False),

    ('ts-heavyweight-280gsm-white', 'Heavyweight 280gsm Relaxed Cotton Tee (White)', 340,
     '100% Opaque Heavyweight Architectural Cotton Crewneck',
     'The holy grail of white tees. Absolute zero translucency, heavy clean drape that drapes away from the torso, and an unyielding reinforced crew collar.',
     'SHIRT_WHITE', 'HERO_MODELS',
     [{'name': 'Opaque Chalk White', 'hex': '#FDFDFD'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Long-Staple Combed Cotton (280g/m)', 'Portugal',
     'Relaxed Drape', 'Everyday Luxury', 'Signature Collection',
     ['Complete opacity with dense 280gsm weight', 'Pre-shrunk fabric ensuring zero wash shrinkage'],
     False, True),

    ('ts-silk-cotton-blend-noir', 'Silk-Cotton Luxury Crewneck Tee (Noir)', 380,
     '55% Mulberry Silk, 45% Mercerized Giza Cotton Jersey',
     'The ultimate luxury t-shirt. The addition of mulberry silk creates a cool, liquid handfeel and an elegant fluid drape that elevates standard casualwear.',
     'BLACK_SUIT', 'ESSENTIALS_POLO',
     [{'name': 'Nocturne Noir', 'hex': '#0A0A0A'}],
     ['S', 'M', 'L', 'XL'], '55% Mulberry Silk, 45% Giza Cotton (170g/m)', 'Como, Italy',
     'Slim Fit', 'Evening Black-Tie', 'Signature Collection',
     ['Liquid silk drape with subtle nocturnal sheen', 'Ultra-flat bonded hem for invisible under-jacket lines'],
     True, False),

    ('ts-sandstone-slub-cotton', 'Sandstone Slub Cotton Textured Tee', 290,
     'Organic Slub Cotton Jersey with Natural Uneven Texture',
     'Organic, tactile simplicity. Subtle horizontal slub variations woven into the yarn provide visual depth and relaxed casual character.',
     'CASUAL_SHIRT', 'HERO_MODELS',
     [{'name': 'Sandstone Taupe', 'hex': '#C5B6A0'}, {'name': 'Oatmeal', 'hex': '#DDD3C3'}],
     ['S', 'M', 'L', 'XL'], '100% Organic Slub Cotton (200g/m)', 'Portugal',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Tactile slub yarn texture with soft handfeel', 'Raw edge chest pocket with bartack reinforcement'],
     False, False),

    ('ts-olive-supima-crewneck', 'Tuscan Olive Supima Cotton Crewneck', 310,
     'American Supima Extra-Long Staple Cotton in Deep Olive',
     'Subtle earthy sophistication. Made from certified Supima cotton known for extra-long fibers that provide twice the strength of regular cotton.',
     'EMERALD_SILK', 'ESSENTIALS_POLO',
     [{'name': 'Tuscan Olive', 'hex': '#3A4432'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Certified American Supima Cotton (190g/m)', 'Albini Group, Italy',
     'Tailored Regular', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Vibrant reactive dye that resists fading', 'Reinforced neck tape from shoulder to shoulder'],
     False, False),

    ('ts-espresso-brown-heavyweight', 'Espresso Brown 260gsm Heavyweight Tee', 330,
     'Roasted Coffee Bean Brown in Dense Compact Jersey',
     'A warm, rich tone for autumn layering. Pairs seamlessly beneath camel coats, olive jackets, and dark grey tailored trousers.',
     'TROUSER_CHARCOAL', 'HERO_MODELS',
     [{'name': 'Espresso Brown', 'hex': '#281B15'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Long-Staple Cotton (260g/m)', 'Portugal',
     'Tailored Regular', 'Winter Collection', 'Winter Collection',
     ['Dense 260gsm jersey with smooth peach finish', 'Twin needle coverstitch at hem and cuffs'],
     False, False),

    ('ts-french-blue-mercerized', 'French Blue Mercerized Giza Tee', 320,
     'Luminous French Blue with Silky Soft Mercerized Finish',
     'A striking color pop under tailored jackets. Double-mercerized for an intense, silky luster that catches natural light with elegance.',
     'NAVY_SUIT', 'SHIRT_WHITE',
     [{'name': 'French Blue', 'hex': '#365983'}],
     ['S', 'M', 'L', 'XL'], '100% Giza 87 Mercerized Cotton (180g/m)', 'Albini Group, Italy',
     'Tailored Regular', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Silky mercerized luster', 'Bound micro-neckband'],
     False, False),

    ('ts-pocket-tee-heavy-white', 'White Heavyweight Sartorial Pocket Tee', 340,
     '260gsm Cotton with Sculpted Mitered Chest Pocket',
     'The elevated workwear tee. Features a tailored mitered chest pocket with an internal pen divider and substantial 260gsm cotton fabric.',
     'SHIRT_WHITE', 'ESSENTIALS_POLO',
     [{'name': 'Chalk White', 'hex': '#FAFAFA'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Heavy Combed Cotton (260g/m)', 'Portugal',
     'Tailored Regular', 'Everyday Luxury', 'Essential Collection',
     ['Mitered chest pocket with hidden pen sleeve', 'Reinforced collar rib'],
     False, False),

    ('ts-waffle-knit-crewneck-grey', 'Grey Melange Waffle-Knit Cotton Long-Sleeve Tee', 360,
     'Textured Honeycomb Cotton Knit for Layering',
     'Breathable thermal waffle texture. Worn beneath casual shirts or as an elevated weekend tee over tailored trousers.',
     'TROUSER_CHARCOAL', 'HERO_MODELS',
     [{'name': 'Grey Melange', 'hex': '#7A7E86'}],
     ['S', 'M', 'L', 'XL'], '100% Combed Cotton Waffle Knit (240g/m)', 'Portugal',
     'Tailored Regular', 'Winter Collection', 'Winter Collection',
     ['Honeycomb waffle texture with natural stretch', 'Ribbed cuffs that stay in place'],
     False, False),

    ('ts-burgundy-silk-cotton-tee', 'Imperial Burgundy Silk-Cotton Crewneck', 380,
     '55% Silk, 45% Cotton in Deep Jewel-Toned Wine',
     'Nocturnal richness. The subtle sheen of mulberry silk transforms this tee into a valid black-tie cocktail layering piece beneath evening jackets.',
     'EVENING_SUIT', 'PACKAGING',
     [{'name': 'Imperial Burgundy', 'hex': '#42101B'}],
     ['S', 'M', 'L', 'XL'], '55% Mulberry Silk, 45% Giza Cotton', 'Como, Italy',
     'Slim Fit', 'Evening Black-Tie', 'Evening Collection',
     ['Saturated jewel-tone dye', 'Blind-stitched seamless hems'],
     True, False),

    ('ts-oatmeal-heather-cotton-linen', 'Oatmeal Cotton-Linen Breathable Tee', 310,
     '70% Cotton, 30% French Linen in Natural Oatmeal Heather',
     'Cooling linen properties combined with the soft familiarity of cotton. Natural slubs provide a casual, earthy texture.',
     'CASUAL_SHIRT', 'TRAD_IVORY',
     [{'name': 'Oatmeal Heather', 'hex': '#D4C9B8'}],
     ['S', 'M', 'L', 'XL'], '70% Long-Staple Cotton, 30% French Linen (190g/m)', 'France & Portugal',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Breathable cotton-linen blend', 'Self-fabric crew neckband'],
     False, False),

    ('ts-oversized-boxy-charcoal', 'Boxy Oversized Heavyweight Tee (Charcoal)', 350,
     'Substantial 300gsm Heavyweight Cotton with Dropped Shoulder',
     'Contemporary street-luxe architecture. Heavy 300gsm combed cotton jersey that hangs completely square with wide elbow-length sleeves.',
     'TROUSER_CHARCOAL', 'BLACK_SUIT',
     [{'name': 'Washed Charcoal', 'hex': '#2D2D30'}],
     ['S', 'M', 'L', 'XL'], '100% Ultra-Heavyweight Combed Cotton (300g/m)', 'Portugal',
     'Relaxed Drape', 'Everyday Luxury', 'Signature Collection',
     ['Architectural boxy silhouette with dropped shoulders', 'Wide elbow-length sleeve opening'],
     True, False),

    ('ts-striped-breton-navy-white', 'Breton Nautical Striped Long-Sleeve Tee', 360,
     'Heavy 240gsm Cotton with Boatneck Collar & Navy Stripes',
     'Timeless French naval heritage. Horizontal 2cm navy and white nautical stripes with an authentic boatneck neckline and straight hem.',
     'NAVY_SUIT', 'SHIRT_WHITE',
     [{'name': 'Navy & White Stripe', 'hex': '#162238'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '100% Heavy Breton Cotton Jersey (240g/m)', 'Brittany, France',
     'Tailored Regular', 'Resort & Casual', 'Summer Collection',
     ['Authentic wide boatneck collar', 'Yarn-dyed horizontal nautical stripes', 'Side hem vents'],
     False, True),
]

print(f"Polos configured: {len(polos)}")
print(f"T-Shirts configured: {len(tshirts)}")
