# 26 Unique Formal Shirts for N.K FABRICS

formal_shirts = [
    ('fs-white-royal-poplin', 'Royal Poplin Formal Shirt (White)', 650,
     'Swiss Giza 45 Cotton with French Cuffs & Brass Stays',
     'Immaculate white dress shirt woven from ultra-long-staple Egyptian cotton. Structured semi-spread collar, French double cuffs, and genuine iridescent mother-of-pearl buttons.',
     'SHIRT_WHITE', 'FABRIC_DETAIL',
     [{'name': 'Crisp White', 'hex': '#FFFFFF'}, {'name': 'Ivory', 'hex': '#FAF8F5'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0', '17.5'], '100% Giza 45 Egyptian Cotton Poplin (200/2 count)', 'Thomas Mason, Albini Group, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Signature Collection',
     ['Removable solid brass engraved collar stays included', '22 stitches per inch single-needle tailoring', 'French double cuffs designed for cufflinks'],
     False, True),

    ('fs-sky-blue-end-on-end', 'End-on-End Formal Shirt (Sky Blue)', 680,
     'Two-Tone Zephyr Weave with Modern Spread Collar',
     'Interweaves white and azure yarns to produce an ethereal two-tone depth that pairs harmoniously with charcoal and navy bespoke suiting.',
     'SHIRT_WHITE', 'NAVY_SUIT',
     [{'name': 'Sky Blue', 'hex': '#D0E2EE'}, {'name': 'French Blue', 'hex': '#9BB8D3'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], 'Super 160s Egyptian Cotton End-on-End', 'Alumo, Appenzell, Switzerland',
     'Tailored Regular', 'Business & Boardroom', 'Business Collection',
     ['Spread collar designed for full or half Windsor knots', 'Australian mother-of-pearl buttons cross-stitched by hand'],
     False, False),

    ('fs-marcella-pique-evening', 'Marcella Piqué Evening Dress Shirt', 750,
     'Formal White-Tie Evening Shirt with Stud Front & Wing Collar',
     'The pinnacle of nocturnal formality. Heavy waffle-textured Marcella bib front with convertible stud placket, finished with a classic wing collar.',
     'SHIRT_WHITE', 'EVENING_SUIT',
     [{'name': 'Pure White', 'hex': '#FFFFFF'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0', '17.5'], 'Giza 45 Cotton with Marcella Piqué Waffle Bib Front', 'Thomas Mason Bespoke',
     'Classic Formal', 'Evening Black-Tie', 'Evening Collection',
     ['Wing collar with interlining that sustains crisp stance through banquets', 'Removable studs slot (compatible with studs or standard buttons)'],
     True, False),

    ('fs-fine-bengal-stripe', 'Fine Bengal Stripe Business Shirt', 620,
     'Alternating Navy & White Precision Bengal Stripe',
     'An executive sartorial classic. Clean 1/8-inch navy stripes on an Egyptian cotton poplin ground, equipped with a semi-spread collar.',
     'SHIRT_WHITE', 'HERO_MODELS',
     [{'name': 'Navy & White Stripe', 'hex': '#2A4465'}, {'name': 'Sky & White Stripe', 'hex': '#638BB8'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '2-Ply Egyptian Cotton Poplin (140/2)', 'Albini Group, Bergamo, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Business Collection',
     ['Pattern matched across shoulder yoke and split placket', 'Two-button mitered cuffs'],
     False, False),

    ('fs-nocturne-black-silk-voile', 'Nocturne Silk-Voile Evening Shirt', 780,
     'Pure Silk Voile with Hidden Placket & Dark Mother-of-Pearl Buttons',
     'Created for black-tie galas and cocktail evenings. Translucent black mulberry silk voile with a whisper-light hand and midnight mother-of-pearl buttons.',
     'SHIRT_WHITE', 'BLACK_SUIT',
     [{'name': 'Pitch Black', 'hex': '#0B0B0B'}, {'name': 'Nocturne Charcoal', 'hex': '#1C1C1C'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '100% Mulberry Silk Voile (110g/m)', 'Como, Italy',
     'Slim Fit', 'Evening Black-Tie', 'Evening Collection',
     ['Concealed placket with dark smoked mother-of-pearl buttons', 'Clean semi-spread collar with soft interlining'],
     True, False),

    ('fs-sea-island-ivory-herringbone', 'Sea Island Ivory Herringbone Shirt', 690,
     'West Indian Sea Island Cotton in Fine Micro-Herringbone Weave',
     'The rarest cotton in the world. Harvested exclusively in the West Indies, offering cashmere-like softness and a refined micro-herringbone zigzag luster.',
     'SHIRT_WHITE', 'TRAD_IVORY',
     [{'name': 'Ivory Herringbone', 'hex': '#FAF7F0'}, {'name': 'Alabaster', 'hex': '#F0ECE0'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0', '17.5'], '100% Certified West Indian Sea Island Cotton', 'Wisica Certified / Thomas Mason',
     'Tailored Regular', 'Wedding & Gala', 'Signature Collection',
     ['Micro-herringbone weave reflects light three-dimensionally', 'French double cuffs with hand-stitched buttonholes'],
     False, True),

    ('fs-ambassador-micro-twill', 'Ambassador Micro-Twill Shirt (White)', 720,
     'High-Luster Compact Twill with Hand-Rolled French Cuffs',
     'The executive favorite. The diagonal micro-twill weave gives off a radiant luster that stays crisp under suiting throughout 14-hour days.',
     'SHIRT_WHITE', 'NAVY_SUIT',
     [{'name': 'Crisp White', 'hex': '#FFFFFF'}, {'name': 'Pale Blue', 'hex': '#E2EDF7'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], 'Super 180s Compact Egyptian Giza Twill', 'Alumo, Switzerland',
     'Tailored Regular', 'Business & Boardroom', 'Formal Collection',
     ['Split-yoke shoulder for natural upper-back curvature', 'Solid brass engraved collar stays'],
     False, False),

    ('fs-pale-rose-royal-oxford', 'Pale Rose Royal Oxford Shirt', 640,
     'Subtle Powder Pink Royal Oxford with Spread Collar',
     'A distinguished continental statement. The delicate powder pink shade enlivens grey and navy suiting while the royal Oxford weave provides rich visual weight.',
     'SHIRT_WHITE', 'TROUSER_CHARCOAL',
     [{'name': 'Pale Rose Pink', 'hex': '#F7E7E7'}, {'name': 'Blush Ivory', 'hex': '#FAF0F0'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '2-Ply Royal Oxford Cotton (120/2)', 'Albini Group, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Business Collection',
     ['Clean semi-spread collar with removable brass stays', 'Double-stitched side seams with reinforced pentagonal gusset'],
     False, False),

    ('fs-charcoal-pinpoint-oxford', 'Charcoal Pinpoint Formal Shirt', 620,
     'Fine Pinpoint Oxford Weave in Deep Anthracite Grey',
     'A modern monochromatic option. Deep grey pinpoint cotton that pairs sharply with black suits and silk knit neckwear.',
     'SHIRT_WHITE', 'HERO_MODELS',
     [{'name': 'Charcoal Grey', 'hex': '#383838'}, {'name': 'Smoke Grey', 'hex': '#555555'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '100% Giza Cotton Pinpoint Oxford', 'Thomas Mason, Italy',
     'Slim Fit', 'Formal Collection', 'Formal Collection',
     ['English cutaway collar', 'Single rounded barrel cuffs with horn buttons'],
     False, False),

    ('fs-cream-silk-blend-formal', 'Cream Silk-Cotton Spread Collar Shirt', 710,
     'Lustrous 50% Mulberry Silk, 50% Egyptian Cotton Twill',
     'The ultimate wedding guest and reception shirt. A warm ivory cream sheen that catches celebration candlelight with graceful elegance.',
     'SHIRT_WHITE', 'TRAD_IVORY',
     [{'name': 'Warm Cream', 'hex': '#F5EFE3'}, {'name': 'Champagne Ivory', 'hex': '#ECE3D0'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '50% Mulberry Silk, 50% Egyptian Cotton', 'Como & Bergamo, Italy',
     'Tailored Regular', 'Wedding & Gala', 'Wedding Collection',
     ['French double cuffs with hand-stitched bar tacks', 'Mother-of-pearl buttons with gold thread loops'],
     True, False),

    ('fs-navy-micro-houndstooth', 'Navy Micro-Houndstooth Formal Shirt', 660,
     'Microscopic Scale Navy & White Houndstooth Weave',
     'Reads as a textured powder blue from two steps away. The fine micro-houndstooth adds textural intrigue under plain worsted suiting.',
     'SHIRT_WHITE', 'NAVY_SUIT',
     [{'name': 'Navy Micro-Check', 'hex': '#283B54'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '2-Ply Egyptian Cotton (160/2)', 'Alumo, Switzerland',
     'Tailored Regular', 'Business & Boardroom', 'Business Collection',
     ['Extreme cutaway collar designed for large tie knots', 'Curved hem with reinforced side gussets'],
     False, False),

    ('fs-pleated-bib-tuxedo-white', 'Classic Pleated-Bib Tuxedo Shirt', 760,
     '0.5cm Accordion Pleats in Giza 87 Egyptian Cotton',
     'The definitive black-tie evening standard. Twelve precision razor-pleats flank the front placket, fastened with convertible black onyx studs.',
     'SHIRT_WHITE', 'EVENING_SUIT',
     [{'name': 'Crisp White', 'hex': '#FFFFFF'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0', '17.5'], 'Giza 87 Egyptian Cotton with Pleated Voile Bib', 'Thomas Mason Bespoke',
     'Classic Formal', 'Evening Black-Tie', 'Evening Collection',
     ['Turn-down formal collar with rigid interlining', 'French double cuffs with rounded corners'],
     False, True),

    ('fs-ice-blue-royal-twill', 'Ice Blue Sovereign Royal Twill Shirt', 670,
     'Frosty Ice Blue Compact Twill with Luminous Sheen',
     'A crisp visual tonic against midnight navy suits. The light-refracting diagonal twill weave gives an immaculate smooth front throughout the day.',
     'SHIRT_WHITE', 'NAVY_SUIT',
     [{'name': 'Ice Blue', 'hex': '#E3EDF7'}, {'name': 'Glacier Blue', 'hex': '#D4E4F5'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], 'Super 160s Egyptian Giza Twill', 'Albini Group, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Formal Collection',
     ['Wide spread collar with removable brass stays', 'Two-button mitered cuffs'],
     False, False),

    ('fs-black-poplin-french-cuff', 'Midnight Noir Poplin Dress Shirt', 660,
     'Ultra-Black Mercerized Cotton with French Double Cuffs',
     'Deep, saturated black that retains its dark pigment without fading. Engineered for nocturnal formal events, paired with silver or gold cufflinks.',
     'SHIRT_WHITE', 'BLACK_SUIT',
     [{'name': 'Jet Black', 'hex': '#0A0A0A'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '100% Giza 87 Mercerized Cotton Poplin', 'Albini Group, Italy',
     'Slim Fit', 'Evening Black-Tie', 'Evening Collection',
     ['Concealed fly placket', 'Dark smoked iridescent mother-of-pearl buttons'],
     True, False),

    ('fs-french-blue-hairline-stripe', 'French Blue Hairline Stripe Shirt', 630,
     'Microscopic Hairline Stripe in Egyptian Giza 45 Cotton',
     'Sophisticated micro-geometry. The ultra-fine lines create an optical illusion of solid soft blue, revealing its meticulous striped craft up close.',
     'SHIRT_WHITE', 'HERO_MODELS',
     [{'name': 'French Blue Stripe', 'hex': '#41638A'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '2-Ply Egyptian Cotton Hairline Weave (140/2)', 'Thomas Mason, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Business Collection',
     ['Semi-spread collar with 3.25-inch collar points', 'Single-needle stitching throughout'],
     False, False),

    ('fs-silver-grey-end-on-end', 'Silver Grey End-on-End Formal Shirt', 650,
     'Alternating White & Charcoal Threads in a Fine Weave',
     'A modern cool-neutral shirt that sits brilliantly under charcoal and black suiting. Mother-of-pearl buttons provide a gleaming finish.',
     'SHIRT_WHITE', 'TROUSER_CHARCOAL',
     [{'name': 'Silver Grey', 'hex': '#A8ADB5'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], 'Super 140s Egyptian Cotton', 'Alumo, Switzerland',
     'Tailored Regular', 'Formal Collection', 'Formal Collection',
     ['Medium spread collar with 8.5cm point spread', 'Two-button rounded cuff'],
     False, False),

    ('fs-white-dobby-micro-check', 'White Dobby Geometric Micro-Check Shirt', 680,
     'Tone-on-Tone Raised Dobby Weave with Visual Depth',
     'An understated white shirt with three-dimensional interest. The subtle dobby jacquard texture catches natural sunlight with refined distinction.',
     'SHIRT_WHITE', 'FABRIC_DETAIL',
     [{'name': 'White Dobby', 'hex': '#FAF9F7'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '100% Giza 45 Cotton Dobby Jacquard', 'Albini Group, Italy',
     'Tailored Regular', 'Wedding & Gala', 'Signature Collection',
     ['French double cuffs with hand-stitched buttonholes', 'Removable brass stays'],
     False, False),

    ('fs-classic-white-tab-collar', 'Savile Row Tab-Collar Formal Shirt', 690,
     'Traditional Collar Tab with Snap Fastener & French Cuffs',
     'Pushes tie knots forward and upward into a prominent, proud arch. Crafted from heavyweight Swiss poplin for boardroom distinction.',
     'SHIRT_WHITE', 'NAVY_SUIT',
     [{'name': 'Pure White', 'hex': '#FFFFFF'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '200/2 Swiss Cotton Poplin', 'Alumo, Switzerland',
     'Slim Fit', 'Business & Boardroom', 'Signature Collection',
     ['Point collar with snap tab closure under tie knot', 'French double cuffs'],
     True, False),

    ('fs-sky-blue-royal-oxford', 'Sky Blue Royal Oxford Dress Shirt', 640,
     'Heavyweight Royal Basketweave with Cutaway Collar',
     'Substantial body with unmatched drape. The basketweave texture provides tactile luxury while remaining crisp under heavy worsted suit jackets.',
     'SHIRT_WHITE', 'HERO_MODELS',
     [{'name': 'Sky Blue Oxford', 'hex': '#7FA4C4'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '2-Ply Royal Oxford Cotton (120/2)', 'Thomas Mason, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Business Collection',
     ['Cutaway collar with wide tie spread', 'Curved hem for secure tucking'],
     False, False),

    ('fs-lavender-end-on-end', 'Pale Lavender End-on-End Formal Shirt', 650,
     'Subtle Violet and White Interwoven Zephyr Yarns',
     'A patrician choice for spring and summer formal wear. The delicate lilac shade complements grey flannel and navy wool suits with quiet warmth.',
     'SHIRT_WHITE', 'CHALK_STRIPE',
     [{'name': 'Pale Lavender', 'hex': '#D4CCE0'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], 'Super 150s Egyptian Cotton End-on-End', 'Albini Group, Italy',
     'Tailored Regular', 'Formal Collection', 'Formal Collection',
     ['Spread collar with removable stays', 'Mother-of-pearl buttons'],
     False, False),

    ('fs-ecru-silk-cashmere-shirt', 'Ecru Silk-Cashmere Evening Dress Shirt', 790,
     '85% Giza Cotton, 15% Cashmere with French Cuffs',
     'Soft as a cloud. An ultra-fine blend of Egyptian cotton and Mongolian cashmere in a warm ecru hue, designed for winter galas and black-tie dinners.',
     'SHIRT_WHITE', 'EVENING_SUIT',
     [{'name': 'Warm Ecru', 'hex': '#EFE9DE'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '85% Giza Cotton, 15% Cashmere (Albiate)', 'Albini Group, Italy',
     'Classic Formal', 'Evening Black-Tie', 'Winter Collection',
     ['French double cuffs with hand-stitched eyelets', 'Extreme thermal softness'],
     True, False),

    ('fs-graph-check-navy-white', 'Executive Graph Check Formal Shirt', 620,
     'Clean 5mm Navy Windowpane Grid on Pure White Poplin',
     'A contemporary executive look. The crisp geometry adds focus and proportion beneath solid charcoal and navy bespoke suiting.',
     'SHIRT_WHITE', 'HERO_MODELS',
     [{'name': 'Navy Graph Check', 'hex': '#223854'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '100% Giza Cotton Poplin (140/2)', 'Thomas Mason, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Business Collection',
     ['Spread collar', 'Pattern-matched split shoulder yoke'],
     False, False),

    ('fs-ivory-silk-pleated-ceremony', 'Ivory Silk Pleated Ceremony Shirt', 780,
     'Mulberry Silk Crepe de Chine with Micro-Pleated Bib',
     'An imperial wedding shirt. Fluid mulberry silk crepe that drapes around the torso with regal weight, finished with a subtle pleated front.',
     'SHIRT_WHITE', 'TRAD_IVORY',
     [{'name': 'Ivory Silk', 'hex': '#F7F3E9'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '100% Pure Mulberry Silk Crepe (16 Momme)', 'Como, Italy',
     'Classic Formal', 'Wedding & Gala', 'Wedding Collection',
     ['Micro-pleated bib with concealed fly front', 'Mother-of-pearl buttons with gold loops'],
     False, True),

    ('fs-white-twill-double-cuff', 'Monarch White Heavy Twill Dress Shirt', 670,
     'Opaque 2-Ply Diagonal Twill with Semi-Spread Collar',
     '100% zero-translucency white twill. Perfect under photographic strobes and camera lights, delivering a pristine white presence without show-through.',
     'SHIRT_WHITE', 'BLACK_SUIT',
     [{'name': 'Opaque White', 'hex': '#FFFFFF'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0', '17.5'], '2-Ply Heavy Egyptian Twill (120/2)', 'Albini Group, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Formal Collection',
     ['Semi-spread collar with brass stays', 'French double cuffs with monogram slot'],
     False, False),

    ('fs-blue-white-university-stripe', 'Blue University Bengal Stripe Formal Shirt', 630,
     'Medium 4mm Blue & White Stripe in Crisp Cotton Poplin',
     'The definitive city shirt. Pair with navy chalk stripe or charcoal flannel suits for an authoritative, timeless British silhouette.',
     'SHIRT_WHITE', 'CHALK_STRIPE',
     [{'name': 'City Blue Stripe', 'hex': '#33527A'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], 'Super 140s Egyptian Cotton Poplin', 'Thomas Mason, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Business Collection',
     ['Cutaway collar with 3.5-inch leaf points', 'Mitered single cuffs'],
     False, False),

    ('fs-pure-white-pin-collar', 'Savile Row Gold Pin-Collar Formal Shirt', 720,
     'Collar Eyelets Accommodating Solid 18K Gold Plated Bar Pin',
     'The ultimate bespoke statement. Includes a solid brass gold-plated collar bar that lifts the necktie knot into a sculptured arch.',
     'SHIRT_WHITE', 'BLACK_SUIT',
     [{'name': 'Crisp White', 'hex': '#FFFFFF'}],
     ['15.0', '15.5', '16.0', '16.5', '17.0'], '200/2 Swiss Cotton Poplin', 'Alumo, Switzerland',
     'Slim Fit', 'Business & Boardroom', 'Signature Collection',
     ['Collar eyelets with included 18K gold-plated screw-bar collar pin', 'French double cuffs'],
     True, True),
]

print(f"Formal shirts configured: {len(formal_shirts)}")
