# 22 Unique Shalwar Kameez Ensembles for N.K FABRICS

shalwar_kameez = [
    ('sk-signature-noir-silk', 'Signature Noir Raw Silk Shalwar Kameez', 1850,
     'Pure Hand-Spun Raw Mulberry Silk with Tailored Structured Stance',
     'A monument of Pakistani luxury heritage. We hand-loom pure mulberry raw silk with deliberate slub textures, then tailor it to Savile Row proportions. The mandarin collar stands firm with custom horsehair interfacing.',
     'TRAD_BLACK', 'HERO_MODELS',
     [{'name': 'Midnight Black', 'hex': '#0C0C0C'}, {'name': 'Charcoal Silk', 'hex': '#1E1E1E'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '100% Pure Mulberry Raw Silk (Heavy Drape)', 'Heritage Silk Weavers, Lahore',
     'Tailored Regular', 'Ceremony & Eid', 'Signature Collection',
     ['Structured mandarin band collar with single-needle pick stitch', 'Concealed mobile and cigar pocket in side seam', 'French cuff slits for cufflinks'],
     True, True),

    ('sk-viceroy-emerald-suit', 'Viceroy Emerald Raw Silk Kameez Suit', 1950,
     'Imperial Forest Emerald Raw Silk with Matching Structured Waistcoat',
     'Tailored for grand wedding banquets and state ceremonies. Dense hand-loomed raw silk with natural slubs in an imperial forest green hue, paired with a sculpted matching waistcoat with gold bullion embroidery.',
     'EMERALD_SILK', 'TRAD_GREEN',
     [{'name': 'Viceroy Emerald', 'hex': '#0F2D22'}, {'name': 'Deep Olive Silk', 'hex': '#1E2B1E'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '100% Pure Raw Mulberry Silk (Dense Handloom)', 'Heritage Silk Guild, Lahore',
     'Classic Formal', 'Wedding & Gala', 'Wedding Collection',
     ['Hand-carved horn buttons with gold thread loops', 'Mandarin collar reinforced with double horsehair interfacing', 'Straight tailored trouser pajama with side vents'],
     True, True),

    ('sk-royal-egyptian-giza87', 'Royal Egyptian Cotton Shalwar Kameez', 1450,
     '200/2 Compact Giza 87 Cotton with Silk-Finish Luster',
     'Crafted from the finest long-staple cotton harvested along the Nile river basin. Delivers an impossibly smooth, cool-to-touch sensation and a sculptural drape that remains crease-free throughout long ceremonial celebrations.',
     'TRAD_IVORY', 'HERO_MODELS',
     [{'name': 'Pure Ivory', 'hex': '#FAF8F5'}, {'name': 'Warm Beige', 'hex': '#E6DFD5'}, {'name': 'Soft Ice Blue', 'hex': '#E5ECF2'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '100% Giza 87 Egyptian Cotton (Silk Sheen)', 'Thomas Mason Bespoke',
     'Tailored Regular', 'Ceremony & Eid', 'Eid Collection',
     ['Micro-corded band collar with 1mm embroidered piping', 'French seams and hand-rolled hems', 'Includes matching tailored pleated shalwar'],
     False, True),

    ('sk-wedding-collection-matka', 'Imperial Matka Silk Wedding Shalwar Kameez', 2400,
     'Heavyweight Matka Raw Silk with Matching Embroidered Waistcoat',
     'The sovereign wedding ensemble. Heavyweight raw silk tailored with royal discipline, accompanied by a matching structured waistcoat finished with champagne gold bullion threadwork.',
     'TRAD_IVORY', 'TRAD_BLACK',
     [{'name': 'Imperial Ivory', 'hex': '#FAF8F5'}, {'name': 'Midnight Noir', 'hex': '#0C0C0C'}],
     ['Custom Made-to-Measure', 'Medium (40)', 'Large (42)'], 'Heavy Matka Raw Silk & Fine Wool Blend', 'Heritage Mills, Lahore & Florence',
     'Classic Formal', 'Wedding & Gala', 'Wedding Collection',
     ['Includes two-piece shalwar kameez plus tailored silk waistcoat', 'Over 60 hours of dedicated artisan handwork', 'Hand-stitched bullion embroidery'],
     True, False),

    ('sk-sovereign-pearl-white-eid', 'Sovereign Pearl White Eid Kameez Suit', 1650,
     'Lustrous Silk-Cotton Twill with Silver-Piped Mandarin Collar',
     'Designed exclusively for festive milestone Eid celebrations. Blended mulberry silk and long-staple cotton with a pearlized sheen, accented with 1mm silver bullion piping along the collar and concealed placket.',
     'TRAD_IVORY', 'ESSENTIALS_POLO',
     [{'name': 'Pearl White', 'hex': '#FDFCFA'}, {'name': 'Alabaster', 'hex': '#F4EFE6'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '60% Mulberry Silk, 40% Egyptian Cotton (220g/m)', 'Como & Punjab Artisans',
     'Tailored Regular', 'Ceremony & Eid', 'Eid Collection',
     ['Silver bullion metallic thread hand-piping on collar and cuffs', 'Real mother-of-pearl buttons carved from Australian oyster shells', 'Tailored matching pleated shalwar with drawstring closure'],
     True, False),

    ('sk-aristocrat-steel-grey', 'Aristocrat Steel Grey Compact Twill Kameez', 1550,
     'Compact High-Count Egyptian Twill with Soft Fluid Drape',
     'An authoritative daytime formal ensemble. Woven in a fine diagonal twill that repels creasing, tailored with a clean concealed placket and French cufflink slits for cufflinks.',
     'HERO_MODELS', 'TROUSER_CHARCOAL',
     [{'name': 'Steel Grey', 'hex': '#3E424B'}, {'name': 'Anthracite', 'hex': '#2A2C31'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], 'Giza 45 Long-Staple Cotton Twill (180g/m)', 'Albini Group, Bergamo, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Signature Collection',
     ['Concealed magnetic placket with hand-sewn button reinforcements', 'Dual deep in-seam pockets with velvet coin sleeve', 'Matching straight cut shalwar'],
     False, False),

    ('sk-sapphire-indigo-raw-silk', 'Royal Sapphire Indigo Shalwar Kameez', 1880,
     'Deep Sapphire Raw Silk with Tonal Geometric Stand Collar',
     'Imbued with the grandeur of Mughal evening courts. Dyed with natural indigo and hand-loomed with rich textural slubs, finished with tonal needlepoint along the stand collar.',
     'NAVY_SUIT', 'TRAD_BLACK',
     [{'name': 'Sapphire Indigo', 'hex': '#131F38'}, {'name': 'Midnight Navy', 'hex': '#0B1324'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], 'Pure Raw Silk with Indigo Yarn Dye (Heavy Weight)', 'Lahore Heritage Silk Weavers',
     'Classic Formal', 'Ceremony & Eid', 'Traditional Collection',
     ['Tonal geometric embroidery on band collar and chest placket', 'French seam needlework throughout', 'Includes matching tailored shalwar'],
     True, False),

    ('sk-champagne-matka-ceremony', 'Champagne Gold Matka Silk Ceremony Suit', 2200,
     'Heavy Matka Silk with Gold Bullion Threadwork & Pajama Trouser',
     'The definitive royal groom and milestone banquet ensemble. Tailored from coarse-spun Matka raw silk with an opulent champagne luster that drapes with statuesque majesty.',
     'TRAD_IVORY', 'TAG_TEXTURE',
     [{'name': 'Champagne Gold', 'hex': '#E3D3B5'}, {'name': 'Desert Sand', 'hex': '#CBB48C'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '100% Hand-Loomed Matka Raw Silk (300g/m)', 'Varanasi & Lahore Master Guilds',
     'Classic Formal', 'Wedding & Gala', 'Wedding Collection',
     ['Champagne gold metallic bullion embroidery on cuffs and collar', 'Includes tailored trouser pajama and matching dupatta wrap', 'Horn buttons with gold loops'],
     False, True),

    ('sk-obsidian-slub-silk', 'Obsidian Slub Raw Silk Shalwar Kameez', 1900,
     'Charcoal Slub Raw Silk with Matte Horn Button Accents',
     'Understated dark nobility. Charcoal raw silk woven with pronounced natural slub yarns, paired with matte carved buffalo horn buttons and a sharp mandarin collar.',
     'TRAD_BLACK', 'FABRIC_DETAIL',
     [{'name': 'Obsidian Charcoal', 'hex': '#1C1C1E'}, {'name': 'Pitch Black', 'hex': '#0C0C0C'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], 'Dense Raw Mulberry Silk with Natural Texture (280g/m)', 'Heritage Mills, Lahore',
     'Tailored Regular', 'Formal Collection', 'Signature Collection',
     ['Dual chest pen and spectacles pockets inside placket', 'Reinforced side slits with hand-stitched bartacks', 'Includes matching slub silk shalwar'],
     False, False),

    ('sk-multan-sandstone-linen', 'Multan Sandstone Pure Irish Linen Kameez', 1400,
     'Pure Irish Linen with Natural Breathability & Crisp Stance',
     'Crafted for summer palaces and daytime celebrations. Pure Irish linen harvested and spun in Northern Ireland, then tailored with Pakistani ceremonial discipline.',
     'ESSENTIALS_POLO', 'HERO_MODELS',
     [{'name': 'Sandstone Beige', 'hex': '#D6C8B4'}, {'name': 'Desert Dune', 'hex': '#BCAC98'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '100% Pure Irish Linen (240g/m)', 'Baird McNutt, Northern Ireland',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Natural linen crease memory that softens with age', 'Unlined cuffs with button tab roll-up option', 'Matching linen shalwar'],
     False, False),

    ('sk-deep-plum-mulberry-silk', 'Regal Plum Mulberry Silk Shalwar Kameez', 1980,
     'Deep Violet Plum Raw Silk with Fine Gold Zardozi Collar Accent',
     'Nocturnal richness. Hand-woven mulberry silk in deep jewel-toned plum, accented by a 1cm gold zardozi bullion embroidered collar band.',
     'EVENING_SUIT', 'HERO_MODELS',
     [{'name': 'Regal Plum', 'hex': '#3D1530'}, {'name': 'Nocturne Violet', 'hex': '#2A0B21'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '100% Pure Mulberry Raw Silk (270g/m)', 'Heritage Weavers, Lahore',
     'Classic Formal', 'Wedding & Gala', 'Wedding Collection',
     ['Gold zardozi bullion embroidery on mandarin collar', 'French cuff slits with silk loop fasteners', 'Matching straight pajama trousers'],
     True, False),

    ('sk-classic-white-latha-cotton', 'Imperial White Egyptian Latha Cotton Suit', 1350,
     'High-Density Egyptian Latha Weave with Crisp Glazed Finish',
     'The quintessential traditional Pakistani white suit. Crisp, starched-feel Egyptian latha cotton that stays immaculate through humid celebrations.',
     'TRAD_IVORY', 'SHIRT_WHITE',
     [{'name': 'Optical White', 'hex': '#FFFFFF'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '100% Compact Glazed Egyptian Cotton (180g/m)', 'Albini Group, Italy',
     'Tailored Regular', 'Ceremony & Eid', 'Eid Collection',
     ['Traditional band collar with mother-of-pearl buttons', 'Classic pleated shalwar with drawcord waistband', 'Clean French seams'],
     False, True),

    ('sk-black-boski-silk-suit', 'Imperial Black Boski Silk Shalwar Kameez', 2100,
     'Traditional Spun Silk Boski with Featherweight Fluidity',
     'The revered Boski tradition. Spun silk yarns create an unmatched buttery drape that flows gracefully with every stride, finished with horn buttons.',
     'TRAD_BLACK', 'PRINCE_COAT',
     [{'name': 'Deep Boski Black', 'hex': '#0A0A0A'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '100% Pure Spun Boski Silk (Heavy 10-Pound Weight)', 'Heritage Boski Guild, Punjab',
     'Relaxed Drape', 'Ceremony & Eid', 'Signature Collection',
     ['Traditional loose tailored drape with fluid movement', 'Handmade loop button fasteners', 'Includes authentic Boski silk shalwar'],
     True, False),

    ('sk-ivory-boski-ceremonial', 'Imperial Ivory Boski Silk Shalwar Kameez', 2100,
     'Heavyweight Spun Silk Boski in Natural Creamy Ivory',
     'The gold standard of Pakistani summer luxury. Pure Boski silk with an authentic butter-yellow undertone that cools down high heat instantly.',
     'TRAD_IVORY', 'TAG_TEXTURE',
     [{'name': 'Authentic Boski Ivory', 'hex': '#FDF8E8'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '100% Heavyweight Spun Boski Silk (10-Pound)', 'Punjab Master Boski Weavers',
     'Relaxed Drape', 'Ceremony & Eid', 'Eid Collection',
     ['Buttery handfeel with natural thermal regulation', 'Mandarin stand collar with pick stitching', 'Includes matching Boski shalwar'],
     False, True),

    ('sk-smoke-grey-karandi-winter', 'Smoke Grey Pure Karandi Winter Suit', 1650,
     'Hand-Spun Pakistani Karandi Cotton-Silk for Winter Banquets',
     'Substantial winter warmth. Hand-spun Karandi combines silk and cotton into a textured, tactile cloth that offers majestic thermal insulation.',
     'HERO_MODELS', 'TROUSER_CHARCOAL',
     [{'name': 'Smoke Grey Karandi', 'hex': '#4A4E57'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '70% Hand-Spun Cotton, 30% Wild Raw Silk (Karandi 320g/m)', 'Khyber & Punjab Heritage Guild',
     'Classic Formal', 'Winter Collection', 'Winter Collection',
     ['Dense Karandi texture with thermal insulation', 'Carved horn buttons with metal shanks', 'Straight trouser pajama with side slits'],
     False, False),

    ('sk-forest-green-matka-suit', 'Forest Green Matka Raw Silk Ensemble', 1920,
     'Rich Jewel-Toned Dark Green Raw Silk with Matching Pajama',
     'Created for evening wedding receptions and autumn festivals. Deep botanical green that absorbs lighting with majestic dignity.',
     'EMERALD_SILK', 'TRAD_GREEN',
     [{'name': 'Forest Green', 'hex': '#102B1D'}, {'name': 'Hunter Green', 'hex': '#0A1E14'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '100% Pure Matka Raw Silk (280g/m)', 'Heritage Weavers, Lahore',
     'Classic Formal', 'Wedding & Gala', 'Wedding Collection',
     ['Concealed button placket with mother-of-pearl face buttons', 'Straight tailored trouser pajama with reinforced seams'],
     False, False),

    ('sk-navy-giza-cotton-eid', 'Midnight Navy Egyptian Cotton Shalwar Kameez', 1480,
     'Silky-Smooth Giza 87 Cotton with Tone-on-Tone Piping',
     'Understated midnight grandeur. Woven from Egyptian cotton with a high-luster finish, framed by subtle 1mm navy silk piping on the collar.',
     'NAVY_SUIT', 'HERO_MODELS',
     [{'name': 'Midnight Navy', 'hex': '#0E192D'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '100% Egyptian Giza 87 Cotton (200/2)', 'Thomas Mason, Italy',
     'Tailored Regular', 'Ceremony & Eid', 'Eid Collection',
     ['Micro silk piping on collar and placket', 'Mother-of-pearl buttons', 'Includes tailored matching shalwar'],
     False, False),

    ('sk-terracotta-raw-silk-festive', 'Terracotta Raw Mulberry Silk Kameez Suit', 1890,
     'Hand-Loomed Warm Rust Silk with Gold Thread Neckline Accent',
     'Vibrant, festive, and imperial. Hand-spun raw silk in rich terracotta rust, paired with matching tailored shalwar.',
     'HERO_MODELS', 'TRAD_IVORY',
     [{'name': 'Terracotta Rust', 'hex': '#A04D36'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '100% Pure Mulberry Raw Silk', 'Lahore Silk Guild',
     'Classic Formal', 'Ceremony & Eid', 'Traditional Collection',
     ['Subtle gold thread border on mandarin stand collar', 'Horn buttons with hand-twisted thread loops'],
     True, False),

    ('sk-oatmeal-linen-pajama-suit', 'Raw Oatmeal Irish Linen Kameez & Pajama', 1420,
     'Pure Heavyweight Linen with Straight Trouser Pajama',
     'Contemporary South Asian minimalist tailoring. Earthy unbleached Irish linen tailored with a modern straight trouser pajama rather than loose shalwar.',
     'CASUAL_SHIRT', 'ESSENTIALS_POLO',
     [{'name': 'Raw Oatmeal', 'hex': '#D4C8B5'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '100% Pure Irish Linen (260g/m)', 'Baird McNutt, Ireland',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Straight trouser pajama with side tab adjusters and cuff slits', 'Carved bone buttons', 'French seams'],
     False, False),

    ('sk-charcoal-silk-wool-ceremonial', 'Charcoal Silk-Wool Ceremonial Kameez Suit', 1950,
     '60% Fine Wool, 40% Mulberry Silk for Autumn Formal Occasions',
     'A substantial seasonal ensemble. The wool-silk blend provides architectural drape and structured shoulder lines while breathing naturally.',
     'TROUSER_CHARCOAL', 'TRAD_BLACK',
     [{'name': 'Charcoal Silk-Wool', 'hex': '#2B2B2E'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '60% Merino Wool, 40% Mulberry Silk (250g/m)', 'Biella & Lahore Artisans',
     'Classic Formal', 'Formal Collection', 'Signature Collection',
     ['Mandarin band collar reinforced with double horsehair interfacing', 'Matching straight cut pajama trousers with pockets'],
     False, False),

    ('sk-gold-zari-wedding-kameez', 'Imperial Gold Zari Embroidered Wedding Suit', 2600,
     'Heavy Matka Silk with Handcrafted 24K Gold Zardozi Border',
     'The ultimate groom couture ensemble. Over 90 hours of hand-embroidery with metallic bullion gold wire along the collar, placket, and sleeve hems.',
     'TRAD_IVORY', 'PRINCE_COAT',
     [{'name': 'Antique Ivory & Gold', 'hex': '#FAF6EC'}],
     ['Custom Made-to-Measure', 'Medium (40)', 'Large (42)'], 'Pure Matka Raw Silk with Real Metallic Zari Thread', 'Varanasi Master Looms & N.K FABRICS Atelier',
     'Classic Formal', 'Wedding & Gala', 'Wedding Collection',
     ['90 hours of dedicated hand zardozi bullion embroidery', 'Includes matching embroidered silk dupatta wrap and tailored trouser pajama', 'Solid gilded crest buttons'],
     True, True),

    ('sk-midnight-black-chikankari-suit', 'Nocturne Black Chikankari Shalwar Kameez', 1780,
     'Tone-on-Tone Hand-Embroidered Chikankari on Swiss Voile',
     'Subtle, mysterious nocturnal artistry. Delicate shadow embroidery hand-stitched by master artisans across the entire front chest panel.',
     'TRAD_BLACK', 'EVENING_SUIT',
     [{'name': 'Shadow Black', 'hex': '#080808'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '100% Swiss Cotton Voile with Silk Threadwork', 'Appenzell & Lahore Embroidery Guild',
     'Classic Formal', 'Evening Black-Tie', 'Signature Collection',
     ['Full front panel hand-embroidered chikankari work', 'Concealed snap placket with mother-of-pearl face buttons', 'Includes matching tailored black shalwar'],
     True, False),
]

print(f"Shalwar Kameez configured: {len(shalwar_kameez)}")
