# 22 Unique Waistcoats for N.K FABRICS

waistcoats = [
    ('wc-navy-double-breasted', 'Formal Double-Breasted Horseshoe Waistcoat', 950,
     'Six-Button Horseshoe Silhouette in Super 150s Merino Wool',
     'The crowning touch for modern formal suiting. The horseshoe neckline highlights dress shirt collars and ties while sculpting a tailored midsection.',
     'NAVY_SUIT', 'BLACK_SUIT',
     [{'name': 'Midnight Navy', 'hex': '#121A2A'}, {'name': 'Deep Black', 'hex': '#0C0C0C'}],
     ['38R', '40R', '42R', '44R'], 'Super 150s Pure Wool with Silk Satin Back', 'Dormeuil, France & UK',
     'Tailored Regular', 'Formal Collection', 'Signature Collection',
     ['Six-button double-breasted arrangement', 'Adjustable cinch buckle on silk back panel', 'Four welt pockets for pocket watch and chain'],
     True, True),

    ('wc-noir-jamawar-brocade', 'Imperial Noir Jamawar Brocade Waistcoat', 1250,
     'Pure Silk Brocade with Hand-Finished Mandarin Collar & Gold Thread',
     'Worn with distinction over black or ivory traditional kurtas. Tailored from dense pure silk Jamawar with subtle raised paisley embossing and miniature gold thread piping.',
     'TRAD_BLACK', 'PRINCE_COAT',
     [{'name': 'Noir Jamawar', 'hex': '#0A0A0A'}, {'name': 'Charcoal Brocade', 'hex': '#1C1C1C'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '100% Pure Silk Jamawar Brocade', 'Heritage Mills, Lahore',
     'Classic Formal', 'Ceremony & Eid', 'Traditional Collection',
     ['Structured mandarin collar that stands firm against the neck', 'Fabric-covered silk buttons with gold loop eyelets'],
     True, False),

    ('wc-high-v-charcoal-flannel', 'High-V Flannel Waistcoat (Charcoal)', 890,
     'Five-Button Tailored Vest with Watch Chain Buttonhole',
     'Cut from worsted flannel to pair seamlessly with three-piece suits or over white formal shirting and traditional kurtas.',
     'HERO_MODELS', 'TRAD_BLACK',
     [{'name': 'Charcoal', 'hex': '#242424'}, {'name': 'Black', 'hex': '#0C0C0C'}],
     ['38R', '40R', '42R', '44R', '46L'], 'English Worsted Flannel', 'Somerset, UK',
     'Tailored Regular', 'Business & Boardroom', 'Business Collection',
     ['Five-button front with horn buttons', 'Full cupro lining printed with tonal N.K FABRICS crest'],
     False, False),

    ('wc-emerald-velvet-mandarin', 'Royal Emerald Silk-Velvet Mandarin Waistcoat', 1180,
     'Italian Cotton-Silk Velvet with Mandarin Stand Collar',
     'An opulent ceremonial layer. Deep forest emerald velvet absorbs ambient lighting with deep warmth, accented by gold metallic filigree button details.',
     'EMERALD_SILK', 'TRAD_GREEN',
     [{'name': 'Emerald Velvet', 'hex': '#0E281E'}, {'name': 'Forest Velvet', 'hex': '#071810'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], 'Silk-Cotton Velvet with Lustrous Pile (340g/m)', 'Pontoglio, Brescia, Italy',
     'Slim Fit', 'Wedding & Gala', 'Wedding Collection',
     ['Mandarin collar with gold thread bullion edge', 'Pure silk satin back with engraved brass buckle'],
     True, False),

    ('wc-ceremonial-gold-ivory', 'Ceremonial Silk Waistcoat (Ivory & Gold)', 1100,
     'Pure Raw Silk with Hand-Piped Champagne Gold Threadwork',
     'Engineered specifically for Pakistani wedding banquets, Eid celebrations, and formal ceremonies. Worn elegantly over black or ivory shalwar kameez.',
     'TRAD_IVORY', 'TRAD_BLACK',
     [{'name': 'Ivory & Gold', 'hex': '#FAF8F5'}, {'name': 'Deep Black & Gold', 'hex': '#0C0C0C'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], 'Pure Raw Mulberry Silk with Metallic Gilt Thread', 'Heritage Mills, Lahore',
     'Classic Formal', 'Ceremony & Eid', 'Eid Collection',
     ['Stand collar with hand-piped champagne gold metallic trim', 'Real horn buttons with gold thread loops'],
     False, True),

    ('wc-black-silk-satin-horseshoe', 'Black Silk Satin Horseshoe Tuxedo Vest', 980,
     'Deep Scoop Horseshoe Cut with Fabric-Covered Satin Buttons',
     'Engineered specifically for black-tie dinner suits. The low-scoop horseshoe cut reveals maximum pleated shirt front and Marcella piqué bib.',
     'BLACK_SUIT', 'EVENING_SUIT',
     [{'name': 'Silk Satin Black', 'hex': '#0B0B0B'}, {'name': 'Midnight Blue', 'hex': '#0E1624'}],
     ['38R', '40R', '42R', '44R'], '100% Pure Mulberry Silk Duchess Satin (Como)', 'Como, Italy',
     'Slim Fit', 'Evening Black-Tie', 'Evening Collection',
     ['Three-button low-scoop front', 'Satin back with adjustable cinch belt'],
     False, False),

    ('wc-vintage-donegal-tweed', 'Donegal Houndstooth Wool Tweed Waistcoat', 880,
     'Pure Irish Wool Tweed with Natural Flecks & Leather Knot Buttons',
     'Rugged country nobility. Woven in Donegal with colorful natural wool neps, finished with woven leather knot buttons and four tailored welt pockets.',
     'HERO_MODELS', 'TROUSER_CHARCOAL',
     [{'name': 'Donegal Grey', 'hex': '#3C3C3C'}, {'name': 'Heather Moss', 'hex': '#3B4032'}],
     ['38R', '40R', '42R', '44R'], '100% Pure Irish Donegal Wool Tweed (380g/m)', 'Donegal, Ireland',
     'Classic Formal', 'Winter Collection', 'Winter Collection',
     ['Hand-woven leather knot buttons', 'Four functional welt watch and pen pockets'],
     False, False),

    ('wc-champagne-gold-damask', 'Champagne Gold Damask Silk Waistcoat', 1150,
     'Lustrous Damask Floral Micro-Weave with Mother-of-Pearl Buttons',
     'The regal daytime banquet waistcoat. Woven in Como from silk and cotton with subtle tone-on-tone damask floral patterns that shimmer in natural light.',
     'TRAD_IVORY', 'ESSENTIALS_POLO',
     [{'name': 'Champagne Damask', 'hex': '#E2D5BE'}, {'name': 'Ivory Gold', 'hex': '#F0E6D2'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], '70% Silk, 30% Cotton Damask Weave (220g/m)', 'Como, Italy',
     'Tailored Regular', 'Wedding & Gala', 'Wedding Collection',
     ['Carved mother-of-pearl buttons with gold shank', 'Mandarin collar with satin piped boundary'],
     False, False),

    ('wc-burgundy-silk-jacquard', 'Imperial Burgundy Silk Jacquard Waistcoat', 1050,
     'Intricate Royal Paisley Micro-Jacquard in Deep Wine Luster',
     'A striking evening accent for black-tie suits and reception sherwanis. Rich burgundy silk with a fine self-toned jacquard relief.',
     'EVENING_SUIT', 'HERO_MODELS',
     [{'name': 'Imperial Burgundy', 'hex': '#4A111E'}, {'name': 'Ruby Noir', 'hex': '#360913'}],
     ['38R', '40R', '42R', '44R'], 'Pure Como Mulberry Silk Jacquard', 'Como, Italy',
     'Slim Fit', 'Wedding & Gala', 'Wedding Collection',
     ['Shawl lapel styling on waistcoat front', 'Satin-faced lower welt pockets'],
     True, False),

    ('wc-slate-blue-wool-silk', 'Milanese Slate Grey Silk-Wool Vest', 920,
     'Super 150s Wool-Silk with 5-Button High-V Stance',
     'Versatile executive elegance. Pairs seamlessly with navy and charcoal tailored suits, adding layered depth for boardroom meetings.',
     'NAVY_SUIT', 'TROUSER_CHARCOAL',
     [{'name': 'Slate Grey', 'hex': '#4A525D'}, {'name': 'Steel Blue', 'hex': '#3B4856'}],
     ['38R', '40R', '42R', '44R', '46L'], 'Super 150s Wool & Mulberry Silk', 'Biella, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Business Collection',
     ['Pick-stitched V-neckline', 'Mother-of-pearl smoked buttons'],
     False, False),

    ('wc-sandstone-matka-mandarin', 'Sandstone Matka Raw Silk Mandarin Waistcoat', 980,
     'Coarse Hand-Loomed Matka Silk with Subtle Slub Texture',
     'Textured warmth for festive Eid and daytime ceremonies. Features a high mandarin stand collar that frames the jawline impeccably.',
     'TRAD_IVORY', 'HERO_MODELS',
     [{'name': 'Sandstone', 'hex': '#D4C3AC'}, {'name': 'Oatmeal', 'hex': '#E0D2BD'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'X-Large (44)'], '100% Matka Raw Silk (280g/m)', 'Heritage Looms, Lahore',
     'Classic Formal', 'Ceremony & Eid', 'Eid Collection',
     ['Carved bone buttons with brass eyelets', 'Pure cotton interior lining for breathability'],
     False, False),

    ('wc-black-barathea-single', 'Black Barathea Wool Single-Breasted Waistcoat', 850,
     'Traditional Five-Button Stance in Pure English Wool Barathea',
     'The quintessential black suit companion. Deep, matte black barathea that avoids artificial sheen under bright conference lighting.',
     'BLACK_SUIT', 'TROUSER_CHARCOAL',
     [{'name': 'Pitch Black', 'hex': '#0A0A0A'}],
     ['38R', '40R', '42R', '44R', '46L'], '100% Pure British Wool Barathea (290g/m)', 'Yorkshire, UK',
     'Tailored Regular', 'Formal Collection', 'Formal Collection',
     ['Jetted double pockets', 'Hand-stitched buttonholes with silk gimp'],
     False, False),

    ('wc-cream-linen-summer', 'Riviera Cream Irish Linen Waistcoat', 790,
     'Pure Irish Linen with Horn Buttons & Bemberg Silk Back',
     'Warm-weather formal layering. Breathable open-weave Irish linen that keeps the torso cool while maintaining crisp structural integrity.',
     'ESSENTIALS_POLO', 'TRAD_IVORY',
     [{'name': 'Cream Linen', 'hex': '#F2ECE1'}, {'name': 'Natural Ecru', 'hex': '#E5DCB'}],
     ['38R', '40R', '42R', '44R'], '100% Irish Linen (240g/m)', 'Baird McNutt, Ireland',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Natural horn buttons with matte finish', 'Lightweight cupro lining'],
     False, False),

    ('wc-midnight-pinstripe-vest', 'Savile Row Chalk Pinstripe Wool Waistcoat', 920,
     'English Worsted Flannel with Chalk Pinstripe & Pocket Watch Slit',
     'Boardroom authority. Worn with matching chalk stripe trousers or contrasting solid navy suits to create an unmistakable executive profile.',
     'CHALK_STRIPE', 'NAVY_SUIT',
     [{'name': 'Navy Pinstripe', 'hex': '#142033'}, {'name': 'Charcoal Pinstripe', 'hex': '#252528'}],
     ['38R', '40R', '42R', '44R', '46L'], 'English Worsted Flannel (310g/m)', 'Somerset, UK',
     'Classic Formal', 'Business & Boardroom', 'Signature Collection',
     ['Dedicated horizontal watch chain pocket slit', 'Curved bottom points designed to cover trouser waistband'],
     False, False),

    ('wc-gold-zari-brocade-mandarin', 'Sovereign Gold Zari Brocade Mandarin Waistcoat', 1350,
     'Metallic Gold Bullion Threadwork on Raw Mulberry Silk',
     'The ultimate wedding groom layer. Hand-embroidered zardozi metallic wire along the collar and placket over heavy raw silk.',
     'TRAD_IVORY', 'PRINCE_COAT',
     [{'name': 'Antique Gold', 'hex': '#D4AF37'}, {'name': 'Royal Champagne', 'hex': '#E6CA65'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], 'Pure Silk with Real Metallic Zari Thread', 'Varanasi & Lahore Master Guilds',
     'Classic Formal', 'Wedding & Gala', 'Wedding Collection',
     ['Full hand-stitched zardozi embroidery', 'Concealed magnetic placket with ornamental face buttons'],
     True, False),

    ('wc-chocolate-suede-vest', 'Florence Calf Suede Tailored Vest', 1200,
     'Ultra-Supple Italian Calf Suede with Horn Buttons',
     'Tactile luxury for autumn and winter. Featherweight suede with a velvety nap, tailored with high-V gorge and satin back.',
     'SUEDE_JACKET', 'HERO_MODELS',
     [{'name': 'Espresso Brown', 'hex': '#2E1E17'}, {'name': 'Warm Taupe', 'hex': '#5E4A3B'}],
     ['38R', '40R', '42R', '44R'], '100% Genuine Italian Calf Suede', 'Tuscany, Italy',
     'Tailored Regular', 'Everyday Luxury', 'Winter Collection',
     ['Genuine buffalo horn buttons', 'Satin lining with inner chest pocket'],
     False, False),

    ('wc-ivory-waffle-marcella', 'Marcella Piqué White-Tie Evening Waistcoat', 890,
     'Pure Cotton Marcella Waffle Bib with Low-Scoop Evening Stance',
     'Strict white-tie formal protocol. Heavy Marcella waffle piqué with four mother-of-pearl buttons and adjustable back neck strap.',
     'SHIRT_WHITE', 'TRAD_IVORY',
     [{'name': 'Crisp White', 'hex': '#FFFFFF'}],
     ['38R', '40R', '42R', '44R'], '100% Giza Cotton Marcella Piqué', 'Thomas Mason, Italy',
     'Classic Formal', 'Evening Black-Tie', 'Evening Collection',
     ['Low-scoop front cut', 'Removable button shank mechanism for formal laundering'],
     False, False),

    ('wc-prince-of-wales-plaid-vest', 'Glen Plaid High-V Wool Waistcoat', 940,
     'Fine Glen Check Worsted Wool with Deco Blue Overcheck',
     'British heritage styling. The intricate black and white glen plaid is accented by a subtle sky blue deco thread.',
     'CHALK_STRIPE', 'HERO_MODELS',
     [{'name': 'Glen Plaid Grey', 'hex': '#4A4A4A'}],
     ['38R', '40R', '42R', '44R', '46L'], 'Super 140s Wool (270g/m)', 'Vitale Barberis Canonico, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Signature Collection',
     ['Five-button stance with notched hem', 'Bemberg cupro lining'],
     False, False),

    ('wc-royal-indigo-raw-silk', 'Royal Indigo Slub Silk Mandarin Waistcoat', 1080,
     'Natural Indigo-Dyed Raw Silk with Silver Thread Piping',
     'Rich, nocturnal South Asian grandeur. The deep sapphire indigo hue is framed by microscopic 1mm silver bullion piping.',
     'NAVY_SUIT', 'TRAD_BLACK',
     [{'name': 'Royal Indigo', 'hex': '#13213B'}, {'name': 'Midnight Blue', 'hex': '#0A1322'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], 'Pure Hand-Spun Raw Mulberry Silk', 'Lahore Heritage Silk Weavers',
     'Classic Formal', 'Ceremony & Eid', 'Traditional Collection',
     ['Silver bullion metallic thread piping', 'Mother-of-pearl buttons with hand-sewn loop fasteners'],
     True, False),

    ('wc-houndstooth-monochrome-db', 'Monochrome Houndstooth Double-Breasted Waistcoat', 960,
     'Micro Puppytooth Pure Wool with Peak Lapels & 6-Button Closure',
     'Dapper vintage tailoring. The double-breasted arrangement features small lapels and a straight hem that sits flush over trouser waistbands.',
     'TROUSER_CHARCOAL', 'HERO_MODELS',
     [{'name': 'Black & White Houndstooth', 'hex': '#333333'}],
     ['38R', '40R', '42R', '44R'], 'Super 130s Pure Wool (280g/m)', 'Fox Brothers, UK',
     'Tailored Regular', 'Formal Collection', 'Formal Collection',
     ['Six-button double-breasted front with small peak lapels', 'Buckle adjuster at back'],
     False, False),

    ('wc-forest-green-velvet-db', 'Bespoke Forest Velvet Double-Breasted Waistcoat', 1190,
     'Heavy Cotton-Silk Velvet in Deep Hunter Green with Shawl Lapel',
     'Commanding evening flair. The rich green velvet pile creates remarkable visual depth under soft lighting, styled with shawl lapels.',
     'EMERALD_SILK', 'EVENING_SUIT',
     [{'name': 'Forest Green', 'hex': '#142B1E'}, {'name': 'Deep Emerald', 'hex': '#0C1C13'}],
     ['38R', '40R', '42R', '44R'], 'Italian Cotton-Silk Velvet (360g/m)', 'Redaelli Velluti, Como',
     'Slim Fit', 'Evening Black-Tie', 'Evening Collection',
     ['Double-breasted four-button closure with shawl lapel', 'Covered velvet buttons'],
     True, False),

    ('wc-platinum-silk-wedding', 'Platinum Silver Silk Wedding Waistcoat', 1220,
     'Lustrous Metallic Silk Weave with Engraved Silver Filigree Buttons',
     'Conceived for high-society wedding ceremonies. Shimmering platinum silver silk tailored with a flattering V-line and silk satin back.',
     'TRAD_IVORY', 'HERO_MODELS',
     [{'name': 'Platinum Silver', 'hex': '#C8CCD4'}, {'name': 'Pearl White', 'hex': '#E8ECF2'}],
     ['Small (38)', 'Medium (40)', 'Large (42)', 'Custom Bespoke'], 'Pure Silk & Lurex Blend (230g/m)', 'Como, Italy',
     'Tailored Regular', 'Wedding & Gala', 'Wedding Collection',
     ['Engraved silver filigree metal buttons', 'Contrasting silk welt pockets'],
     False, True),
]

print(f"Waistcoats configured: {len(waistcoats)}")
