# 16 Jackets (STRICTLY NO BLAZERS!) and 16 Sweaters for N.K FABRICS

jackets = [
    ('jk-suede-harrington-espresso', 'Florence Calf Suede Harrington Jacket', 2450,
     'Supple Italian Calf Suede with Double-Zip & Ribbed Collar Trim',
     'The pinnacle of casual outerwear luxury. Featherweight Italian calf suede with a velvety nap, tailored with a dual two-way Lampo zipper and clean buttoned flap pockets.',
     'SUEDE_JACKET', 'HERO_MODELS',
     [{'name': 'Espresso Brown', 'hex': '#281A14'}, {'name': 'Cognac Tan', 'hex': '#583D2A'}],
     ['38R', '40R', '42R', '44R'], '100% Ultra-Soft Italian Calf Suede', 'Tuscany, Italy',
     'Tailored Regular', 'Everyday Luxury', 'Signature Collection',
     ['Two-way solid brass Lampo zipper gilded in champagne gold', 'Ribbed wool-cashmere interior collar stand and cuffs', 'Silk cupro lining with dual interior pockets'],
     True, True),

    ('jk-royal-prince-coat-black', 'Sovereign Royal Velvet Prince Coat', 2850,
     'Midnight Black Velvet Prince Coat with Gold Zardozi Bullion Collar',
     'The crowning jewel of South Asian formal royalty. Tailored in an authoritative structured prince coat silhouette from deep Italian silk-cotton velvet, adorned with handcrafted 24K gold bullion zardozi embroidery on the mandarin collar and French cuffs.',
     'PRINCE_COAT', 'BLACK_SUIT',
     [{'name': 'Midnight Velvet Noir', 'hex': '#080808'}, {'name': 'Royal Navy Velvet', 'hex': '#0B132B'}],
     ['38R', '40R', '42R', '44R', '46L', 'Custom Bespoke'], 'Heavy Venetian Silk-Cotton Velvet (380g/m)', 'Redaelli Velluti, Como & Lahore Royal Guild',
     'Classic Formal', 'Wedding & Gala', 'Wedding Collection',
     ['Over 90 hours of hand-guided zardozi gold bullion embroidery', 'Full floating chest canvas with military waist suppression', 'Solid brass engraved crest buttons gilded in 18K champagne gold'],
     True, True),

    ('jk-jamawar-wedding-sherwani', 'Imperial Jamawar Wedding Sherwani Jacket', 3400,
     'Woven Pure Silk Jamawar Brocade with Hand-Cut Crystal Buttons',
     'An heirloom wedding creation. Woven from genuine pure silk Jamawar with intricate paisley and royal crest motifs, structured with Savile Row chest padding for an unyielding regal stance.',
     'TRAD_IVORY', 'PRINCE_COAT',
     [{'name': 'Antique Gold Jamawar', 'hex': '#CDB788'}, {'name': 'Ivory Silver Brocade', 'hex': '#E2DCD0'}],
     ['38R', '40R', '42R', '44R', 'Custom Bespoke'], '100% Pure Mulberry Silk Jamawar Brocade', 'Varanasi Master Weavers & N.K FABRICS Atelier',
     'Classic Formal', 'Wedding & Gala', 'Wedding Collection',
     ['Hand-set crystal and filigree metal buttons', 'Full silk cupro interior lining printed with N.K FABRICS monogram', 'Accompanied by custom velvet garment storage trunk'],
     True, False),

    ('jk-midnight-velvet-smoking', 'Midnight Velvet Smoking Jacket', 2200,
     'Heavy Venetian Cotton Velvet with Quilted Silk Shawl Lapels',
     'The pinnacle of private club luxury. Tailored from lustrous midnight black Italian cotton velvet, finished with a hand-quilted diamond silk shawl collar and braided frog closures.',
     'EVENING_SUIT', 'BLACK_SUIT',
     [{'name': 'Midnight Black', 'hex': '#0C0C0C'}, {'name': 'Deep Burgundy', 'hex': '#2A0808'}],
     ['38R', '40R', '42R', '44R'], 'Heavy Cotton Velvet (380g/m)', 'Pontoglio 1883, Brescia, Italy',
     'Tailored Regular', 'Evening Black-Tie', 'Evening Collection',
     ['Quilted silk satin shawl collar and matching turn-back cuffs', 'Handmade silk frog toggle closure', 'Two jetted lower pockets'],
     False, True),

    ('jk-casablanca-dinner-jacket', 'Casablanca Ivory Silk Dinner Jacket', 2450,
     'Unbleached Wool-Silk Barathea with Sweeping Shawl Collar',
     'The golden age of warm-weather black tie. Woven in an ivory barathea that resists yellowing under lighting, finished with a curved shawl collar and carved mother-of-pearl buttons.',
     'ESSENTIALS_POLO', 'TRAD_IVORY',
     [{'name': 'Ivory Barathea', 'hex': '#FDFBF5'}, {'name': 'Alabaster', 'hex': '#F4ECE0'}],
     ['38R', '40R', '42R', '44R'], 'Fine Wool & Mulberry Silk Barathea (260g/m)', 'Holland & Sherry, Savile Row',
     'Classic Formal', 'Evening Black-Tie', 'Evening Collection',
     ['Continuous sweeping shawl collar without break', 'Single-button evening stance with jetted pockets', 'Silk-faced covered buttons'],
     True, False),

    ('jk-cashmere-linen-safari', 'Florence Field Safari Jacket', 2100,
     'Cashmere-Linen Twill with Internal Drawstring & Four Bellows Pockets',
     'A sartorial reinterpretation of traditional fieldwear. Blends the breathability of Irish linen with the silky drape of Mongolian cashmere, tailored with horn buttons and an internal drawstring.',
     'ESSENTIALS_POLO', 'TROUSER_CHARCOAL',
     [{'name': 'Olive Drab', 'hex': '#3E4433'}, {'name': 'Espresso Brown', 'hex': '#2F231D'}],
     ['38R', '40R', '42R', '44R'], '60% Irish Linen, 40% Cashmere (290g/m)', 'Piacenza 1733, Italy',
     'Tailored Regular', 'Everyday Luxury', 'Essential Collection',
     ['Four pleated bellows pockets with button flap closures', 'Action back shoulder pleats for driving comfort', 'Dark horn buttons'],
     False, False),

    ('jk-leather-bomber-navy', 'Nappa Leather Ribbed Flight Bomber Jacket', 2600,
     'Buttery French Lambskin Nappa with Cashmere Ribbed Hem',
     'A luxurious aviation monument. Hand-selected French lambskin nappa leather with an impossibly supple temper, paired with 100% cashmere ribbed hem and storm collar.',
     'NAVY_SUIT', 'SUEDE_JACKET',
     [{'name': 'Midnight Navy Nappa', 'hex': '#0F1A2C'}, {'name': 'Pitch Black Nappa', 'hex': '#0A0A0A'}],
     ['38R', '40R', '42R', '44R', '46L'], 'Full-Grain French Lambskin Nappa Leather', 'Annonay Tanneries, France',
     'Tailored Regular', 'Everyday Luxury', 'Signature Collection',
     ['100% cashmere knit ribbed collar, cuffs, and hem', 'Heavyweight brass two-way Lampo zipper', 'Dual snap-down storm flap pockets'],
     True, False),

    ('jk-quilted-microfiber-riding', 'Quilted Equestrian Diamond Riding Jacket', 1650,
     'Water-Repellent Micro-Suede Quilting with Corduroy Collar',
     'Aristocratic British sporting heritage. Matte diamond-quilted microfiber shell lined with lightweight insulation, finished with an English corduroy collar and snap storm flap.',
     'HERO_MODELS', 'TROUSER_CHARCOAL',
     [{'name': 'British Racing Green', 'hex': '#1B3120'}, {'name': 'Midnight Navy', 'hex': '#121F33'}],
     ['38R', '40R', '42R', '44R', '46L'], 'Water-Repellent Microfiber Twill with Primaloft Insulation', 'Lancashire, UK',
     'Tailored Regular', 'Winter Collection', 'Winter Collection',
     ['English corduroy collar and pocket trim', 'Dual rear snap riding vents', 'Brass snap buttons engraved with N.K FABRICS insignia'],
     False, False),

    ('jk-cashmere-overcoat-camel', 'Double-Face Cashmere Winter Overcoat', 3200,
     'Pure Mongolian Double-Face Cashmere with Colossal Lapels',
     'A monumental winter overcoat designed to be worn over bespoke suiting. Hand-split double-face cashmere that requires zero synthetic interlining, falling gracefully to the knee.',
     'HERO_MODELS', 'FABRIC_DETAIL',
     [{'name': 'Golden Camel', 'hex': '#B88A4A'}, {'name': 'Charcoal Flannel', 'hex': '#282828'}],
     ['38R', '40R', '42R', '44R', '46L'], '100% Pure Double-Face Cashmere (520g/m)', 'Piacenza 1733, Biella, Italy',
     'Classic Formal', 'Winter Collection', 'Winter Collection',
     ['Tailored with sufficient chest allowance to layer over suits', 'Hand-finished pick stitching along colossal lapels', 'Genuine unpolished horn buttons'],
     False, True),

    ('jk-unstructured-hopsack-sport', 'Unstructured Navy Hopsack Sport Jacket', 1950,
     'Open-Weave High-Twist Wool with Shirt-Sleeve Shoulder',
     'The most versatile tailored sport jacket in the gentleman’s wardrobe. Completely unlined hopsack wool allows total airflow, pairing seamlessly with both flannel trousers and casual pants.',
     'NAVY_SUIT', 'HERO_MODELS',
     [{'name': 'Classic Navy', 'hex': '#142238'}, {'name': 'Steel Blue', 'hex': '#27384E'}],
     ['38R', '40R', '42R', '44R', '46L'], 'Super 120s High-Ventilation Wool Hopsack (270g/m)', 'Vitale Barberis Canonico, Biella',
     'Tailored Regular', 'Everyday Luxury', 'Essential Collection',
     ['Quarter-lined back with hand-finished French seams', 'Patch hip pockets and barchetta breast pocket', 'Smoked mother-of-pearl buttons'],
     False, False),

    ('jk-shearling-aviator-jacket', 'Merino Shearling Winter Aviator Jacket', 3600,
     'Thick Spanish Merino Shearling with Full-Grain Leather Outer',
     'Unyielding warmth in extreme cold. Plush 15mm Spanish merino sheepskin shearling with a crackled dark brown leather finish and heavy brass buckle collars.',
     'SUEDE_JACKET', 'HERO_MODELS',
     [{'name': 'Espresso Shearling', 'hex': '#2A1A12'}],
     ['38R', '40R', '42R', '44R'], '100% Spanish Merino Lambskin Shearling', 'Zaragoza, Spain',
     'Relaxed Drape', 'Winter Collection', 'Winter Collection',
     ['Plush 15mm natural shearling collar with dual leather buckle straps', 'Heavyweight brass zip mechanism', 'Leather welt handwarmer pockets'],
     True, False),

    ('jk-linen-field-jacket-sand', 'Mediterranean Sand Linen Field Jacket', 1850,
     'Heavy Irish Linen with Storm Placket & Four Bellows Pockets',
     'The ultimate warm-weather adventure layer. Heavyweight linen washed to drape with relaxed authority, featuring an interior waist cinch cord and military storm flap.',
     'CASUAL_SHIRT', 'ESSENTIALS_POLO',
     [{'name': 'Sandstone Linen', 'hex': '#C5B59D'}, {'name': 'Olive Drab', 'hex': '#444A38'}],
     ['38R', '40R', '42R', '44R'], '100% Heavy Pure Irish Linen (320g/m)', 'Baird McNutt, Ireland',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Four large front bellows pockets with hidden snaps', 'Storm flap front over two-way brass zipper', 'Internal drawstring waist'],
     False, False),

    ('jk-harrington-cotton-twill-navy', 'Classic Navy Water-Repellent Harrington Jacket', 1450,
     'Storm-Proof Cotton Gabardine with Signature Silk Tartan Lining',
     'The perennial British icon. High-density waterproof cotton gabardine styled with a stand collar, raglan sleeves for ease of movement, and silk tartan interior.',
     'NAVY_SUIT', 'SUEDE_JACKET',
     [{'name': 'Deep Navy', 'hex': '#111A2B'}, {'name': 'British Khaki', 'hex': '#7A6B53'}],
     ['38R', '40R', '42R', '44R', '46L'], 'Weather-Resistant Compact Cotton Gabardine (280g/m)', 'Lancashire, UK',
     'Tailored Regular', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Raglan sleeves for unrestricted arm motion', 'Two-button stand collar with horn buttons', 'Silk tartan interior body lining with scalloped back umbrella vent'],
     False, True),

    ('jk-down-quilted-vest-cashmere', 'Cashmere-Flannel Quilted Down Gilet Jacket', 1550,
     'Pure Wool-Cashmere Flannel Stuffed with 800-Fill Goose Down',
     'Thermal core warmth for autumn and spring mornings. Cashmere flannel outer shell repels chill while 800-fill white goose down insulates with featherweight lightness.',
     'HERO_MODELS', 'FABRIC_DETAIL',
     [{'name': 'Anthracite Flannel', 'hex': '#242424'}, {'name': 'Navy Blue', 'hex': '#101B2E'}],
     ['38R', '40R', '42R', '44R'], '90% Wool, 10% Cashmere with 800-Fill White Goose Down', 'Biella, Italy & Austria',
     'Tailored Regular', 'Winter Collection', 'Winter Collection',
     ['Genuine 800-fill Austrian white goose down', 'Dual-entry fleece-lined handwarmer pockets', 'Stand collar with internal rib knit'],
     False, False),

    ('jk-wool-chore-jacket-charcoal', 'Savile Row Wool Flannel Chore Jacket', 1680,
     'Heavy English Wool Flannel with Three Patch Pockets',
     'Workwear heritage reimagined through bespoke tailoring. Dense flannel with hand-sewn buttonholes, unlined construction, and three patch utility pockets.',
     'TROUSER_CHARCOAL', 'HERO_MODELS',
     [{'name': 'Charcoal Flannel', 'hex': '#2A2A2A'}],
     ['38R', '40R', '42R', '44R', '46L'], '100% British Wool Flannel (340g/m)', 'Fox Brothers, Somerset, UK',
     'Relaxed Drape', 'Everyday Luxury', 'Signature Collection',
     ['Three exterior patch pockets with barchetta curvature', 'Real unpolished horn buttons', 'Single rear vent'],
     False, False),

    ('jk-black-wool-overcoat-chesterfield', 'Nocturne Black Chesterfield Overcoat', 2950,
     'Super 150s Melton Wool with Black Velvet Upper Collar',
     'The definitive formal overcoat for white-tie and black-tie evenings. Impeccable knee-length tailoring with a concealed button fly placket and velvet top collar.',
     'BLACK_SUIT', 'EVENING_SUIT',
     [{'name': 'Nocturne Black', 'hex': '#0A0A0A'}],
     ['38R', '40R', '42R', '44R', '46L'], 'Heavy British Melton Wool (480g/m)', 'Huddersfield Fine Worsteds, UK',
     'Classic Formal', 'Evening Black-Tie', 'Formal Collection',
     ['Venetian black velvet upper collar', 'Fly front concealing horn buttons', 'Single deep rear walking vent'],
     True, False),
]

# =========================================================================
# 11. SWEATERS & KNITWEAR (16 Products)
# =========================================================================
sweaters = [
    ('sw-cashmere-crewneck-sandstone', '18-Gauge Cashmere Crewneck Sweater', 920,
     'Pure 2-Ply Mongolian Cashmere in Warm Sandstone Beige',
     'Whisper-light yet intensely warm. Knitted on precision 18-gauge Japanese machines with zero side seams for a sculpted, second-skin silhouette.',
     'ESSENTIALS_POLO', 'PACKAGING',
     [{'name': 'Sandstone Beige', 'hex': '#D8CBB7'}, {'name': 'Deep Black', 'hex': '#0C0C0C'}, {'name': 'Navy', 'hex': '#162032'}],
     ['S', 'M', 'L', 'XL'], '100% 2-Ply Grade-A Mongolian Cashmere', 'Biella, Italy',
     'Tailored Regular', 'Everyday Luxury', 'Signature Collection',
     ['Fully fashioned seamless construction', 'Ribbed cuffs and hem with elastane memory thread', 'Self-finished crew neckline'],
     False, True),

    ('sw-cashmere-turtleneck-noir', 'Fine-Gauge Cashmere Turtleneck (Black)', 980,
     '18-Gauge Worsted Cashmere Rollneck for Tailored Layering',
     'The quintessential sartorial cold-weather staple. Designed with a close-fitting rollneck collar that stands firm beneath bespoke suit jackets and coats.',
     'BLACK_SUIT', 'HERO_MODELS',
     [{'name': 'Pitch Black', 'hex': '#0A0A0A'}, {'name': 'Charcoal', 'hex': '#1F1F1F'}],
     ['S', 'M', 'L', 'XL'], '100% Grade-A Mongolian Cashmere', 'Cariaggi Fine Yarns, Marche, Italy',
     'Slim Fit', 'Evening Black-Tie', 'Winter Collection',
     ['Double-folded ribbed turtleneck that never sags', 'Sleek underarm taper to eliminate bunching under suit jackets', 'Ultra-soft handfeel'],
     True, True),

    ('sw-shawl-cardigan-cableknit', 'Cashmere Shawl-Collar Cableknit Cardigan', 1450,
     'Heavy 8-Ply Ribbed Cashmere with Carved Buffalo Horn Buttons',
     'Substantial, protective, and supremely luxurious. Knitted from eight plies of pure Mongolian cashmere with a generous ribbed shawl collar and welt pockets.',
     'HERO_MODELS', 'TROUSER_CHARCOAL',
     [{'name': 'Oatmeal Heather', 'hex': '#CDBFA8'}, {'name': 'Navy Blue', 'hex': '#121C2B'}],
     ['S', 'M', 'L', 'XL'], '100% 8-Ply Mongolian Cashmere (Heavy Weight 650g)', 'Biella, Italy',
     'Relaxed Drape', 'Winter Collection', 'Winter Collection',
     ['Generous shawl collar with horn toggle button closure', 'Hand-sewn horn buttons with genuine leather backing washers', 'Deep waist welt pockets'],
     False, True),

    ('sw-quarter-zip-silk-cashmere', 'Silk-Cashmere Quarter-Zip Pullover', 890,
     '70% Cashmere, 30% Silk with Leather Pull & Lampo Zipper',
     'The modern executive travel layer. Ultra-smooth Italian Lampo zipper finished with a hand-stitched leather pull tab and ribbed mock neck.',
     'ESSENTIALS_POLO', 'NAVY_SUIT',
     [{'name': 'Slate Blue', 'hex': '#2E3D52'}, {'name': 'Espresso', 'hex': '#2B1E19'}],
     ['S', 'M', 'L', 'XL'], '70% Grade-A Cashmere, 30% Mulberry Silk', 'Loro Piana Yarns, Quarona, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Business Collection',
     ['Satin gold Lampo zipper mechanism from Milan', 'Hand-stitched calfskin leather zipper pull', 'Ribbed cuffs and waistband'],
     False, False),

    ('sw-vneck-merino-navy', 'Super 160s Worsted Merino V-Neck Sweater', 680,
     'Ultra-Fine Worsted Merino Wool Designed for Shirt & Tie Pairing',
     'Calculated specifically for the gentleman’s neckwear. The V-neckline reveals shirt collars and tie knots with razor-sharp geometric precision.',
     'NAVY_SUIT', 'SHIRT_WHITE',
     [{'name': 'Midnight Navy', 'hex': '#0E1728'}, {'name': 'Anthracite', 'hex': '#222222'}],
     ['S', 'M', 'L', 'XL', 'XXL'], 'Super 160s Australian Merino Wool (Zegna Baruffa)', 'Biella, Italy',
     'Tailored Regular', 'Business & Boardroom', 'Formal Collection',
     ['V-neck angle cut to expose shirt collar band and tie knot', 'Fine gauge that fits under tailored suit jackets without bulk'],
     False, False),

    ('sw-chunky-fisherman-crewneck', 'Donegal Flecked Wool Fisherman Sweater', 850,
     'Heavy 5-Gauge Irish Wool Knit with Authentic Honeycomb Stitching',
     'Rugged coastal warmth. Knitted in Ireland from pure wool flecked with colorful Donegal tweed neps, featuring traditional honeycomb and cable stitches.',
     'HERO_MODELS', 'ESSENTIALS_POLO',
     [{'name': 'Donegal Cream', 'hex': '#EDE6D8'}, {'name': 'Moss Green', 'hex': '#2E382A'}],
     ['S', 'M', 'L', 'XL'], '100% Pure Irish Wool (5-Gauge Heavy Knit)', 'Donegal, Ireland',
     'Relaxed Drape', 'Winter Collection', 'Winter Collection',
     ['Heavy 5-gauge cable and honeycomb stitch', 'Ribbed crewneck and cuffs with natural elasticity'],
     True, False),

    ('sw-milano-stitch-cardigan-black', 'Milano-Stitch Structured Knit Cardigan', 960,
     'Dense Architectural Milano Rib with Horn Buttons & V-Neck',
     'Knitted with jacket-like body. The dense Milano rib stitch prevents sagging, giving this cardigan the crisp architecture of outerwear.',
     'BLACK_SUIT', 'HERO_MODELS',
     [{'name': 'Deep Black', 'hex': '#080808'}],
     ['S', 'M', 'L', 'XL'], '100% Extra-Fine Worsted Merino Wool (Milano Rib)', 'Biella, Italy',
     'Tailored Regular', 'Everyday Luxury', 'Signature Collection',
     ['Dense Milano rib knit with architectural structure', 'Real buffalo horn buttons', 'Dual tailored patch pockets'],
     False, False),

    ('sw-cashmere-crewneck-burgundy', 'Imperial Burgundy Cashmere Crewneck', 920,
     'Grade-A Mongolian Cashmere in Rich Jewel-Toned Wine',
     'An opulent holiday colorway. Knitted from two-ply worsted cashmere yarns that retain their lofty softness and resist pilling over years of wear.',
     'EVENING_SUIT', 'PACKAGING',
     [{'name': 'Imperial Burgundy', 'hex': '#44111D'}],
     ['S', 'M', 'L', 'XL'], '100% 2-Ply Mongolian Cashmere', 'Cariaggi, Italy',
     'Tailored Regular', 'Wedding & Gala', 'Evening Collection',
     ['Saturated jewel-tone dye', 'Reinforced saddle shoulder seams', 'Ribbed cuffs and hem'],
     True, False),

    ('sw-silk-linen-summer-knit', 'Riviera Silk-Linen Lightweight Summer Sweater', 740,
     'Open-Knit Breathable Blend of Mulberry Silk and French Linen',
     'The ultimate breezy evening knit. Spun from mulberry silk and open-weave linen to provide thermal regulation over polo shirts on coastal evenings.',
     'ESSENTIALS_POLO', 'TRAD_IVORY',
     [{'name': 'Sandstone Ecru', 'hex': '#DDD4C4'}, {'name': 'Navy Blue', 'hex': '#141E30'}],
     ['S', 'M', 'L', 'XL'], '55% Mulberry Silk, 45% French Linen', 'Como & Normandy',
     'Relaxed Drape', 'Resort & Casual', 'Summer Collection',
     ['Open airy stitch permitting air circulation', 'Rolled edge collar and cuffs'],
     False, False),

    ('sw-cashmere-polo-sweater-collar', 'Long-Sleeve Cashmere Polo Collar Sweater', 950,
     'Seamless Knit with Camp-Style Shirt Collar & 3 Horn Buttons',
     'Sprezzatura knitwear. Merges the formal stance of a shirt collar with the cloud-like comfort of pure Mongolian cashmere.',
     'CASUAL_SHIRT', 'HERO_MODELS',
     [{'name': 'Warm Taupe', 'hex': '#665345'}, {'name': 'Midnight Navy', 'hex': '#0F1A2A'}],
     ['S', 'M', 'L', 'XL'], '100% Grade-A Mongolian Cashmere', 'Biella, Italy',
     'Tailored Regular', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Fully fashioned shirt-style collar', 'Genuine carved horn buttons', 'Seamless shoulder construction'],
     False, True),

    ('sw-mockneck-merino-charcoal', 'Fine-Gauge Charcoal Merino Mockneck', 720,
     'Super 160s Merino Wool with 4cm Clean Mock Neckline',
     'The modern minimalist alternative to the turtleneck. Sits cleanly at the base of the neck, creating an athletic, streamlined silhouette under suit jackets.',
     'TROUSER_CHARCOAL', 'BLACK_SUIT',
     [{'name': 'Charcoal Melange', 'hex': '#28282B'}],
     ['S', 'M', 'L', 'XL'], '100% Super 160s Worsted Merino Wool', 'Zegna Baruffa, Italy',
     'Slim Fit', 'Business & Boardroom', 'Signature Collection',
     ['4cm stand mock neckline with shape-memory elastic', 'Fine 18-gauge knit for smooth layering'],
     False, False),

    ('sw-cashmere-hoodie-luxury', 'Sovereign Double-Knit Cashmere Lounge Hoodie', 1150,
     'Heavy 4-Ply Pure Cashmere with Drawstring Hood & Kangaroo Pocket',
     'The ultimate private jet and travel layer. Pure cashmere knit with an internal jersey face, solid brass eyelets, and hand-stitched kangaroo pocket.',
     'ESSENTIALS_POLO', 'HERO_MODELS',
     [{'name': 'Heather Oatmeal', 'hex': '#D4CBBF'}, {'name': 'Pitch Black', 'hex': '#0A0A0A'}],
     ['S', 'M', 'L', 'XL'], '100% 4-Ply Grade-A Mongolian Cashmere', 'Biella, Italy',
     'Relaxed Drape', 'Resort & Casual', 'Limited Edition',
     ['Cashmere knitted drawstring with metal aglets', 'Seamless front kangaroo hand pocket', 'Double-layer cashmere hood'],
     True, False),

    ('sw-cableknit-crewneck-ivory', 'Heavy Ivory Cashmere Cableknit Crewneck', 1280,
     '6-Ply Hand-Guided Cable Stitch in Unbleached Virgin Cashmere',
     'Sculptural three-dimensional knitwear. Traditional rope and diamond cables hand-guided on manual flatbed machines using unbleached ivory cashmere.',
     'TRAD_IVORY', 'HERO_MODELS',
     [{'name': 'Unbleached Ivory', 'hex': '#FAF5EC'}],
     ['S', 'M', 'L', 'XL'], '100% 6-Ply Virgin Cashmere', 'Piacenza 1733, Italy',
     'Tailored Regular', 'Winter Collection', 'Winter Collection',
     ['Intricate dimensional rope cable pattern', 'Heavyweight thermal retention', 'Hand-linked crewneck collar'],
     False, True),

    ('sw-vneck-cashmere-camel', 'Golden Camel Cashmere V-Neck Sweater', 940,
     'Pure Mongolian Cashmere in Classic Camel Tan',
     'Warm, aristocratic, and timeless. Complements white and light blue shirting with soft golden warmth beneath navy and charcoal suiting.',
     'HERO_MODELS', 'ESSENTIALS_POLO',
     [{'name': 'Golden Camel', 'hex': '#B58D56'}],
     ['S', 'M', 'L', 'XL'], '100% 2-Ply Mongolian Cashmere', 'Biella, Italy',
     'Tailored Regular', 'Everyday Luxury', 'N.K FABRICS Essentials',
     ['Deep V-neck cut for tie display', 'Ribbed waistband and cuffs', 'Zero-pilling worsted yarns'],
     False, False),

    ('sw-waffle-knit-thermal-navy', 'Merino Wool Waffle-Knit Thermal Crewneck', 780,
     'Dimensional Waffle Honeycomb Texture in Super 140s Wool',
     'Traps air within miniature knitted pockets for supreme warmth without weight. Modern waffle texture that pairs effortlessly with tailored chinos.',
     'NAVY_SUIT', 'ESSENTIALS_POLO',
     [{'name': 'Midnight Navy', 'hex': '#101B2E'}],
     ['S', 'M', 'L', 'XL'], 'Super 140s Merino Wool (Waffle Knit)', 'Biella, Italy',
     'Tailored Regular', 'Everyday Luxury', 'Essential Collection',
     ['Three-dimensional thermal honeycomb stitch', 'Raglan sleeves for enhanced shoulder movement'],
     False, False),

    ('sw-button-front-knit-vest', 'Cashmere-Wool Sleeveless V-Neck Vest', 650,
     'Four-Button Fine-Gauge Knitted Vest for Business Layering',
     'The lightweight alternative to a fabric waistcoat. Slips over dress shirts under suit jackets to provide torso warmth while keeping arms free.',
     'HERO_MODELS', 'NAVY_SUIT',
     [{'name': 'Charcoal Heather', 'hex': '#303030'}, {'name': 'Navy Blue', 'hex': '#141E30'}],
     ['S', 'M', 'L', 'XL', 'XXL'], '70% Merino Wool, 30% Mongolian Cashmere', 'Biella, Italy',
     'Slim Fit', 'Business & Boardroom', 'Business Collection',
     ['Four real horn button closures', 'Dual jetted micro-pockets', 'Ribbed V-neckline'],
     False, False),
]

print(f"Jackets configured: {len(jackets)}")
print(f"Sweaters configured: {len(sweaters)}")
